### ISSUE TITLE
Komponent datepicker går inte att stänga när man klickar på kalender utan att välja dag

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#116]
### Beskrivning
*När man öppnar en kalender så går det inte att stänga när man klickar på kalender utan att välja dag*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc50**
* Angular version: **version**
* Browsers: **Chrome, IE11**

### Steg för att påvisa problemet
*1.Gå till komponent Datepicker
2. Öppna en kalender
3. Klicka på kalender för att stänga utan att välja datum*

### Förväntat beteende
*Kalender stänger när man klickar på kalender*

### Faktiskt beteende
*Kalender är fortfarande öppen*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by Jbraaf** [comment]
Löst i senare version
