### ISSUE TITLE
Komponent Reactive Forms: Kalender "Välj dag" visar inget Obligatoriskt meddelande när man klickar ur utan att välja dag i Chrome

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#122]
### Beskrivning
*Kalender "Välj dag" visar inget Obligatoriskt meddelande när man klickar ur utan att välja i Chrome*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc64**
* Angular version: **version**
* Browsers: **Chrome**

### Steg för att påvisa problemet
*1. Öppna med Chrome
 2. Klicka på "Välj dag" 
3.  Klicka ur utan att välja dag. *

### Förväntat beteende
*Borde visa felmeddelande "Obligatoriskt".**

### Faktiskt beteende
*Visar inget felmeddelande "Obligatoriskt"*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by CrestTheFury** [comment]
Jag testade nu och får inte samma som du, har du möjlighet att testa igen? Finns en -rc65 nu med

**Comment by FeliciaRingblom** [comment]
Felet uppstår då man klickat på själva kalenderikonen och inte på "Välj datum". Detta problemet uppstod när jag och Per tog bort vi tog bort tabindex för att lösa ett annat problem. Men man borde kunna lägga till tabindex på <div class datepicker__dropdown>.

**Comment by Jbraaf** [comment]
Löst i senare release
