### ISSUE TITLE
[IE] Pilen för kontextmenyn ligger för långt ner

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#129]
### Beskrivning
Pilen för kontextmenyn ligger för långt ner i IE

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: v0.3.3-rc67
* Angular version: **version**
* Browsers: Endast IE

### Steg för att påvisa problemet
Se utv-appen

### Förväntat beteende
Pilen skall vara linjerad med texten

### Faktiskt beteende
Pilen ligger under texten¨

### Övrig information, kodexempel och motivering till förändring
I bilden så visas följande browsers
1. IE
2. Edge
3. Chrome

### Skärmdumpar mm
![image](https://user-images.githubusercontent.com/28337838/34248799-98c888be-e637-11e7-975c-2bee90c100fe.png)

**Comment by Jbraaf** [comment]
Löst i senare version /J
