### ISSUE TITLE
Går inte bygga Angular-projekt med AOT

### ISSUE THREAD

**Issue by sheriffjohn** [Vastra-Gotalandsregionen/komponentkartan#139]
### Beskrivning
Kompileringsfel när man försöker bygga ett Angular-projekt som använder sig av komponentkartan i AOT-läge.

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.0.1-rc5**
* Angular version: **5.0.0**
* Browsers: **N/A**

### Steg för att påvisa problemet
Kör kommandot "ng build -prod"

### Förväntat beteende
Kompilerar utan fel

### Faktiskt beteende
ERROR in : Unexpected value 'undefined' exported by the module 'KomponentkartanModule in C:/Repos/vgr/APP/node_modules/vgr-komponentkartan/vgr-komponentkartan.d.ts'

### Övrig information, kodexempel och motivering till förändring
Kunna kompilera Angular-projekt med AOT

**Comment by Jbraaf** [comment]
Löst i senare version
