### ISSUE TITLE
Uppdatera readme för minimal uppsättning med angular-cli

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#14]
Readme behöver kompletteras med:

- Vilken Module som behöver importeras.
- Att scss filen behöver importeras i angular-cli.json
- Att sökväg till jquery behöver sättas i angular-cli.json

**Comment by perakerberg** [comment]
Jättebra förslag. Gör en PR utifrån era erfarenheter med uppsättning.

**Comment by perakerberg** [comment]
Stängd med #21.
