### ISSUE TITLE
Inte tvinga konsumenter att importera Routing (Menu komponenten)

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#15]
Man är i nulägget tvingad att använda angular-router, samt att importera RouterModule för att Menu komponenten ska fungera. Efterfrågar en bättre hantering av Menu komponenten med avseende på routing så menu komponenten fortfarande fungerar även om man inte använder angular-router.

**Comment by sheriffjohn** [comment]
Hej, är det inte så att menukomponenten har ett maffigt konfigurationsobjekt där man anger en url-path för varje menuobjekt. Sedan att den ska kunna navigeras någonstans är ju applikationens ansvar att man har skapat en route till den sidan. Du skulle ju lika gärna kunna ange vilken URL du vill. Så jag är inte helt med på att menukomponenten måste ha RouterModule
Men det är ju käckt att applikationen använder sig av den för att skapa routes till sina sidor. 

Skickat från min iPhone

**Comment by perakerberg** [comment]
Idag behövs RouterModule eftersom vi använder routerLink-direktivet på våra menylänkar, vi har inte sett behov av applikationer utan routing. Kom gärna med förbättringsförslag.

**Comment by staxgard** [comment]
Beslut att detta inte kommer att åtgärdas.

**Comment by staxgard** [comment]
Beslut att detta inte kommer att åtgärdas.
