### ISSUE TITLE
vgr-card för bred vid indentering

### ISSUE THREAD

**Issue by Faldo** [Vastra-Gotalandsregionen/komponentkartan#151]
![cardtowide](https://user-images.githubusercontent.com/232093/35094023-5bcf7382-fc44-11e7-979e-aabd3b2080ec.PNG)
### Beskrivning
När vi lägger på indentering, marginleft så förskjuts hela vgr-card utan att ta hänsyn till storleken på container som den innesluts av

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.0.1-rc7
* Angular version: 5.0.0
* Browsers: **Chrome och Firefox**

### Steg för att påvisa problemet
http://koptvardwebtest.vgregion.se/claims det är den här sidan fast vi har inte lagt på indenteringen på card nivån men inspektera element på expandable-div som håller vgr-card och lägg på en margin-left på 20px

### Förväntat beteende
att den håller sig inom omgivande container

### Faktiskt beteende
sticker ut till höger "över kanten"

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by Jbraaf** [comment]
Löst i senare version, öppnas igen om problem återuppstår /J
