### ISSUE TITLE
vgr-card-column ritas utanför sitt parent element

### ISSUE THREAD

**Issue by nihreborn** [Vastra-Gotalandsregionen/komponentkartan#153]
### Beskrivning
vgr-card med två kolumner är placerad innanför en vgr-expandable-div som i sin tur är indragen ett antal pixlar (margin-left). Den andra vgr-card-column växer och ritas då utanför dess vgr-expandable-div-content. Se bifogad bild.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.0.1-rc14
* Angular version: 5.0.0
* Browsers: Chrome

### Steg för att påvisa problemet
Se beskrivning. 

### Förväntat beteende
Att vgr-card-column håller sig innanför sitt parent element

### Faktiskt beteende
vgr-card-column ritas utanför sitt parent element

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
![vgr-card](https://user-images.githubusercontent.com/35603939/35156404-059f5372-fd31-11e7-8caa-85805ccc098a.png)

**Comment by Jbraaf** [comment]
Löst i senare version, öppnas igen om problem återuppstår /J

**Comment by Jbraaf** [comment]
Löst i senare version, öppnas igen om problem återuppstår /J
