### ISSUE TITLE
Komponent Lista (checkbox och papperskorg )- visar kod i info meddelande

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#154]
### Beskrivning
*När man tar bort en rad så innehåller info meddelandet en massa kryptiska tecken istället för objektets namn.*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **: 2.0.1-rc14**
* Angular version: ** 5.1.2**
* Browsers: **Chrome, IE11**

### Steg för att påvisa problemet
*1.Tryck på Komponent Lista (checkbox och papperskorg)
2. Tryck på "Ladda data"
3.Tryck på papperskorgs ikonen och välj Ja
*

### Förväntat beteende
*Info meddelandet innehåller information om objektets namn*

### Faktiskt beteende
*Info meddelandet innehåller kod istället för objektets namn*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller ö
![infokod](https://user-images.githubusercontent.com/33692196/35157214-9265ebd4-fd33-11e7-8da3-2fbf161a82f9.JPG)
vrig information*

**Comment by FeliciaRingblom** [comment]
Detta är ett medvetet val för att visa en funktion som implementatören kan använda. Men vi skulle så klart kunna ändra det till något mer användarvänligt. Beror på vad man ser att syftet är.

**Comment by Jbraaf** [comment]
Inte en bugg, upp till implementatör enligt design. Good catch!

**Comment by maddefinlof** [comment]
Ok men då stänger vi den här då!
