### ISSUE TITLE
Hungerian notations interfaces

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#16]
Undvik hungerian notations, interfacen har fått ett "I". Se typescript naming convention: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

**Comment by perakerberg** [comment]
Bra idé, absolut. Borde bara handla om en refactor-rename.

**Comment by staxgard** [comment]
Beslut att detta inte kommer att åtgärdas.
