### ISSUE TITLE
vgr-list-item Dölj notifiation div om RowNotification är null

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#162]
### Beskrivning
*Skulle det gå att ta bort (ngIf) denna div div class="list-item__notification"  Om man sätter RowNotification till null?*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** "2.0.2-rc7"**
* Angular version: **version**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
*Se nedan "Faktiskt beteende".*

### Förväntat beteende
*Linjen och ytan skall försvinna*

### Faktiskt beteende
*Vi sätter RowNotification dynamiskt om det finns kommentar i objektet i listan. Om man ex. tar bort kommentaren sätter vi  RowNotification till null. Då ligger  ytan med diven kvar (fast tom) och linjen som visas vid notification kvar*

### Övrig information, kodexempel och motivering till förändring
*
`<div class="list-item__notification" ***ngIf="notification"**>
  <span class="list-item__notification__icon" [ngClass]="
            {   'bg-image-icon-ok-check' : notification && notification.icon===NotificationIcons.Ok,
                'bg-image-icon-ok-check--green' : notification && notification.icon===NotificationIcons.OkGreen,
                'bg-image-icon-exclamation' : notification && notification.icon===NotificationIcons.Exclamation,
                'bg-image-icon-exclamation--red' : notification && notification.icon===NotificationIcons.ExclamationRed}">
  </span>
  <div class="list-item__notification__message">
    {{notification? notification.message : ''}}
  </div>
</div>`
*

### Skärmdumpar mm
*Borttagen kommentar*
![image](https://user-images.githubusercontent.com/35916501/35502636-e45884d6-04dd-11e8-8098-a6f51078a891.png)

**Comment by FeliciaRingblom** [comment]
Ska vara fixat i 2.12-rc12
