### ISSUE TITLE
Avverka användning av Providers i komponenter

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#17]
Providers bör ligga i modulen inte i komponenterna. Ligger providers i en komponent blir dessa lokala (Dvs en ny per instans av komponenten). I dom flesta fallen är inte detta önskvärt.

**Comment by sheriffjohn** [comment]
Osäker på om det fanns en tanke att man skulle kunna välja att bara importera enskilda komponenter utan att behöva gå via modulen.
Kanske kan vara onödigt att behöva ha tillgång till alla komponenter samtidigt. 

Men lättast är nog att bara importera modulen och låta den instansera alla providers, även ifall man bara använder ett fåtal komponenter. 

Skickat från min iPhone

**Comment by perakerberg** [comment]
Det är bara SidebarMenuComponent som deklarerar en provider, i detta fall för BrowserDetector. Den skulle lika gärna kunna ligga i modulen.

**Comment by perakerberg** [comment]
Stäng med https://github.com/Vastra-Gotalandsregionen/komponentkartan/commit/984b77a6a1f1106305a8ff1fcab2b3ff6dc9f172. 

SidebarMenuComponent hade en onödig provider som istället kunde definieras i modulen.
