### ISSUE TITLE
Datepicker med min- och maxdatum innan innevarande datum går ej att navigera framåt

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#171]
### Beskrivning
*Försöker man navigera framåt efter att man har navigerat tillbaka till 2016-05-15 i demo-appen för komponentkartan så är "navigeringspilen" inaktiverad både framåt och bakåt.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc2 **
* Angular version: **5.1.2 **
* Browsers: **IE11, Edge, Chrome, IE10 (emulerad)**

### Steg för att påvisa problemet
*1. Gå till KomponentkartanDemo
2. Tryck på Datepicker i menyn
3. Tryck på Exempel så att alla exempel syns
4. Tryck på datumväljaren i det tredje exemplet och navigera så långt bak som möjligt
5. Tryck på pilen för att navigera tillbaka framåt.*

### Förväntat beteende
Man kommer till nästa månad

### Faktiskt beteende
Man stannar kvar på samma månad och det går inte att navigera nånstans

### Skärmdumpar mm
![navigera frama](https://user-images.githubusercontent.com/36041543/35684576-9f4b1a66-0767-11e8-8cac-787bb9423720.png)

**Comment by sheriffjohn** [comment]
fixat buggen
