### ISSUE TITLE
Datepicker/Monthpicker månad på engelska

### ISSUE THREAD

**Issue by Jbraaf** [Vastra-Gotalandsregionen/komponentkartan#172]
### Beskrivning
I datepickern står månadsnamnet på engelska. Månad är på engelska när man valt en månad i månadskalendern.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc2**
* Angular version: **5.1.2**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
http://vgwb0399.vgregion.se:4500/datepicker klicka på kalendern och se månaden
Gäller även motnhpicker, syns efter att man valt månad

### Förväntat beteende
Datepicker ska vara helt på svenska

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
<img width="277" alt="skarmavbild 2018-02-01 kl 16 09 52" src="https://user-images.githubusercontent.com/33897418/35685570-611ee92c-076a-11e8-96f2-0368621b1ea1.png">

*Infoga skärmdumpar eller övrig information*

**Comment by sheriffjohn** [comment]
lagt till locale provider i komponentkartan.module
