### ISSUE TITLE
Reactive forms - När man väljer en radiobutton så markeras även radiobutton i de övriga formulären

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#175]
### Beskrivning
*När man markerar en radiobutton i reactive forms så markeras även radiobutton i de andra formulären*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc3**
* Angular version: **Angular version: 5.1.2 **
* Browsers: **Chrome, IE 11**

### Steg för att påvisa problemet
*1. Öppna komponent Kodexempel och Reactive forms
2. Markera första radiobutton.*

### Förväntat beteende
*Radiobutton är markerad*

### Faktiskt beteende
*Radiobutton är markerad men även första radiobutton i de övriga formulären är markerade.*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig infor
![reactivformsradiobutton](https://user-images.githubusercontent.com/33692196/35795070-e08bd674-0a4f-11e8-95d5-2cad618cfd44.JPG)
mation*

**Comment by sheriffjohn** [comment]
Ändrat i implementationen så att den inte binder mot samma option
