### ISSUE TITLE
Radiogroup i reactive forms med update-mode = blur uppdaterar inte värdet

### ISSUE THREAD

**Issue by FeliciaRingblom** [Vastra-Gotalandsregionen/komponentkartan#178]
### Beskrivning
När radiogroup används i ett reactive forms med updateOn: 'blur' uppdateras inte komponentens värde korrekt (vid blur).

### Typ av ärende (kryssa i en med "x")
- [X ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc3**
* Angular version: **5.1.2**

### Förväntat beteende
Värdet uppdaterar sig på blur.

### Faktiskt beteende
*Beskriv vad som händer*
När man ändrar valt option i radiogroupen och går från komponenten, så uppdateras inte värdet.

**Comment by FeliciaRingblom** [comment]
Fixat i version 2.1.2-rc32

**Comment by Jbraaf** [comment]
Löst i version 2.1.2-rc50
