### ISSUE TITLE
Dubbel inläsning av jquery

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#18]
Såg att ni använder jqeury på ett sätt som leder till att multipla inläningar av pluginet

Rekommenderad användning av tredjeparts bibliotek
https://github.com/angular/angular-cli/wiki/stories-third-party-lib

Förklaring till hur man inte ska importera jquery
https://github.com/angular/angular-cli/wiki/stories-global-scripts

**Comment by sheriffjohn** [comment]
Hej, vad menar du med dubbel inläsning av jquery? Så som det är nu så behöver man bara ha ett jquery i sitt node-modules och lägga till den i sitt cli-json under script-sektionen. Sedan finns det import av jquery i komponentkartan så det ska man inte behöva tänka på. Man behöver alltså inte göra en import av jquery i appen som konsumerar komponentkartan. 

Dock så arbetar vi på att slimma ner komponentkartan så att man inte får med så mycket grejer när man installerar paketet. 

Skickat från min iPhone
