### ISSUE TITLE
Title-value med IE10's document mode dras ut längst åt höger

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#184]
### Beskrivning
*Title-value komponenten dras ut till höger väldigt långt bort i webläsaren om man har emulerat document mode i IE11 till IE10*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc12**
* Angular version: **5.1.2**
* Browsers: **IE10 (Emulerad)**

### Steg för att påvisa problemet

1. Öppna developer tools i IE11
2. Gå till Emulation
3. Ändra Document mode till '10'
4. Gå till **Komponenter/Title-value**

### Förväntat beteende
*Belopp och belopp readonly får plats i kortet*

### Faktiskt beteende
*Båda raderna åkte utanför kortet långt till höger*

### Skärmdumpar mm
*![rader at hoger ie10](https://user-images.githubusercontent.com/36041543/35966244-88e701c6-0cbd-11e8-87e2-cf9507947fed.png)*

**Comment by Jbraaf** [comment]
IE 10 stöds inte
