### ISSUE TITLE
Komponenter med samma source refererar varandra

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#185]
### Beskrivning
Om man har två dropdowns (till ex.) som använder samma source så sker samma typ av markeringar i båda dropdownsen. Dvs. väljer du ett item i ena så väljs det i andra. Får oönskade effekter

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.1.2-rc12**
* Angular version: **5xx**
* Browsers: **IE/Edge/Chrome**

### Steg för att påvisa problemet
1. Gå till Exempelsidor/Lista med kort
2. Expandera två rader med olika ägare
3. Expandera en tredje rad och lås upp den raden
4. Visa valen i ägarkomboboxen så ser man att de olika ägarna är markerade

### Förväntat beteende
Ett val skall vara valt (det som är valt i komboboxen endast)

### Faktiskt beteende
Alla nuddade val är valda

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
![image](https://user-images.githubusercontent.com/28337838/35971725-66dfd49c-0ccf-11e8-820b-870ebfab7ec3.png)

**Comment by Jbraaf** [comment]
Löst i senare version
