### ISSUE TITLE
Möjlighet till längre namn i titel för komponent SidebarMenuComponent

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#19]
Korrekt hantera lång "titel". I nuläget blir texten avklippt.

**Comment by perakerberg** [comment]
Det är flera system som kommer få detta problem, så fontstorleken kommer att ändras. Antingen generellt eller vid behov.

**Comment by perakerberg** [comment]
Efter diskussion med interaktionsdesignern har vi identifierat behov av att ändra fontstorlek på rubriken efter behov. Detta kommer i en framtida release.
