### ISSUE TITLE
DropDown - Tab

### ISSUE THREAD

**Issue by nihreborn** [Vastra-Gotalandsregionen/komponentkartan#196]
### Beskrivning
Syns ej att vi tabbar till komponent (vgr-dropdown). Kan inte använda komponent med tangentbord.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.1.2-rc25
* Angular version: 5.0.0
* Browsers: Chrome

### Steg för att påvisa problemet
*Beskriv hur man kan återskapa problemet.*

### Förväntat beteende
*Beskriv vad du förväntar dig skall hända*

### Faktiskt beteende
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by Jbraaf** [comment]
Ej bugg, kommer lösas i WCAGstory Combox
