### ISSUE TITLE
DropDown - Kan inte ta bort val

### ISSUE THREAD

**Issue by nihreborn** [Vastra-Gotalandsregionen/komponentkartan#197]
### Beskrivning
Initialt har vi en vgr-dropdown som används vid sökning och är tom. Vi väljer ett värde i dropdown:en och resultatet filtreras. När vi "nollar" filtreringen vill vi att dropdownen ska nollställas. Vi försöker på olika sätt, loopar alla items och sätter selected till false eller sätter dropdownen till en tom array. Oavsett hur vi gör visas alltid det senast valda item:et.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.1.2-rc25
* Angular version: 5.0.0
* Browsers: Chrome

### Steg för att påvisa problemet
*Beskriv hur man kan återskapa problemet.*

### Förväntat beteende
Att vgr-dropdown visar en tom text.

### Faktiskt beteende
Visar alltid senast vald item.

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by FeliciaRingblom** [comment]
Löst i 2.1.2-rc30
