### ISSUE TITLE
Dropdown multiselect, får ut fel värden

### ISSUE THREAD

**Issue by Faldo** [Vastra-Gotalandsregionen/komponentkartan#201]
### Beskrivning
Välj alla, avmarkera en, klicka submit så får man ut en array av de texter som ligger i dd boxen istället för de dropdown item som man populerat den med.

Det är bara i det läget man går ifrån att alla är valda och man avmarkerar i listan

### Typ av ärende (kryssa i en med "x")
- [X ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.1.2-rc25
* Angular version: 5.2.4
* Browsers: Chrome, Firefox

### Steg för att påvisa problemet
Välj alla, avmarkera en, klicka submit så får man ut en array av de texter som ligger i dd boxen istället för de dropdown item som man populerat den med.

Det är bara i det läget man går ifrån att alla är valda och man avmarkerar i listan
### Förväntat beteende
Som i alla andra fall att jag får ut en array med dropdown items

### Faktiskt beteende
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by FeliciaRingblom** [comment]
Idag på onChange emittar vi valda items displayName istället för valda items.

**Comment by CrestTheFury** [comment]
Löst i release v2.2.0-rc2
