### ISSUE TITLE
Meny radbryter i Safari

### ISSUE THREAD

**Issue by Jbraaf** [Vastra-Gotalandsregionen/komponentkartan#221]
### Beskrivning
Menyval radbryter vid hover med en bokstav där det bara är ett ord, och med hela ordet där menyvalet är två ord.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.2.0-rc2**
* Angular version: **5.2.7**
* CLI version: **1.7.2**
* Browsers: **Safari**

### Steg för att påvisa problemet
Gå in på komponentkartan i safari och hovra över menyval.

### Förväntat beteende
Menyvalen ska inte radbrytas

### Faktiskt beteende
Menyvalen radbryter alltid

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm

![safari](https://user-images.githubusercontent.com/33897418/37449258-e76da286-2829-11e8-85a7-593bb8afbaf8.png)

**Comment by FeliciaRingblom** [comment]
Branch som löser detta problem finns: meny_radbryter_safari.
Dock så finns liknande problem även i dropdown-multi.

**Comment by FeliciaRingblom** [comment]
Löst. Skapat ny bugg för problemet i dropdown-multi
