### ISSUE TITLE
Tydligare gruppering av checkbox och label

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#229]
### Beskrivning
Det avstånd som kommer automatiskt mellan en checkbox och dess label är så stort att det blir en otydlig gruppering mellan olika alternativ när de ligger på rad. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 2.3.0-rc11 tror jag
* Angular version: vet ej
* Browsers: Chrome

### Steg för att påvisa problemet
Lägg in checkboxar med labels?

### Förväntat beteende
En tydlig gruppering mellan checkbox och label

### Faktiskt beteende
Ett stort avstånd mellan checkbox och label som skapar en otydlig gruppering

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
![image](https://user-images.githubusercontent.com/35460884/38032790-bc224a58-329e-11e8-8209-17e90aafd420.png)

**Comment by louisebroo** [comment]
Det samma gäller för radioknappar

**Comment by staxgard** [comment]
Är denna fortfarande aktuell?

**Comment by louisebroo** [comment]
Ja den ligger i backlog, men har medium eller låg prioritet.
