### ISSUE TITLE
Datepicker i ActionPanel ger fel höjd vid öppning och stängning

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#231]
### Beskrivning
Om en ActionPanel innehåller en Datepicker verkar höjden för kalendern spänna ut höjden för AcionPanel i öppnings- och stägningsanimationerna för denna.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.2.0-rc11*
* Angular version: **5.2.7**
* Browsers: *Chrome**

### Skärmdumpar mm
Öppnas
<img width="890" alt="opening" src="https://user-images.githubusercontent.com/2772564/38299465-7224f692-37fa-11e8-9a47-45d6301c59c9.png">
Öppen
<img width="888" alt="open" src="https://user-images.githubusercontent.com/2772564/38299464-72074372-37fa-11e8-855a-32e8b042c10c.png">

**Comment by FeliciaRingblom** [comment]
Löst i 2.4.0-beta19
