### ISSUE TITLE
Dropdown tar mer utrymme när långa alternativ är valda

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#232]
### Beskrivning
Bredden av en Dropdown verkar vara lika med eller bero på bredden på dess valda alternativ.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.2.0-rc11**
* Angular version: **5.2.7**
* Browsers: **Chrome**

### Skärmdumpar mm
Innan val
<img width="890" alt="unselected" src="https://user-images.githubusercontent.com/2772564/38300181-6f20d32e-37fc-11e8-95ec-8e96b03212f2.png">
Efter val
<img width="888" alt="selected" src="https://user-images.githubusercontent.com/2772564/38300180-6f0506f8-37fc-11e8-9b54-c92c6bf1f7d7.png">

**Comment by CrestTheFury** [comment]
Är fixad i version v2.4.0-beta9, om ni vill testa ifall den är löst för er
