### ISSUE TITLE
Kursiv brödtext

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#233]
### Beskrivning
Jag vill ha möjlighet att välja kursiv text 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: -
* Angular version: -
* Browsers: -

### Steg för att påvisa problemet
-

### Förväntat beteende
-

### Faktiskt beteende
-

### Övrig information, kodexempel och motivering till förändring
I vissa fall är det lämpligt med kursiv text, t.ex. för att förmedla att ett item i en lista är ett utkast.

**Comment by Jbraaf** [comment]
Det är upp till implementatören om texten ska vara kursiv, sorry för felinformation Louise / Johanna
