### ISSUE TITLE
Value changed event på Input

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#234]
### Beskrivning
Input bör ha ett ValueChanged event.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.2.0-rc11**
* Angular version: **5.2.7**
* Browsers: **Chrome**

### Övrig information, kodexempel och motivering till förändring
I likhet med andra inmatningskomponenter bör Input kommunicera när dess värde förändras så att en implementatör kan agera på det.

**Comment by staxgard** [comment]
@kinbode åtgärdas denna i samband med refakten ni håller på med?

**Comment by kinbode** [comment]
@staxgard Nej, vi har inte gjort några förändringar på Input.
