### ISSUE TITLE
Uppdatera rubrik på Dropdown vid programmatisk select/deselect

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#240]
### Beskrivning
Då val i Dropdown väljs eller väljs bort programmatiskt uppdateras inte rubriken. Eftesom det inte är helt klart huruvida detta ska stödas så markeras jag det här som ett förbättrningsförslag.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.2.0-rc11**
* Angular version: **5.2.7**
* Browsers: **Chrome**

### Steg för att påvisa problemet
Ändra värde på selected på en DropDownItem som en DropDownMultiselect binder mot.

### Förväntat beteende
Rubriken uppdatreras.

### Faktiskt beteende
Rubriken uppdateras inte.

**Comment by sheriffjohn** [comment]
fixat i 2.4.0-beta20
