### ISSUE TITLE
Skapa riktig Library bundle

### ISSUE THREAD

**Issue by sheriffjohn** [Vastra-Gotalandsregionen/komponentkartan#25]
### Beskrivning
Skapa en bundle för komponentkartan-biblioteket som publiceras till NPM

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X ] Förbättringsförslag

### Förväntat beteende
Mindre slimmat bundle +typings och CSS

### Faktiskt beteende
Just nu så publiceras all källkod till NPM

### Övrig information, kodexempel och motivering till förändring
Få ner storleken på komponentkartan och göra den mer library-aktig

### Skärmdumpar mm
Se https://www.npmjs.com/package/ng-packagr för skapa en library-bundle

**Comment by Jbraaf** [comment]
Löst
