### ISSUE TITLE
ListItem får fel höjd vid öppning

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#257]
### Beskrivning
ListItem får i vissa fall fel höjd vid öppning. Orsaken till detta är oklar, men kan mycket väl bero på tveksam implementation i KSV, så avvakta med action tills vi utrett det.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.2.0-beta20**
* Angular version: **5.2.7**
* Browsers: **Chrome**

### Steg för att påvisa problemet
Oklart, men har sannolikt med ngIf i content att göra.

### Förväntat beteende
ListItem får rätt höjd i öppningsanimationen.

### Faktiskt beteende
ListItem får för hög höjd i öppnigsanimationen.

**Comment by louisebroo** [comment]
Kvarstår problemet?

**Comment by staxgard** [comment]
@louisebroo @kinbode kvarstår problemet?

**Comment by louisebroo** [comment]
@staxgard problemet är kvar hos oss, men jag har inte fått klarhet i om det kräver en åtgärd i komponentkartan. Är det hos oss problemet ligger @kinbode ?

**Comment by kinbode** [comment]
@louisebroo @staxgard Felet verkar ligga i komponentkartan.

**Comment by AronssonFredrik** [comment]
@alphaPlusPlus, 
Försöker ni lösa detta i `fix-expandable-div-grid`?

**Comment by alphaPlusPlus** [comment]
Nej, detta för #169861726 (som ligger i pivotal)
Detta buggen vi kommer inte att fixa för att det är redan löst i nya gridan

**Comment by AronssonFredrik** [comment]
Stänger då det är löst i `vgr-grid` och en lösning i `vgr-list` är inte längre ett behov.
