### ISSUE TITLE
Dropdown-items radbryter på hover i Safari

### ISSUE THREAD

**Issue by FeliciaRingblom** [Vastra-Gotalandsregionen/komponentkartan#261]
### Beskrivning
När man hovrar över items i dropdown-multi så radbryter texten på ett felaktigt sätt.

### Typ av ärende 
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.5.0-beta3**
* Angular version: **5.2.7**
* Browsers: **Safari**

### Steg för att påvisa problemet
Expandera en dropdown multi i Safari. Hovra över items. 

### Förväntat beteende
Radbryt ska inte förändras vid hover. 

### Faktiskt beteende
Radbrytning förändras vid hover. Det blir "hoppigt".

### Övrig information, kodexempel och motivering till förändring
Liknande problem har lösts för menyn (också endast problem i Safari) i #221 

### Skärmdumpar mm
<img width="354" alt="skarmavbild 2018-04-27 kl 09 45 10" src="https://user-images.githubusercontent.com/6872618/39351246-306f96a8-4a01-11e8-925c-f8c468523e97.png">

**Comment by staxgard** [comment]
@louisebroo åtgärdas detta i omskrivningen av dropdown? Om inte så föreslår jag att vi sätter den till wontfix då vi inte kommer att stödja safari i komponentkartan.

**Comment by louisebroo** [comment]
@staxgard Jag vet inte, men det kan vi tittat på. Annars håller jag med om att vi kan sätta den som wontfix.

**Comment by louisebroo** [comment]
@staxgard vi stänger denna. Som du skrev är det inte en browser vi stöder.
