### ISSUE TITLE
Kodexempel-> (Lista med radnotifieringar) - Tryck på enter visar spara meddelande igen

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#266]
### Beskrivning
*När man har uppdaterat en användare och trycker på enter så visas spara meddelande igen*

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.6.0-beta8**
* Angular version: **5.2.7**
* Browsers: **Chrome , IE 11**

### Steg för att påvisa problemet
*Steg1: Öppna Kodexempel -> Lista (Lista med radnotifieringar) Öppna en användare Steg 2:Tryck på "Uppdatera" ,(Ett spara meddelande visas), Steg 3: Tryck på enter. *

### Förväntat beteende
**

### Faktiskt beteende
*Visar spara meddelande igen*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by kebarvid** [comment]
Denna bug skall vara löst nu, dubbelkolla att den kör en komponentkartan-version > 4.0.0-beta5 och verifiera att den är löst.

**Comment by maddefinlof** [comment]
Den är ok i både Chrome, edge och IE 11.
