### ISSUE TITLE
Grafik blir pixlig

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#273]
### Beskrivning
När man zoomar på sidan blir lock button, back to top och VGR-loggan pixliga. 

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.6.0-beta12**
* Angular version: **5.2.7**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
*Zooma sida med en av komponenterna.*

### Förväntat beteende
*Grafiken ska fortsätta att vara skarp vid zoom*

**Comment by kebarvid** [comment]
Har ändrat till SVG-ikoner för dessa nu
