### ISSUE TITLE
Gå direkt från menyn till content med tab

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#274]
### Beskrivning
Som det fungerar nu måste jag tabba igenom alla meny-alternativ för att kunna ta mig vidare till innehållet på sidan, det är väldigt omständigt. Det borde gå att gå mellan alternativen med piltangenter istället. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.6.0-beta12**
* Angular version: **5.2.7**

### Förväntat beteende
Tab gör översta menyalternativet fokuserat och sedan kan man navigera mellan alternativen med piltangenterna.

**Comment by staxgard** [comment]
@louisebroo @Jbraaf är detta någonting vi ska åtgärda då vi idag följer WCAG-reglerna och de säger att det är såhär det ska fungera?

**Comment by louisebroo** [comment]
Vi behöver stödja något sätt att hoppa över innehållet i menyn om man vill gå direkt till content på sidan. Det skulle också funka med ett osynligt menyalternativ.

**Comment by louisebroo** [comment]
Jag uppfattar det som att den här är redundant nu när vi refineat den här storyn; https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/516 Så jag stänger denna.
