### ISSUE TITLE
Permanent notifiering försvinner

### ISSUE THREAD

**Issue by Jbraaf** [Vastra-Gotalandsregionen/komponentkartan#278]
### Beskrivning
- Gå in på http://vgwb0399.vgregion.se:4500/examples-listwithcards
- Öppna listrad som har en permanent notifiering på sig
- Lås upp och avbryt editeringen
- Filtrera bort alla rader
- Ta fram rader igen
- Tillfällig notifiering visas och sedan försvinner det permanenta meddelandet

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **2.6.0-beta15**
* Angular version: ** 5.2.7 **
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
Se ovan 

### Förväntat beteende
Det permanenta meddelandet ska ligga kvar på listraden.

### Faktiskt beteende
Den tillfälliga notifieringen spelas igen och sedan blir listraden utan meddelande.

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by kebarvid** [comment]
Denna bug skall vara löst nu, dubbelkolla att den kör en komponentkartan-version > 4.0.0-beta5 och verifiera att den är löst.
