### ISSUE TITLE
Karma-tester failar slumpmässigt

### ISSUE THREAD

**Issue by sheriffjohn** [Vastra-Gotalandsregionen/komponentkartan#281]
### Beskrivning
När man kör ng test så får man fialande tester. Första gången man kör så går det bra men när man kör om test runner så uppstår failande tester.

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.0.0**
* Angular version: **^6.0.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
kör ng test ett par gånger

### Förväntat beteende
Allt ska bara funka!

### Faktiskt beteende
Slumpmässigt antal failande test

### Övrig information, kodexempel och motivering till förändring
Han här har samma problem:
https://github.com/angular/angular-cli/issues/9906

**Comment by Ichimaru8259** [comment]
Hej,
Om det här refererar till random failande tester i VGPV Klient så var det async problem: testrunnern hade redan påbörjat nästa test (och därmed byggt upp en ny DOM) innan den kört asserten från föregående test. Anledningen att det ibland lyckas (mycket beroende på testrunner) hade att göra med hur snabb eller långsam testrunnern var. Långsam testrunner = fler lyckades test pga att assert kördes för rätt DOM

**Comment by staxgard** [comment]
Detta är inget problem längre.
