### ISSUE TITLE
Blå primär och dimmad har bytt färgkod på exempelsidan

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#294]
### Beskrivning
Färdkoden för blå primärfärg och blå dimmad färg har bytt plats så att den primära beskriver dimmad och vice verse

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Förväntat beteende
Färgkoderna stämmer överens med färgen som visas. Det gäller endast hex-koderna

**Comment by synne1** [comment]
Fixat
