### ISSUE TITLE
Korten i modal dialog går ibland inte att öppna

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#296]
### Beskrivning
*Om man är inne på 'Modal dialog' inne på komponentkartan, går till en annan komponent och sedan går in på 'Modal dialog' igen så går det inte att öppna korten för Exempel, API eller tillgänglighet.*

### Typ av ärende (kryssa i en med "x")
- [X] Bugg

### Din miljö
* Version av vgr-komponentkartan: **3.0.0-beta23**
* Angular version: **Angular: 6.0.3, Angular-Cli: 6.0.7**
* Browsers: **IE11**

### Steg för att påvisa problemet
*1. Gå in på Komponentkartan demo.
2. Tryck på komponenter och sen tryck på Modal dialog
3. Kolla att du kan öppna korten
4. Gå till Monthpicker komponenten
5. Gå tillbaka till Moda dialog
6. Hovera över korten och tryck på dom*

### Förväntat beteende
*Korten öppnas*

### Faktiskt beteende
*Det går inte att öppna korten*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*![panel efter byte i menyn](https://user-images.githubusercontent.com/36041543/42078512-180b1ba2-7b7d-11e8-9f0d-317017f7f489.gif)*

**Comment by CrestTheFury** [comment]
Löst i 3.1.0-beta5

**Comment by CrestTheFury** [comment]
Löst i 3.1.0-beta5
