### ISSUE TITLE
Textarea blir jätteliten när man växlar ifrån readonly

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#297]
### Beskrivning
*Om man växlar ifrån readonly på en textarea komponent så blir arean väldigt liten.*

### Typ av ärende (kryssa i en med "x")
- [X] Bugg

### Din miljö
* Version av vgr-komponentkartan: **3.0.0-beta23**
* Angular version: **Angular: 6.0.3, Angular Cli: 6.0.7**
* Browsers: **IE11, Chrome, Edge**

### Steg för att påvisa problemet
*1. Gå till komponentkartan demo
2. Gå till Textarea komponenten
3. Notera vart readonly fältet är
4. Tryck på Nyckellåset*

### Förväntat beteende
*Området där readonly texten är blir ett område där all text kan redigeras och synas samtidigt. Det ska vara tillräckligt stort för att man ska kunna se vad som står.*

### Faktiskt beteende
*Området som skapas är alldeles för litet för att få någon översikt om vad som står.*

### Skärmdumpar mm
*![readonly textarea](https://user-images.githubusercontent.com/36041543/42088479-e0c48490-7b99-11e8-8881-f9298878ab5f.gif)*

**Comment by louisebroo** [comment]
Det var fel höjd satt på demosida, inget fel i komponenten. Synnöve har fixat demosidan.
