### ISSUE TITLE
Första kortet blir indenterat även fast det konfigurerats att vara normalt

### ISSUE THREAD

**Issue by Ichimaru8259** [Vastra-Gotalandsregionen/komponentkartan#300]
### Beskrivning
Första kortet blir indenterat även fast det konfigurerats att vara normalt
```<vgr-list-item-content [indentContent]="false">```

**Edited to add:**
Det är ett följd problem. Rot-felet uppstår av en felaktig bindning: om man binder 
``` <vgr-list [notification]="listNotification"> ``` 
där __listNotification__ är till exempel en sträng så går listan sönder. Buggen är alltså att databindingen inte är stabil nog.

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.0.0-beta20**
* Angular version: **6.0.4**
* Browsers: Chrome, IE, Edge etc

### Steg för att påvisa problemet
```
 <vgr-list [flexibleHeader]="true" [notification]="errorMessage" [allowMultipleExpandedItems]="true">
        <vgr-list-header>
          <vgr-list-column-header text="Text1" width="6" sortKey="title"></vgr-list-column-header>
          <vgr-list-column-header text="Text2" width="3" [align]="'right'" sortKey="sum"></vgr-list-column-header>          
        </vgr-list-header>
        <vgr-list-item *ngFor="let item of items | unitfilter:filter" [notification]="item?.rowNotification">
          <vgr-list-item-header (click)="onClick(item.id)">
            <vgr-list-column [text]="item?.title" width="6"></vgr-list-column>
            <vgr-list-column [text]="item?.sum | vgpvCurrency" width="3" [align]="'right'"></vgr-list-column>
          </vgr-list-item-header>
          <vgr-list-item-content [indentContent]="false">
            <div style="height: 50px;" align="right"  *ngIf="item?.option1 && item?.option2 === false">
              <vgr-button [secondary]="true" (click)="openPrompt(item)">Do the thing</vgr-button>
            </div>
            <vgr-table *ngFor="let row of item.rows">
              <vgr-table-header>
                <vgr-table-header-column [width]="8">
                  {{row?.title}}
                </vgr-table-header-column>
                <vgr-table-header-column [width]="3" [align]="'right'">
                  {{row?.sum | vgpvCurrency}}
                </vgr-table-header-column>
              </vgr-table-header>
              <vgr-table-row>

                <vgr-table-row-column [width]="3">
                  nivå 2
                </vgr-table-row-column>
              </vgr-table-row>
            </vgr-table>
          </vgr-list-item-content>
        </vgr-list-item>
      </vgr-list>
```

### Förväntat beteende
~~Första kortet ska inte vara indenterat~~
felaktig databinding mot [notification] i ett <vgr-list> element ska inte orsaka felaktig indentering.
Önskat beteende är att databindingen misslyckas på ett robust sätt (bindingen sker inte men komponenten fortsätter fungera). Det vore även trevligt om komponenten protesterade mot den felaktiva typen. 

### Faktiskt beteende
Första kortet/elementet är indenterat

### Skärmdumpar mm
![oonskad_indentering](https://user-images.githubusercontent.com/26999965/43777891-63a7abfc-9a54-11e8-811d-1e593e454386.png)

**Comment by Ichimaru8259** [comment]
Mer information!

Det beror på ett bindingsfel. Om man binder [notification] ( ```<vgr-list [notification]="listNotification">```) till ett objekt av fel typ (t.ex. en sträng) så går listan sönder.

**Comment by staxgard** [comment]
Implementationsfel.
