### ISSUE TITLE
Rensa alternativ rensar inte val i radiobuttons i komponentkartan-demo

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#302]
### Beskrivning
*Search results har ett exempel som ligger under Översiktkortet som inte filtrerar korrekt. Väljer man något i den listan som kommer upp får man ett skumt resultat nedanför.
Knappen 'Rensa alternativ' under exempel för komponenten Radio Group rensar inte alternativen.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.0.1-beta6**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **IE11, Edge, Chrome**

### Steg för att påvisa problemet
*1. Gå till demo siten för komponentkartan
2. Gå till komponenten 'Radio Group'
3. Öppna upp kortet för Exempel
4. Tryck på 'Val 2' i den gruppen som har en knapp bredvid sig
5. Tryck på knappen - Felsymptom 1
6. Gå till komponenten 'Search results'
7. Skriv in vad som helst i sökfältet under översikt - Felsymptom 2*

### Förväntat beteende
*Felsymptom 1 - Radio knappen töms
Felsymptom 2 - Resultaten filtreras på det man skriver in*

### Faktiskt beteende
*Felsymptom 1 - Inget händer vid klick av knapp
Felsymptom 2 - Inget filtreras*

### Skärmdumpar mm
![image](https://user-images.githubusercontent.com/36041543/44077607-826c3724-9fa4-11e8-928c-fd673f2fecc6.png)
![search results and radio group](https://user-images.githubusercontent.com/36041543/44077944-92cec52c-9fa5-11e8-9ef9-7e4f8ffc08df.gif)

**Comment by kebarvid** [comment]
När det gäller search-result så är det inte ett fel.

Search-result-komponenten filtrerar inte en lista, den visar endast upp vad den får tillskickat sig. Det är upp till implementatörern att styra hur den skall användas. I det första examplet visar vi bara en förskapad lista när man klickar i rutan. På några av de andra exemplen under exempel så filtrerar vi en lista när man skriver något, men det är något vi lagt in själva i implementationen inte något som finns i komponenten.

**Comment by Jbraaf** [comment]
Stänger denna och lägger den i en samlingsstory i pivotal. /J
