### ISSUE TITLE
Filter textbox hindrar kort från att öppnas smidigt

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#303]
### Beskrivning
*När man öppnar ett kort som innehåller en Filter textbox i Edge eller IE11 så öppnas kortet lite hackigt fram tills att hela textboxen öppnats, efter det öppnas kortet smidigt*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.0.1-beta6**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **Edge, IE11**

### Steg för att påvisa problemet
*1. Gå in på demosidan för komponentkartan i Internet explorer 11 eller Microsoft Edge
2. Gå in på komponenten 'Filter textbox'
3. Tryck på Exempel*

### Förväntat beteende
*Kortet öppnar sig smidigt*

### Faktiskt beteende
*Kortet hackar upp tills det att filter textboxen visats helt*

### Skärmdumpar mm
![filter textbox med kort](https://user-images.githubusercontent.com/36041543/44086605-64cf241a-9fbd-11e8-8f22-3a363146160f.gif)

**Comment by staxgard** [comment]
Åtgärdat.
