### ISSUE TITLE
Grafik ser felaktig ut i datepicker

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#304]
### Beskrivning
Cirkeln som är runt navigationspilarna i datepickern ligger inte centrerade runt pilarna. Dessutom ser pilarna mer avlånga ut än de borde (på min laptopskärm i alla fall).

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 3.1.0-beta1
* Angular version:  6.0.3
* Browsers: Chrome

### Steg för att påvisa problemet
Tryck på datepickern, då öppnas kalendern och då syns pilarna. Hover på pilarna visar cirkeln. 

### Förväntat beteende
Att pilarna ser mer kompakta ut samt att cirklarna runt dem är placerade centrerat på pilen. 

### Skärmdumpar mm
<img width="290" alt="skarmavbild 2018-08-14 kl 16 10 47" src="https://user-images.githubusercontent.com/35460884/44097464-1f8a71cc-9fde-11e8-92a0-3e3cc6f79ce1.png">

**Comment by staxgard** [comment]
@louisebroo är det på mac? På min VGR-dator i Chrome ser det bra ut.

**Comment by louisebroo** [comment]
ja precis @staxgard. såg det även på johannas och rebeccas mac:ar.

**Comment by staxgard** [comment]
@louisebroo kan vi stänga denna då det gäller safari?

**Comment by louisebroo** [comment]
den gäller i chrome så den tycker jag inte att vi kan stänga
