### ISSUE TITLE
Datepickers fokus är olika för mus och piltangent

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#307]
### Beskrivning
*Om man trycker på ett inaktiverat datumalternativ och sedan klickar på en piltangent så hamnar fokus inte där man förväntar sig.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.1.0-beta2**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **IE11, Chrome, Edge**

### Steg för att påvisa problemet
*1. Gå till demot för komponentkartan
2. Gå in på Datepicker-komponenten
3. Tryck exempel-kortet och sen tryck på det 3:e exemplet
4. Scrolla till en månad som har alternativ som inte är valbara
5. Tryck på ett inaktiverat alternativ
6. Tryck på uppåtpil*

### Förväntat beteende
*Hamnar på datumet ovanför det man klickade på*

### Faktiskt beteende
*Hamnar på datumet ovanför det man hade fokus på innan man klickade med musen*

### Skärmdumpar mm
*![datepicker fokus](https://user-images.githubusercontent.com/36041543/44270077-b0074400-a236-11e8-84e5-ae8d4b9e7530.gif)*

**Comment by Jbraaf** [comment]
Inträffar inte i skarpa projekt kommer inte att lösas
