### ISSUE TITLE
Filter tag:Avancerat exempel - Fokuserar inte på nästa filter tag när man tar bort en filter tag i IE

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#309]
### Beskrivning
*Filter tag:Avancerat exempel - Fokuserar inte på nästa filter tag när man tar bort en filter tag i IE*

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.1.0-beta2**
* Angular version: **6.0.3 och Angular-Cli: 6.0.7 **
* Browsers: **IE 11**

### Steg för att påvisa problemet
*1. Öppna komponent Filter tag med IE 11.
2. Gå till avancerat filter
3. Fyll i tex Johanna, 15 och kvinnor och män" och tryck på filtrera*
4. Tabba dig fram till första filtret Johanna.
5. Tryck på Space

### Förväntat beteende
*Filter tag "Johanna" försvinner och fokus hamnar på nästa filter tag  "Ålder >15" *

### Faktiskt beteende
*Ingen fokus på "Ålder >15"  *

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by herrklaseen** [comment]
@louisebroo @athid 

Fix för detta finns på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/filter-tag

**Comment by erfham** [comment]
@herrklaseen 

Chrome - OK
Edge - OK
IE 11 -
På demo sidan:
När man tagit bort ett filter tappar man fokus, dvs man får inte fokus på nästa tag automatiskt. 
Om man tabbar till checkbox för kvinnor/män kan man inte tabba vidare. Är detta något som fixas i denna story eller ska ett nytt ärende skapas?
I feature-branch:
När man tagit bort ett filter tappar man fokus, dvs man får inte fokus på nästa tag automatiskt.
Här kan man tabba mellan kvinnor/män utan problem.
