### ISSUE TITLE
Vid minskning av fönstret så döljs expanderade komponenter i pageheadern

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#314]
### Beskrivning
När man har något i en pageheader som kan expanderas utöver pageheadern, så lägger sig den expanderade delen bakom saker som finns i vgr-page-body då man minskar fönstret horisontelt

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 3.1.0-betaX (är osäker på när den exakt började)
* Angular version: 6.0.3
* Browsers: IE, Edge o Chrome (de jag testat)

### Steg för att påvisa problemet
I Komponentkartan-demo kan man lokalt se det om man tittar på sidan Lista med kort. Där finns numera en datepicker i headern. 
1. Klicka på datepickern så den fäller ut sig
2, Minska fönstret och se hur den försvinner bakom listan nedanför

### Förväntat beteende
Datepickern skall ligger överst hela tiden

### Faktiskt beteende
Datepickern i utfällt tillstånd försvinner bakom listan

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
![issue_komponentkartan](https://user-images.githubusercontent.com/28337838/45485588-74d63300-b758-11e8-866f-73d20c4c1e2e.gif)

**Comment by kebarvid** [comment]
Löst i beta9
