### ISSUE TITLE
Scrollbar dyker inte upp när menyn blir lång

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#318]
### Beskrivning
*Öppnar man en expanderbar del av menyn så att man måste scrolla så dyker inte scrollbaren upp på en gång.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.2.0-beta1**
* Angular version: ** Angular: 6.0.3 och Angular-Cli: 6.0.7 **
* Browsers: **IE11, Chrome, Edge**

### Steg för att påvisa problemet
*1. Gå till komponentkartandemo
2. Tryck på 'Komponenter'
3. Rör musen ut i kanten av menyn*

### Förväntat beteende
*Musen hoverar över en scrollbar*

### Faktiskt beteende
*Ingen scrollbar dyker upp*

### Övrig information, kodexempel och motivering till förändring
*Scrollbaren dyker upp så fort man scrollar på annat sätt som med musen*

### Skärmdumpar mm
*![scrollbar dyker inte upp](https://user-images.githubusercontent.com/36041543/46289434-61fd9400-c589-11e8-8781-5d5427ad1f74.gif)*

**Comment by herrklaseen** [comment]
Det här är inte längre ett problem och ärendet kan stängas @athid

**Comment by AronssonFredrik** [comment]
@herrklaseen, jag kan fortfarande reproducera på [demot](https://vastra-gotalandsregionen.github.io/komponentkartan-demo/). Däremot om vi väljer att gå vidare med att ta bort ngx-scrollbar (#435), så skulle vi kunna lösa problemet därigenom.

Fredrik

**Comment by athid** [comment]
ngx-scrollbar ligger i nuvarande projekt så det bör ju lösa det då, men vi låter denna ligga så länge så att vi ser om det löses och inte kvarstår ändå utan att något manuellt event eller jox måste göras då listan plötsligt blir längre...
