### ISSUE TITLE
Dropdown multiselect stängs ner vid klick runt textboxen

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#319]
### Beskrivning
*Klickar man på ett ställe i området runt textboxen i dropdown eller på sökikonen så stängs dropdownen ned*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** Angular: 6.0.3 och Angular-Cli: 6.0.7 **
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **IE11, Chrome, Edge**

### Steg för att påvisa problemet
*1. Gå till komponenten Dropdown multiselect
2. Tryck upp exempelkortet
3. Tryck på den 3:e dropdownen (den med texten: "25 items" ovanför)
4. Tryck på sökikonen*

### Förväntat beteende
*Dropdownen håller sig uppe*

### Faktiskt beteende
*Dropdownen stängs ner*

### Skärmdumpar mm
*![dropdown stangs ner](https://user-images.githubusercontent.com/36041543/46290510-519ae880-c58c-11e8-9e01-3b98d745b349.gif)*

**Comment by louisebroo** [comment]
@Jbraaf anser du detta att det är en bug eller är det förväntat beteende?

**Comment by Jbraaf** [comment]
Bugg sedan ett tag tillbaka, alltså innan förändring i dropdown gjordes.

**Comment by louisebroo** [comment]
Detta är löst i och med att vi har byggt om dropdown.
