### ISSUE TITLE
Dropdown multiselect's hover är missvisande när man trycker under ett item

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#320]
### Beskrivning
*När man ska välja ett item i en dropdown multiselect så kan man inte trycka på undersidan eller översidan av itemet även om hover får det att se ut som om man kommer att välja det itemet.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.2.0-beta1**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **Edge, IE11, Chrome**

### Steg för att påvisa problemet
*1. Gå till komponenten Dropdown multiselect
2. Tryck upp exempelkortet
3. Tryck på den första dropdownen
4. Tryck på undersidan utav ett icke-valt item*

### Förväntat beteende
*Boxen blir checkad*

### Faktiskt beteende
*Boxen blir inte checkad*

### Skärmdumpar mm
*![dropdown multiselect items valjs inte 2](https://user-images.githubusercontent.com/36041543/46291300-5f516d80-c58e-11e8-8af3-070ee7092baf.gif)*

**Comment by Jbraaf** [comment]
Löst i ny version av dropdown
