### ISSUE TITLE
Rader innanför Card-komponenten blir osynliga vid öppning

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#328]
### Beskrivning
*När man öppnar Card-komponenten så kan vissa rader innanför försvinna ibland och kommer inte tillbaka förrän man hoverar över raden.*

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** 4.0.0-beta8**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **IE11**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Card under komponenter
3. Öppna upp Exempel - två kolumner*

### Förväntat beteende
*Alla rader under kortet syns*

### Faktiskt beteende
*De 2 översta raderna försvinner delvis*

### Övrig information, kodexempel och motivering till förändring
*Sker i Edge också men raderna dyker upp utav sig själva.*

### Skärmdumpar mm
*![osynliga items i card-komponenten](https://user-images.githubusercontent.com/36041543/48469718-e3cf1700-e7ef-11e8-8a0a-d7ffdfb8ae3c.gif)*

**Comment by Jbraaf** [comment]
Går inte att återskapa, öppnas igen om problemet uppstår igen./ J
