### ISSUE TITLE
Fokus försvinner från listan vid uppdatering

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#329]
### Beskrivning
*Kodexemplet Lista (med radnotifieringar) har knappar under varje listobjekt som uppdaterar och krymper objektet efteråt. När det sker så hamnar fokus nån annanstans än förväntat.*

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta8**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7 **
* Browsers: **Edge**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Lista (med radnotifieringar) under Kodexempel
3. Klicka på Första raden i exempletsom har förnamnet Adam.
4. Tabba till knappen 'uppdatera' och tryck på space
5. Vänta på att fliken viker ihop sig
6. Tryck på Tab*

### Förväntat beteende
*Fokus skiftar till 'Bjarne'*

### Faktiskt beteende
*Fokus hamnar på Systeminformationsrutan i headern*

### Skärmdumpar mm
*![fokus forsvinner fran listan efter uppdatering](https://user-images.githubusercontent.com/36041543/48475539-585c8280-e7fd-11e8-9476-b359e0f1bf0d.gif)*

**Comment by maddefinlof** [comment]
Buggen är omtestad och den är okej! Testad med version: DEMO vgr-komponentkartan version: 5.0.0-beta6, Angular: 7.1.0 och Angular-Cli: 7.3.9
