### ISSUE TITLE
Länkar på header-meny fungerar inte

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#330]
### Beskrivning
När man lägger en headerMenu på en <vgr-header> så får man upp menyalternativen, men det händer inget när man klickar på dem. Det verkar finnas någon click-listener som stjäl klick-eventet till länken och istället bara stänger menyn.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.1.1**
* Angular version: **6.0.8**
* Browsers: **Edge, Chrome, Firefox**

### Övrig information, kodexempel och motivering till förändring
Så här ser deklarationen av min header ut:
``` 
  <vgr-header userName="{{user?.fornamn}} {{user?.efternamn}}, Avtal: {{user?.currentAvtal}}" 
    [hideSwosh]="true" 
    initials= "{{user?.fornamn.charAt(0).toUpperCase()}}{{user?.efternamn.charAt(0).toUpperCase()}}"
    circleColor="#7FA276" 
    [headerMenu]="{menuItems:[
      {displayName: 'Hjälp', url: '/skicka-fil', isInternalLink: true}, 
      {displayName: 'Om', url: '/om', isInternalLink: true}, 
      {displayName: 'Kontakt', url: '/kontakt', isInternalLink: true}, 
      {displayName: 'Byt avtal', url: '/byt-avtal', isInternalLink: true}, 
      {isSeparator: true}, 
      {displayName: 'Logga ut', url: '/logout', isInternalLink: true}
      ]}">
  </vgr-header>
```

**Comment by louisebroo** [comment]
@perut1 vad blir konsekvensen av detta?

**Comment by perut1** [comment]
@louisebroo Att menyn inte går att använda.

**Comment by louisebroo** [comment]
Jag är ändå osäker om jag riktigt förstår, vi har inte det här problemet någon annanstans. Ni försöker alltså skapa en meny med menyalternativ till olika sidor men det går inte att navigera? Är det menyn till vänster på sidorna som du menar?

**Comment by perut1** [comment]
Nej, inte vgr-menu header-menu, den som ligger i headern.

**Comment by kebarvid** [comment]
Tror att jag fixat buggen i version 4.0.1-beta3, testa gärna att dra in den i ert projekt och se om det funkar bättre @perut1

**Comment by maddefinlof** [comment]
Buggen är testad Okej i demomiljön med 4.3.0-beta5, Angular: 7.1.0 och Angular-Cli: 7.3.9
