### ISSUE TITLE
Events från header-meny

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#331]
### Beskrivning
Det hade varit praktiskt för oss om det fanns en möjlighet att kunna lyssna på events från header-menyn när någon har klickat på ett menyalternativ, istället för att alltid navigera till en annan sida. Vi har t.ex. ett menyval där vi vill öppna en modal-dialog vilket idag inte går.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

**Comment by louisebroo** [comment]
Vad är det för fall ni vill trigga en modal vid klick på ett menyval? Jag skulle säga att det är inte ett rekommenderat beteende att trigga en dialog vid navigering.
