### ISSUE TITLE
Sidan borde inte scrollas när scrollbaren når någon utav extrempunkterna

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#332]
### Beskrivning
*När man med 1 scroll når antingen längst upp eller längst ner i scrollbaren så scrollas även sidan*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta10**
* Angular version: **Angular: 6.0.3 och Angular-Cli: 6.0.7**
* Browsers: **Edge, IE, Chrome**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Komponenter och sedan Dropdown Select
3. Tryck upp exempel och API
4. Tryck på dropdownen med texten "Val av flera alternativ"
5. Scrolla inuti dropdownen*

### Förväntat beteende
*Endast dropdownen scrollas*

### Faktiskt beteende
*Dropdownen och sidan scrollas*

### Övrig information, kodexempel och motivering till förändring
*Irriterande att det scrollas på ett ställe där jag inte har någon avsikt att scrolla*

### Skärmdumpar mm
*![scroll som scrollar efter maxscroll ar natt](https://user-images.githubusercontent.com/36041543/48937671-2ccd4c80-ef0f-11e8-9387-6315dd5740cb.gif)*

**Comment by louisebroo** [comment]
@kinbode uppstår detta beteende nu när vi uppdaterat beteende för scroll och space?

**Comment by herrklaseen** [comment]
@louisebroo @athid 
Fix för detta finns på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select

**Comment by athid** [comment]
Verkar funka fint!

**Comment by erfham** [comment]
@herrklaseen 

Fungerar enligt förväntat beteende i Chrome, dock kvarstår problemet i Edge/IE11.
