### ISSUE TITLE
Default sortering av lista är inverterad

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#338]
### Beskrivning
När man sätter sortDirection på en lista så pekar pilarna åt motsatt håll mot vad man har satt. Sätter man t.ex. Descending så pekar pilen uppåt istället för nedåt.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **3.1.1**
* Angular version: **6.0.8**
* Browsers: **Firefox, Chrome & Edge**

### Steg för att påvisa problemet
```
      <vgr-list>
        <vgr-list-header (sortChanged)="sortChanged($event)">
          <vgr-list-column-header width="4" sortKey="datum" [sortDirection]="sortDirection.Descending">Datum</vgr-list-column-header>
          <vgr-list-column-header width="3" sortKey="registreradAv">Registread av</vgr-list-column-header>
          <vgr-list-column-header width="2" sortKey="besokIFil" [align]="'right'">Besök i fil</vgr-list-column-header>
          <vgr-list-column-header width="5" sortKey="besokSomKraverAtgard" [align]="'right'">Besök som kräver åtgärd</vgr-list-column-header>
          <vgr-list-column-header width="2" sortKey="belopp" [align]="'right'">Belopp</vgr-list-column-header>
          <vgr-list-column-header width="2" sortKey="status">Status</vgr-list-column-header>
          <vgr-list-column-header width="2" [align]="'center'">Ta bort</vgr-list-column-header>
        </vgr-list-header>
        <vgr-list-item *ngFor="let fil of fillista">
          <vgr-list-item-header class="smaller-text">
            <vgr-list-column width="4">{{fil.datum | datumOchTid}}</vgr-list-column>
            <vgr-list-column width="3">{{fil.registreradAv}}</vgr-list-column>
            <vgr-list-column width="2" [align]="'right'"><span *ngIf="fil.besokIFil > 0">{{fil.besokIFil}} st</span></vgr-list-column>
            <vgr-list-column width="5" [align]="'right'"><span *ngIf="fil.besokSomKraverAtgard > 0">{{fil.besokSomKraverAtgard}} st</span></vgr-list-column>
            <vgr-list-column width="2" [align]="'right'">{{fil.belopp | belopp}}</vgr-list-column>
            <vgr-list-column width="2">{{fil.status}}</vgr-list-column>
            <vgr-list-column-trashcan width="2" [align]="'center'"></vgr-list-column-trashcan>
          </vgr-list-item-header>
          <vgr-list-item-content>detaljer</vgr-list-item-content>
        </vgr-list-item>
      </vgr-list>
```

### Förväntat beteende
När jag har angivit `[sortDirection]="sortDirection.Descending"` så förväntar jag mig att pilen pekar nedåt.

### Faktiskt beteende
Pilen pekar uppåt

### Skärmdumpar mm
![sortdirection](https://user-images.githubusercontent.com/44672809/49368303-9824d480-f6ee-11e8-80aa-49fa7c2c163b.PNG)

**Comment by kebarvid** [comment]
Uppmärksammade det när jag gjorde ändringar i listan tidigare i höst, har tydligen varit en del diskussioner tidigare om vilket håll pilarna bör vara. Men när jag gjorde om där så ändrade vi så att det blir så som du och jag tycker att det bör vara. Så från och med version 4.0.0 av komponentkartan så är det så.

**Comment by AronssonFredrik** [comment]
Hej,
Detta är ingen pil utan en caret. Den symboliserar lågt till högt.

**Comment by perut1** [comment]
Om ^ symboliserar lågt till högt så är det ju tvärt emot vad jag bad den att sortera när jag satte den till `[sortDirection]="sortDirection.Descending"`

**Comment by AronssonFredrik** [comment]
Hej,
Med version 6 som vi lanserar de nästkommande dagarna kommer `vgr-list` att bli deprecated och blir ersatt med `vgr-grid` som används i exemplet nedan.

Nedan ser vi ett exempel med ascending order.

Det ska följa enligt [länk](https://www.kb.blackbaud.co.uk/articles/Article/117098)
> For numbers or amounts, the sort is smallest to largest. Lower numbers or amounts will be at the top of the list.
> For letters/words, the sort is alphabetical from A to Z.

[Föjande länk](https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header#answer-38654) visar på caret för ascending order.

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/listexample-expandable-div

Hoppas det gör saken mer klar, annars hojta

Fredrik
