### ISSUE TITLE
Enter borde avvälja alternativ i en multiselect dropdown

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#340]
### Beskrivning
*Eftersom 'Enter' avväljer 'Välj alla' valet så borde den även avvälja enskilda items i en Multiselect Dropdown.*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta17**
* Angular version: **Angular: 7.0.4 och Angular-Cli: 7.0.6**
* Browsers: **Edge, IE11, Chrome**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Dropdown select under komponenter
3. Tryck upp Exempel
4. Tryck på dropdownen med texten 'Alternativ med extra information' ovanför sig
5. Tryck 'Piltanget Ned' 3 gånger och sedan 'Enter'
6. Tryck Enter 2 gånger till*

### Förväntat beteende
*Val 1 avväljs*

### Faktiskt beteende
*Val 1 stannar som vald*

### Övrig information, kodexempel och motivering till förändring
*Borde vara konsekvent med 'Välj alla'*

### Skärmdumpar mm
*![enter avvaljer inte items i listan](https://user-images.githubusercontent.com/36041543/49996610-bcef3680-ff8f-11e8-926f-6fe8ab5736c3.gif)*

**Comment by kinbode** [comment]
Detta är by design. Motivationen är att enter alltid ska välja markerat alternativ och stänga, vara sig det är multi eller inte. Välj alla ses däremot inte som ett valbart alternativ, utan en action och beter sig annorlunda.

**Comment by louisebroo** [comment]
Jag håller med om att detta är by design. Det är ganska tydligt definierat i WCAG så jag föreslår att vi behåller beteendet som det är.
