### ISSUE TITLE
Tab inuti en dropdown

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#341]
### Beskrivning
*Trycker man på tab inuti en dropdown i Edge hamnar man Längst upp i headern och det itemet man hade fokus på ser ut som om den har fokus.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta17**
* Angular version: **Angular: 7.0.4 och Angular-Cli: 7.0.6**
* Browsers: **Edge**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Dropdown select under komponenter
3. Tryck upp Exempel
4. Tryck på en dropdown
5. Tryck 'Piltanget Ned' så att du hamnar på ett item i dropdownen och sedan tryck på 'Tab'*

### Förväntat beteende
*Fokus hamnar på nästa dropdown i listan*

### Faktiskt beteende
*Fokus hamnar på systeminformation i headern*

### Skärmdumpar mm
*![tab i edge pa dropdown](https://user-images.githubusercontent.com/36041543/50004282-08f9a580-ffa7-11e8-8ff2-f19621393d7d.gif)*

**Comment by maddefinlof** [comment]
Buggen är omtestad och är okej. DEMO vgr-komponentkartan version: 5.0.0-beta6, Angular: 7.1.0 och Angular-Cli: 7.3.9
