### ISSUE TITLE
"Teckentangent" flyttar inte fokus till tidigare alternativ

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#342]
### Beskrivning
*När man trycker på teckentangenter i en dropdown så kommer man inte till ett tidigare alternativ om man har fokus på något item som inte kommer först.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta17**
* Angular version: **Angular: 7.0.4 och Angular-Cli: 7.0.6**
* Browsers: **Edge, IE11, Chrome**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Dropdown select under komponenter
3. Tryck upp Exempel
4. Tryck på dropdownen med texten 'Stor, många alternativ' ovanför sig
5. Tryck på 'E'
6. Tryck på 'A'*

### Förväntat beteende
*Fokus hamnar på 'Adam'*

### Faktiskt beteende
*Fokus hamnar på 'Erika'*

### Skärmdumpar mm
*![teckentangent flyttar inte fokus](https://user-images.githubusercontent.com/36041543/50008904-cbe8df80-ffb5-11e8-9567-30b3cbceb6cb.gif)*

**Comment by kinbode** [comment]
Detta är by design. Sök går endast framåt från aktiv position.
