### ISSUE TITLE
Ingen fokus på monthpicker när man trycker på den

### ISSUE THREAD

**Issue by KristofferBackman** [Vastra-Gotalandsregionen/komponentkartan#345]
### Beskrivning
*Trycker man på en inaktiv monthpicker i IE11 får den inte fokus*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **4.0.0-beta17**
* Angular version: **Angular: 7.0.4 och Angular-Cli: 7.0.6**
* Browsers: **IE11**

### Steg för att påvisa problemet
*1. Besök komponentkartan-demo http://vgwb0399.vgregion.se:4500/
2. Klicka på Monthpicker under komponenter
3. Tryck upp Exempel
4. Tryck på en monthpicker som är disabled*

### Förväntat beteende
*Monthpickern får fokus*

### Faktiskt beteende
*Ingenting får fokus*

### Skärmdumpar mm
*![ingen fokus pa monthpicker](https://user-images.githubusercontent.com/36041543/50279907-62e8e800-044b-11e9-80fe-a99b7f45a634.gif)*

**Comment by AronssonFredrik** [comment]
Hej @KristofferBackman,
Vi har gjort en release av v6.0.0 av komponentkartan som löser detta med `vgr-datepicker`.

Vi har tre olika varianter:
:heavy_check_mark: Default (aktiv) - kan fokuseras
:x: Disabled (inaktiv) - kan ej fokuseras
:heavy_check_mark: Readonly (endast visning) - kan fokuseras
 
https://vastra-gotalandsregionen.github.io/komponentkartan-demo/datepicker

Mvh,
Fredrik
