### ISSUE TITLE
Blur av <vgr-input> resulterar i valueChanges även om värdet inte är förändrat

### ISSUE THREAD

**Issue by patrikbjork** [Vastra-Gotalandsregionen/komponentkartan#347]
### Beskrivning
Givet att man "prenumererar" på förändringar av ett formulär, t.ex.:
````
this.updateOnChangeForm.valueChanges.subscribe(_ => {
  console.log('changed...');
});
````

Då kommer console.log() köras även om man bara ställer markören i vgr-input-fältet och sedan går ur fältet.

Om man kommenterar ut ``this.onChange(this.value)``ur nedanstående funktion i input.component.ts åtgärdas det beteendet:
````
  onBlur(event: Event) {
    if (this.readonly) {
      return;
    }

    this.onTouched();
    this.formatDisplayNumber();

    // this.onChange(this.value);
    this.hasFocus = false;
    this.blur.emit(event);

  }
````
### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: t.ex. 3.2.1 och 4.0.0-beta20
* Angular version: 6 och 7
* Browsers: Troligen alla

### Steg för att påvisa problemet
Man prenumererar på valueChanges på ett formulärobject: form.valueChanges.subscribe(). Enligt ovan.

### Förväntat beteende
Blur ska inte orsaka valueChange.

### Faktiskt beteende
Blur orsakar valueChange.

### Övrig information, kodexempel och motivering till förändring
En kanske relaterad sak. InputComponent.onChange skrivs över via InputComponent.registerOnChange. Således spelar innehållet i ursprungliga funktionen ingen roll.

**Comment by louisebroo** [comment]
Jag förstår inte riktigt den här beskrivningen, vill du försöka förtydliga för en som inte är så insatt i koden? @patrikbjork

**Comment by patrikbjork** [comment]
För att ta ett exempel från vår applikation. Vi kodade att en checkruta skulle bockas i om man skrev något i ett visst fält. Men nu bockades checkrutan i utan att man behövde skriva något. Det räckte att ställa markören i fältet och sen gå ur fältet.

Men problemet är mer generellt att vad man än har kodat ska hända vid change även händer vid blur. @louisebroo

**Comment by louisebroo** [comment]
Då förstår jag. Låter inte alls bra, det får vi ta tag i. Jag tror vi har en liknande issue här: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/234 är denna redundant eller är det två olika problem?

**Comment by patrikbjork** [comment]
Det är två olika problem. #234 är tillägg av en funktion som saknas.

**Comment by louisebroo** [comment]
Då förstår jag, skapar en ytterligare bugg i Pivotal Tracker då.

**Comment by herrklaseen** [comment]
Jag har inspekterat nuvarande kod och även testat att göra enligt beskrivningen och det här är inte längre ett problem.

@athid Jag stänger det här ärendet.
