### ISSUE TITLE
Modal ser konstig ut när man öppnar den efter att ha scrollat en bit på sidan.

### ISSUE THREAD

**Issue by kebarvid** [Vastra-Gotalandsregionen/komponentkartan#349]
![modalbugg](https://user-images.githubusercontent.com/973836/52851008-4d273480-3115-11e9-9722-229060c92176.PNG)
### Beskrivning
När modalen öppnas hamnar innehållet i VGR-page-block ovanför header och page-header.

### Typ av ärende (kryssa i en med "x")
- [ X ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 4.0.0
* Angular version: 7.1.0
* Browsers: Chrome, Internet Explorer, Edge

### Steg för att påvisa problemet
1. Besök http://vgwb0399.vgregion.se:4500/modaldialog
2. Klicka upp listvalet exempel.
3. Öppna modalen längst ner i den rutan.
4. Bakom det skuggade lagret kommer nu innehållet i listan att hamna ovanför header och page headern. (se bild för exempel)

### Förväntat beteende
Modalen lägger sig över utan att det som ligger i bakgrungen ändrar sig.

### Faktiskt beteende
När modalen öppnas hamnar innehållet i VGR-page-block ovanför header och  @page-header.

### Övrig information, kodexempel och motivering till förändring
I samband med att VGPV-Klient använde modalen för godkänn/granska, så gjorde jag om den lite för att det skulle funka att lägga en modal var man ville i sin markup. (Tidigare gick det endast att ha ytterst i domen.) Efter det dök det upp lite problem med att den skuggade bakgrunden inte täckte hela fönstret. Detta löstes dock men buggen vi har nu är förmodligen en rest från detta arbete.

### Skärmdumpar mm
Se skärmdump högst upp.

**Comment by louisebroo** [comment]
Detta finns redan inlagt i Pivotal som en bug som vi kommer titta på under kommande sprint förhoppningsvis.

**Comment by kebarvid** [comment]
Kanon! Se bara till att inte ta bort möjligheten (som jag la in tidigare) att man kan lägga modalen var man vill, för det använder vi i vgpv-klient idag.

**Comment by louisebroo** [comment]
@nihreborn det som arvid beskriver är väl inget som vi har förändrat i modalen?

**Comment by nihreborn** [comment]
Nej, det är den gamla buggen att allt under modalen (meny, header, osv) sätts till samma z-order vilket leder till att de kommer i den ordningen de ritas ut.

**Comment by louisebroo** [comment]
Jag tänkte mer i den tidigare storyn vi gjorde där man fick ändra storlek på modalen. Det var inget mer vi ändrade va?

**Comment by nihreborn** [comment]
Nej, bara bredden.

**Comment by kebarvid** [comment]
Denna verkar inte vara löst. Jag hittade en workaround som jag la in på VGPV-klient där jag la in följande SCSS-kod :

`.modal--open {
  overflow: hidden;
  .sidebar-menu,
  .page-header {
    z-index: 0;
  }
  header.header {
    z-index: 3;
    &:after {
      content: '';
      position: fixed;
      top: 0;
      left:0;
      display: block;
      width: 100%;
      height: 79px;
      background: #151515;
      opacity: 0.65;
    }
  }
}`

Det känns lite hackigt och jag har inte testat det fullt ut, så jag lägger inte in det i kompoentkartan nu, men om det är fler som upptäcker liknande problem i sina projekt så kan de testa detta.

**Comment by AronssonFredrik** [comment]
Hej @kebarvid ,
Detta ska vara löst nu:
https://vastra-gotalandsregionen.github.io/komponentkartan-demo/modaldialog

Fredrik
