### ISSUE TITLE
vgr-datepicker blir för stor i höjdled

### ISSUE THREAD

**Issue by nader-einanlo** [Vastra-Gotalandsregionen/komponentkartan#351]
![datepicker](https://user-images.githubusercontent.com/15648121/55224426-d18ace00-5210-11e9-9c7b-879636cff2a2.PNG)

**Comment by Jbraaf** [comment]
Hej! Följ gärna instruktionerna när du skapar en bugg/förbättringsförslag så att vi lättare i ett första skede kan få lite mer information att gå på. / Johanna

**Comment by AronssonFredrik** [comment]
Hej @nader-einanlo ,
Skulle du kunna uppdatera issuen genom att följa instruktioner som nämnts ovan?

Fredrik

**Comment by AronssonFredrik** [comment]
Hej @nader-einanlo,
Jag stänger storyn då den inte blivit uppdaterad. Hör av dig om du fortfarande behöver hjälp.

Fredrik
