### ISSUE TITLE
Otydligt när knappar "trycks ner" med tangentbordet

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#374]
### Beskrivning
När man navigerar endast med tangentbordet får man mindre feedback om man trycker enter när en knapp är fokuserad än om den trycks ner med muspekaren. I fall då knappen inte svarar blir det extra irriterande eftersom det inte är tydligt om jag lyckades trycka alls.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **5.0.0**
* Angular version: **7.1.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
* Tabba till en knapp
* Tryck Enter

### Förväntat beteende
När jag trycker på Enter borde knappen ändra storlek och få en skugga som den får om jag klickar med musen.

### Faktiskt beteende
Knappens utseende påverkas inte av Enter

**Comment by herrklaseen** [comment]
@louisebroo 
Jag har gjort en fix för detta som kan ses på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/textbuttons

**Comment by athid** [comment]
Jag tycker det ser nice ut, vad säger du @louisebroo?

**Comment by louisebroo** [comment]
Det ser bra ut :)
