### ISSUE TITLE
Dropdown select följer inte med resten av innehållet när validering läggs på

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#375]
### Beskrivning
När en dropdown-kontroll får ett felmeddelande flyttas kontrollen neråt för att ge plats åt felmeddelandet. Om dropdown select är öppen följer inte själva listan med i förflyttningen så den ser ut att hamna mitt i fältet (se bild).

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **5.0.0**
* Angular version: **7.1.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
* Gå in på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/reactiveformsexample
* Tryck på "Submit"
* Öppna dropdown

Samma beteende har observerats i Ivard.

### Förväntat beteende
Hela kontrollen förflyttas när felmeddelandet läggs på. 

### Faktiskt beteende
Själva rutan flyttas men listan med alternativ har samma position som innan felmeddelandet visades. 

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
<img width="678" alt="Skärmavbild 2019-06-19 kl  14 14 00" src="https://user-images.githubusercontent.com/35460884/59765195-d1ddb700-929d-11e9-99b1-ac7285876f19.png">

**Comment by AronssonFredrik** [comment]
Hej @louisebroo,
Vill minnas att jag löste detta tidigare, kan du kika så att allt funkar som förväntat - annars får du gärna återöppna issuen

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/reactiveformsexample
