### ISSUE TITLE
Etiketter till kontroller läses inte upp av skärmläsaren

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#376]
### Beskrivning
När man använder en skärmläsare för att läsa innehållet i våra system läses inte etiketter till olika kontroller upp. Tex kommer jag till en dropdown och hör bara "välj" och "lista med noll alternativ" (??)

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **5.0.0**
* Angular version: **7.1.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
Exempelvis:
* Aktivera skärmläsare, t.ex. Chromevox
* Gå in på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select
* Öppna "Exempel"
* Tabba till en dropdown och lyssna

Samma beteende gäller för alla kontroller jag hittat med etiketter.

### Förväntat beteende
När en kontroll som har en etikett fokuseras och skärmläsaren är aktiv ska etiketten som hör till kontrollen läsas upp.

### Faktiskt beteende
Etiketten läses inte upp.

**Comment by ralvesmartins** [comment]
Testa om det fungerar att implementera på samma sätt som title value. 

Diskutera med UX  hur vi vill att det ska fungera. Finns det fler komponenter som detta gäller för?

**Comment by ralvesmartins** [comment]
UX tycker att label ska vara en del av alla kontrollkomponenter och visas som default. 
Detta skulle lösa problemet med att skärmläsare inte läser upp labeln och även lösa att labeln hamnar på olika avstånd enligt följande story: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/381
