### ISSUE TITLE
Komponent checkbox-Fokus markering går utanför checkbox

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#377]
### Beskrivning
*Fokus markering går utanför checkbox.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Angular version: **version: 5.0.0, Angular: 7.1.0 och Angular-Cli: 7.3.9 **
* Browsers: **Alla**

### Steg för att påvisa problemet
*1. Tryck på Checkbox
2. Markera en checkbox under "Exempel"*

### Förväntat beteende
*Fokus borde markeras runt checkboxrutan*

### Faktiskt beteende
*fokus markering ligger utanför checkbox*

### Övrig information, kodexempel och motivering till förändring
**Kommentar 25/2 2020**
Vi gör det vi kan och kikar på det igen när markeringen går så nära vi kan få den eftersom det är en svgbild. 

Radiobutton är idag ingen svgbild utan hmtlkod. På länkarna syns hur radiobutton ser ut. Förslagsvis så låter vi Radiobutton vara html och kanske också checkbox?

Radiobutton:
https://fontawesome.com/icons/circle?style=regular
https://fontawesome.com/icons/circle?style=solid

## Acceptanskriterier
- Fokus markeras runt checkboxrutan
- Checkbox är ifylld #FFFFFF

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
![image](https://user-images.githubusercontent.com/999511/91440313-b3465900-e86e-11ea-920e-f3b33278be45.png)

**Comment by maddefinlof** [comment]
![checkboxMarkeringUtanför](https://user-images.githubusercontent.com/33692196/59775277-3ce4b900-92b1-11e9-9662-6daeb5930245.PNG)

**Comment by CrestTheFury** [comment]
Bland annat löst i release 9.1.0
