### ISSUE TITLE
vgr-list täcker kommande 

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#378]
### Beskrivning
När man har någonting som ligger efter en vgr-list så täcker listan till viss del över det som kommer efter så man inte kan se det.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 4.0.1-beta3
* Angular version: 7.0.4
* Browsers: Firefox, Edge, IE, Chrome

### Steg för att påvisa problemet
``` 
      <vgr-list>
        <vgr-list-header (sortChanged)="sortChanged($event)">
          <vgr-list-column-header width="4" sortKey="Datum" [sortDirection]="sortDirection.Descending">Datum</vgr-list-column-header>
          <vgr-list-column-header width="3" sortKey="RegistreradAv">Registread av</vgr-list-column-header>
          <vgr-list-column-header width="2" sortKey="BesokIFil" [align]="'right'">Besök i fil</vgr-list-column-header>
          <vgr-list-column-header width="5" sortKey="BesokSomKraverAtgard" [align]="'right'">Besök som kräver åtgärd</vgr-list-column-header>
          <vgr-list-column-header width="2" sortKey="Status">Status</vgr-list-column-header>
          <vgr-list-column-header width="2" [align]="'center'">Ta bort</vgr-list-column-header>
        </vgr-list-header>
        <vgr-list-item>
            <vgr-list-item-header class="smaller-text">
              <vgr-list-column width="4">sdg</vgr-list-column>
            </vgr-list-item-header>
            <vgr-list-item-content>
              foo
          </vgr-list-item-content>
        </vgr-list-item>
      </vgr-list>
      <ol>
        <li>rad 1</li>
        <li>rad 2</li>
        <li>rad 3</li>
        <li>rad 4</li>
      </ol>
``` 

### Förväntat beteende
Komponenter efter listan borde synas utan att bli täckta.

### Faktiskt beteende
I den efterföljande listan så syns inte rad 1 då den hamnar under listan

### Skärmdumpar mm
![komponentkartebugg](https://user-images.githubusercontent.com/44672809/59776763-a49c0380-92b3-11e9-9f61-c90b610dcda1.PNG)

**Comment by AronssonFredrik** [comment]
Hej,
Finns det en anledning vi vill ha content nedanför `vgr-list`?
Förslagsvis skulle vara att wrappa content i en ny `vgr-page-block`, som kod nedan. Skulle detta kunna lösa ert problem?

Har ännu inte hittat någon lösning till att redigera margin, detta då den används för att ha rätt avstånd mellan flera `vgr-list`.

```
    <vgr-page-block>
      <vgr-list>
        <vgr-list-item>
          <vgr-list-item-header>
            <vgr-list-column>List Header</vgr-list-column>
          </vgr-list-item-header>
          <vgr-list-item-content>List Content</vgr-list-item-content>
        </vgr-list-item>
      </vgr-list>
    </vgr-page-block>
    <vgr-page-block>
      <ol>
        <li>rad 1</li>
        <li>rad 2</li>
        <li>rad 3</li>
        <li>rad 4</li>
      </ol>
    </vgr-page-block>
```
