### ISSUE TITLE
Kunna använda lista utan header och kolumner

### ISSUE THREAD

**Issue by MarcusAlfredsson** [Vastra-Gotalandsregionen/komponentkartan#38]
### Beskrivning
Vi har en lista där vi inte önskar ha kolumner utan enbart en lista. Men verkar som man måste ange vgr-list-header, även om man inte vill använda den

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 0.2.1-rc18
* Angular version: 4.4.6
* Browsers: chrome

### Steg för att påvisa problemet
Om man inte anger vgr-list-header så kommer man få fel i consolen

### Förväntat beteende
Inga fel och det fungerar utan att ange vgr-list-header för listan

**Comment by perakerberg** [comment]
Hej! Utifrån de exempel vi hittills har i BMM, VGPV, Rehab och Privera så har alla listor både rubrik och kolumner. Det är för de användningsfallen vi har anpassat listan. För att den ska vara enkel att använda i dessa fall är den också lite mer begränsad.

**Comment by MarcusAlfredsson** [comment]
En annan fundering här, jag tycker er list komponent börjar bli mer likt en table än en list. Är det så tanken är? Enligt mig har man kolumner i en tabell och inte i en lista

**Comment by perakerberg** [comment]
Kan vara en korrekt iakttagelse. När vi kommer i ett läge där vi har både en lista och tabell kan det ju bli läge att byta namn. Givet att vi idag bara har en lista (som kanske är en tabell) så får den heta lista :)
