### ISSUE TITLE
Dropdown borde inte återställas när byter flik eller applikation

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#380]
### Beskrivning
Jag har öppnat en dropdown och t.ex. gjort en sökning men behöver kolla upp något i en annan flik (ex vilket avtalsnummer jag skulle välja). När jag kommer tillbaka till fliken med dropdownen så har den stängt sig och sökningen har försvunnit. Detta gör att det blir svårt att jämföra alternativen i listan med annan information såsom en instruktion. Samma beteende uppstår när jag går in i en annan applikation, t.ex. Word eller någon annanstans jag har en instruktion.   

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **5.0.0**
* Angular version: **7.1.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
* Gå in på https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select
* Öppna dropdown
* Gå till annan flik eller annan applikation

### Förväntat beteende
När jag kommer tillbaka till sidan med dropdown är den fortfarande öppen. Har jag börjat söka i den finns min sökning kvar.

### Faktiskt beteende
Dropdown har stängts och min sökning är återställd.

**Comment by herrklaseen** [comment]
@louisebroo @athid 

Jag har kollat närmare på det här ärendet. 

En "vanlig" `select` beter sig precis som vår: om man klickar på den och sedan lämnar fliken så är selecten stängd när man återkommer. Det är standard-beteende. 

Jag har dock hittat en select i Googles egna Material-lib till Angular som beter sig som det här ärendet beskriver. Tyvärr är det inte trivialt att implementera. Vad googleteamet har gjort är att hantera flertalet events själva och inte använda sig av inbyggda events som t ex `blur` eller `focusout`. Det innebär att de kan låta selecten vara öppen eftersom det inbyggda `focusout` eventet som normalt skickas när man byter flik inte påverkar deras select. 

För att fixa det i vårt bibliotek behöver vi nog gå tillbaka till grunderna för komponenten, alternativt bygga en ny, och inspireras av Googles lösning.

**Comment by louisebroo** [comment]
@herrklaseen Det låter inte som att vi borde prioritera att göra om vår select i så fall. Jag skulle gärna se att vi i applikationen istället kunde koppla mer relaterad information så skulle användaren, i vårt fall, inte behöva kolla i en instruktion.

**Comment by herrklaseen** [comment]
@louisebroo
Jag håller med. Att hjälpa användaren så denne inte behöver växla flikar mitt i ett val låter som en bra idé. 

 @athid 
Kanske läge att stänga det här ärendet i så fall?
