### ISSUE TITLE
Etiketter till text area hamnar på olika avstånd jämfört med övriga kontroller

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#381]
### Beskrivning
När man lägger etiketter över kontrollerna hamnar de inte på samma avstånd från kontrollen. Jag tror också att det är upp till implementatören att själv sätta avståndet vilket för att det blir olika i olika sidor. För textarea går det inte heller att sätta etiketten lika nära som för de andra kontrollerna. Det gör att det ser stökigt ut.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **5.0.0**
* Angular version: **7.1.0**
* Browsers: **Chrome**

### Steg för att påvisa problemet
Har inte sett något exempel i demokartan men man kan gå in på https://ivard-test.vgregion.se och gå in på Betalningsförbindelser. 
* Skapa ny betalningsförbindelse
* Lägg till en patient och jämför avstånd mellan etikett och kontroll

### Förväntat beteende
När man lägger till en etikett ovanför sin kontroll ska den hamna på ett förutbestämt avstånd ovanför kontrollen. 

### Faktiskt beteende
Etiketter hamnar inte automatiskt på det avstånd som förväntas och det finns inte dokumenterat vilket avstånd som borde användas. 

### Skärmdumpar mm
![långt namn på patient](https://user-images.githubusercontent.com/35460884/59833076-98f91d00-9345-11e9-81e3-f042180d5a39.png)

**Comment by herrklaseen** [comment]
@athid 

Så vitt jag förstår ska vi använda https://vastra-gotalandsregionen.github.io/komponentkartan-demo/titlevalue istället för input och label. Personligen tycker jag designen på title-value är suboptimal, men det är ju inte min sak. 

I alla fall så är frågan om vi ska jobba med den här eller inte.

**Comment by ralvesmartins** [comment]
Löses av denna story: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/376
