### ISSUE TITLE
Listheader ej klickbar vid FlexibleHeader=false (default)

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#383]
### Beskrivning
Om man har en lista där FlexibleHeader är false (vilket är defaultvärde) så kan man inte trycka på headern (gäller bla. för sortering, checkboxar eller annat man lägger i headern).

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 5.0.0
* Angular version: 
* Browsers: Testat i edge och chrome

### Steg för att påvisa problemet
Gå in på komponentkartan-demo och försök trycka på headern under exempellistor, där kan man inte trycka på headern. Men går man in under listorna i kodexempel (där flexibleHeader = true) så kan man sortera osv.

### Förväntat beteende
Man skall kunna använda headern och trycka på den för att ex. sortera

### Faktiskt beteende
Händer inget när man trycker på headern

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by kebarvid** [comment]
Den här är löst i nuvarande version 5.0.3, kan ha lösts redan i nån tidigare minor-version.
