### ISSUE TITLE
Input, Inmatningsfunktion för belopp klarar inte att hantera sitt egna format

### ISSUE THREAD

**Issue by JohanWinqvist** [Vastra-Gotalandsregionen/komponentkartan#384]
### Beskrivning
Input, Inmatningsfunktionen för belopp klarar inte att hantera sitt egna format.

### Typ av ärende (kryssa i en med “x”)
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
Version av vgr-komponentkartan: 5.00
Angular version: 7.1.0 
Browsers: Chrome
IVARD test

### Steg för att påvisa problemet
1. Gå till komponenten Input och mata in värdet, '10 000 000 000 000'.
2. Verifiera att funktionen inte tar emot värdet vid submit och följdaktligen inte returnerar något värde.

### Förväntat beteende
GIVET att jag matar in ett värde som är formaterat enligt NN NNN NNN NNN NNN,N eller NN NNN NNN NNN NNN till Input,
NÄR jag submittar värdet,
DÅ tar funktionen emot värdet OCH returnerar enligt samma format: NN NNN NNN NNN NNN,N eller NN NNN NNN NNN NNN.

Komponenten borde kunna hantera sitt egna format och returnera t ex. '10 000 000 000 000' för inmatning '10 000 000 000 000' såväl som '10000000000000'.

### Faktiskt beteende
GIVET att jag matar in ett värde som är formaterat enligt NN NNN NNN NNN NNN,N eller NN NNN NNN NNN NNN till Input,
NÄR jag submittar värdet, 
DÅ tar inte funktionen emot värdet OCH returnerar "Ange ett värde" ELLER returnerar ingenting.

### Övrig information, kodexempel och motivering till förändring
Varför det är intressant att funktionen skall klara av att hantera sitt egna format som indata, beror på att t.ex en användare kan 
vilja kopiera ett värde från en annan webbsession där Input har returnerat ett värde med sitt format,
för att sedan klistra in detta värde som belopp i sin aktuella webbsession.

Detta upptäcktes i "IVARD > Betalningsförbindelser > BF-96 > Ändra > Fältet: begränsning pris"
Se även skärmdump på var någonstans fältet används.
### Skärmdumpar mm
![BF96](https://user-images.githubusercontent.com/52245638/60239393-d9a8e700-98ad-11e9-866b-149b54d0e66d.PNG)

**Comment by AronssonFredrik** [comment]
Hej @JohanWinqvist,
Detta är fixat i version 5.1.1 och senare.
