### ISSUE TITLE
Input, Inmatningsfunktion för belopp skriver inte ut ören med två siffror.

### ISSUE THREAD

**Issue by JohanWinqvist** [Vastra-Gotalandsregionen/komponentkartan#385]
### Beskrivning
Input, Inmatningsfunktion för belopp skriver inte ut ören med två siffror.

### Typ av ärende (kryssa i en med “x”)
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
Version av vgr-komponentkartan: 5.00
Angular version: 7.1.0 
Browsers: Chrome
IVARD test

### Steg för att påvisa problemet
1. Gå till Input och mata in värdet, '10.50'.
2. Verifiera att funktionen tar emot värdet efter submit och returnerar 10,5.

### Förväntat beteende
GIVET att jag matar in ett värde som har något av formaten: 
NN.N
NN.NN
NN,N
NN,NN
till komponenten Input,

NÄR jag submittar värdet, 
DÅ tar funktionen emot värdet OCH returnerar värdet enligt formatet NN,NN

### Faktiskt beteende
GIVET att jag matar in ett värde som är formaterat enligt NN.NN till Input,
NÄR jag submittar värdet,
DÅ tar funktionen emot värdet OCH returnerar: NN,N.

GIVET att jag matar in ett värde som är formaterat enligt NN,NN till Input,
NÄR jag submittar värdet,
DÅ tar funktionen emot värdet OCH returnerar: null.

### Övrig information, kodexempel och motivering till förändring
Ören skall skrivas ut med två siffror. Komponenten borde returnera '
10,50' för inmatning '10.50', '10.5', 10,50 eller 10,5.

Varför det är intressant att funktionen skall klara av att hantera sitt egna format som indata, beror på att t.ex en användare kan 
vilja kopiera ett värde från en annan webbsession där Input har returnerat ett värde med sitt format,
för att sedan klistra in detta värde som belopp i sin aktuella webbsession.

Detta upptäcktes i IVARD > Betalningsförbindelser > BF-96 > Ändra > Fältet begränsning pris

### Skärmdumpar mm
![BF96](https://user-images.githubusercontent.com/52245638/60242866-28a74a00-98b7-11e9-9b66-a56e9532038c.PNG)

**Comment by Jbraaf** [comment]
Det går att välja hur formateringen ska ske, se APIdelen på inputkomponent.
