### ISSUE TITLE
Input, Inmatningsfunktion kan hålla för stora belopp

### ISSUE THREAD

**Issue by JohanWinqvist** [Vastra-Gotalandsregionen/komponentkartan#386]
### Beskrivning
Input, Inmatningsfunktion kan hålla för stora belopp. Nu går gränsen vid 99 999 999 999 999 kr, hundra tusen miljarder, vilket är mer än 20 gånger större belopp än Sveriges BNP 2018.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
Version av vgr-komponentkartan: 5.00
Angular version: 7.1.0 
Browsers: Chrome
IVARD test

### Steg för att påvisa problemet
Fyll ut komponenten med '9' för att verifiera möjlig beloppslängd.

### Förväntat beteende
Beloppsstorlek bör ändras till hur stora kostnader som kan registreras med en mer lämplig kostandsmarginal.

### Faktiskt beteende
Belopp som kan anges är alldeles för stort.

### Övrig information, kodexempel och motivering till förändring
Ta reda på lämplig storlek på fält, som fungerar med förenade affärssystem.

**Comment by Jbraaf** [comment]
Det finns möjlighet att lägga till maxantal på komponenten, finns i APIbeskrivning på inputsidan
