### ISSUE TITLE
Kontroller i read-only, dynamisk bredd

### ISSUE THREAD

**Issue by brustablett** [Vastra-Gotalandsregionen/komponentkartan#390]
### Beskrivning
Idé: Kontroller i read-only – anpassa storlek till innehåll, vilket gör det möjligt att lägga andra objekt nära.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

**Comment by AronssonFredrik** [comment]
Hej @brustablett ,
Har du tid att uppdatera issuen? Ytterst oklart vad som efterfrågas.
