### ISSUE TITLE
Dropdown – Flytta fokus när filtrering resulterar i ett alternativ

### ISSUE THREAD

**Issue by brustablett** [Vastra-Gotalandsregionen/komponentkartan#391]
### Beskrivning
För att förenkla tangentbordsnavigation, vore det en fördel att flytta fokus när filtrering i en dropdown resulterar i en lista med ett enda alternativ. Det gör att det går att välja och stänga genom att bara trycka Enter.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Steg för att påvisa problemet
När jag filtrerar i en dropdown med många poster, blir alternativen allt färre. När det endast finns ett alternativ, måste jag ändå trycka Pil ned + Pil ned innan jag kan trycka Enter för att välja.

### Förväntat beteende
När jag filtrerar i en dropdown med många poster, blir alternativen allt färre. När det endast finns ett alternativ, flyttar fokus till alternativet så att jag kan trycka Enter för att välja det.

**Comment by ralvesmartins** [comment]
Stängs då Combobox kan lösa dessa fall
