### ISSUE TITLE
Gör botten på sidor mer luftig

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#392]
### Beskrivning
När man scrollar längst ner på sidan finns inte så mycket white space vilket gör att det känns trångt och man kan få känslan att innehållet inte helt får plats. Detta förstärks av att kort som öppnas inte automatiskt scrollas upp i skärmen så man ser inte innehållet om det är sista raden som öppnas. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Steg för att påvisa problemet
Gå till botten av en lista och upplev känslan av att vara trängd (^^)

### Förväntat beteende
Det finns mer utrymme som inte används för att visa upp våra komponenter på så att jag får en härlig och luftig känsla.

### Skärmdumpar mm

<img width="1440" alt="Skärmavbild 2019-08-28 kl  14 30 04" src="https://user-images.githubusercontent.com/35460884/63855879-b92a0580-c9a0-11e9-867b-861933f94df8.png">

**Comment by ralvesmartins** [comment]
Problemet kvarstår inte
