### ISSUE TITLE
keyboard stängning av Modal komponenten

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#393]
### Beskrivning
Modal dialog komponenten stänger inte vid tryck på `escape`. Enligt WCAG ska vi tillåta det, och därmed borde funktionalitet följa med komponenten.

relevanta guidelines: https://www.w3.org/TR/wai-aria-practices/#dialog_modal

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **vad?**
* Angular version: **hur så?**
* Browsers: **Trousers**

### Förväntat beteende
`escape` ska stänga modal per automatik

**Comment by herrklaseen** [comment]
@athid @TorinWilliams 

Jag har gjort en ändring som gör att modal-dialogen stängs vid tryck på escape. https://vastra-gotalandsregionen.github.io/komponentkartan-demo/

Lösningen stödjer dock inte att användaren lämnar "fokus" på dialogen, dvs om användaren klickar på den grå bakgrunden som kommer escape inte stänga dialogen längre. Det beror på att modal-dialogen inte längre är i fokus och inte kan lyssna på tangentbords-tryck. Om vi vill fixa det tror jag vi behöver tänka om lite hur modalen funkar rent tekniskt. 

Enligt WaiAria så ska en modal dialog inte kunna lämnas och det kan man alltså i vårt fall. Även om det inte ser ut så.

**Comment by TorinWilliams** [comment]
Vad bra! Jag är osäker om scenariot du nämnde skulle i praktiken vara problematiskt, då man inte kan lämna fokus i modalen med keyboard. Har man klickat i det grå, då är man förmodligen även mus användare och borde kunna klicka sig i igen. Men det är kanske värt att diskutera med Anders när han är tillbaks. Snyggt jobbat!

**Comment by athid** [comment]
Känns som vi kanske skall skriva en bugg på att man kan lämna dialoge, men det känns i nuläget som en lågt prioriterad fix.

**Comment by erfham** [comment]
@athid Har det skapats någon bugg på att man kan lämna fokus från dialogen? 

En del av buggen kommer ju lösas när https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/446 är implementerat om jag förstår det rätt, dock kan man fortf lämna fokus om man klickar på exempelvis text i modalen.

**Comment by erfham** [comment]
@herrklaseen 

Chrome - OK
Edge - OK
IE 11 - Inget händer när man trycker esc
Reproducera:
1. Gå till https://vastra-gotalandsregionen.github.io/komponentkartan-demo/modaldialog
2. öppna en modal
3. se till att fokus är i modalen och tryck escape

**Comment by AronssonFredrik** [comment]
```Javascript
    case "Esc": // IE/Edge specific value```

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by AronssonFredrik** [comment]
Hej,
Testade igen i IE och Edge och kan inte reproducera felet.

Testa gärna igen: https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select

Fredrik
