### ISSUE TITLE
Möjlighet att förhindra navigering mellan paginerade sidor

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#394]
### Beskrivning
När man använder pagern för att navigera mellan olika sidor av en lista finns idag inget sätt att förhindra att sidan byts. Det blir problematiskt när man har gjort en ändring i en listrad, t.ex. om användaren försöker byta namn på en vårdenhet, men ännu inte sparat. Då vill man kunna förhindra att sidan med den osparade listraden byts för att ge användaren möjlighet att se över ändringarna och ta ett beslut om de ska sparas eller inte. Det gör att det blir svårt att förstå vad man tar ett beslut kring.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Förväntat beteende
Går igenom ett exempel från vårdenheter i Ivard. 

1. Öppnar ett kort i listan – vårdenheten Capio Movement
2. Trycker på Ändra och byter namna till Capio Movement Halmstad
3. Byter sida med hjälp av pagineringen längst ner i listan
4. Får en dialog som frågar om jag vill spara. Alternativen är Avbryt, Släng ändringar och Spara
5. Väljer Avbryt och stannar kvar på sidan. 
6. Hittar listraden och ser över ändringarna - Sparar
7. Byter sida

### Faktiskt beteende
1. Öppnar ett kort i listan – vårdenheten Capio Movement
2. Trycker på Ändra och byter namna till Capio Movement Halmstad
3. Byter sida med hjälp av pagineringen längst ner i listan
4. Får en dialog som frågar om jag vill spara. Alternativen är Släng ändringar och Spara
5. Vet inte vad jag ska välja och hur jag ska hitta tillbaka.
Oavsett val så hamnar jag på den nya sidan.

**Comment by ralvesmartins** [comment]
Stänger denna story då samma problem beskrivs här: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/544
