### ISSUE TITLE
Underalternativ syns ej då sidan laddas om

### ISSUE THREAD

**Issue by brustablett** [Vastra-Gotalandsregionen/komponentkartan#395]
### Beskrivning
*När jag står på en sida som listas som ett underalternativ i menyn, ser jag inte markeringen (vilken sida jag står på) om jag laddar om sidan. Detta gör nämligen att menyn visas i kollapsat läge*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Steg för att påvisa problemet

- *Gå till en sida som listas som ett underalternativ i menyn.
- Ladda om sidan.*

### Förväntat beteende
*Den sektion som jag befinner mig i borde visas expanderad, så att jag ser vilken sida jag står på.*

**Comment by Jbraaf** [comment]
@brustablett vilken webbläsare gäller detta? Det funkar som förväntat hos mig på chrome

**Comment by brustablett** [comment]
Ok, jag använde också Chrome. Kanske problem i implementationen.. Jag kollade i Ivard

**Comment by brustablett** [comment]
Det berodde på en bugg i Angular – vi får tyvärr vänta in en uppdatering hos dem.

**Comment by AronssonFredrik** [comment]
Hej @brustablett,
Är detta fortfarande aktuellet?

Om jag exempelvis laddar följande sida, så ser jag att **Komponenter** är utfällt.
https://vastra-gotalandsregionen.github.io/komponentkartan-demo/card

Fredrik

**Comment by brustablett** [comment]
Hej, ja vi har fortfarande kvar problemet och vi har tidigare utrett om vi kunde lösa det, men jag förstod att det beror på en begränsning i Angular och vi kan följaktligen inte lösa det innan de fixar till vad-det-nu-var som var problem för oss. Ska se om jag har antecknat något mer i detalj. Liten video:
[https://www.dropbox.com/s/dq6vdeoccg9gxlo/%C3%96ppna%20menyn%20efter%20omladdning.mov?dl=0](url)

**Comment by brustablett** [comment]
Vi använder oss av en getter för att verifiera om man är inloggad.
Getter är bra djur.

**Comment by herrklaseen** [comment]
@athid 

Kan du undersöka om detta fortfarande är ett problem? Det beter sig okej i demo-appen men enligt exemplet https://www.dropbox.com/s/dq6vdeoccg9gxlo/%C3%96ppna%20menyn%20efter%20omladdning.mov?dl=0 så funkar det inte för dem. De har å andra sidan två nivåer ner, demo-appen har bara en.

**Comment by athid** [comment]
@herrklaseen jag skall kika på det, har fått en ny VGR burk nu och skall kolla om jag kan få access till lite andra system utöver vårdval. Återkommer när jag kikat på det.

**Comment by athid** [comment]
Problemet är kvar i iVard fortfarande.

**Comment by ralvesmartins** [comment]
Problemet kvarstår under Underhåll i Ivard 2021-09-09. Fungerar i övriga menyer.

**Comment by ralvesmartins** [comment]
@johanmartin7811 kan testa och se om det fungerar i komponentkartan

**Comment by johanmartin7811** [comment]
menyn visas i kollapsat läge om man går in på Action panel  och laddar om sidan ,  efter det visas menyn i expanderat läge när man laddat om sidan, i chrome, edge, firefox,

**Comment by synne1** [comment]
Har grottat lite i detta och hittade att det alltid är den översta undermenyn som inte funkar. Tror iaf jag hittat en förklaring till mysteriet. I submenu.component.ts hittade jag denna kodsnutt:

`    private setChildSelected(event: NavigationEnd) {
        const itemArray = this.menuItems.toArray();
        itemArray.splice(0, 1);`

Jag misstänker att det som idag kallas vgr-menu-separator tidigare kan ha varit ett menuItem och att man då har tagit bort den från arrayen. Kontentan nu är att den översta undermenyn inte markeras och expanderas.

Jag har testat att ta bort raden och då funkar det.

Däremot hittade jag att huvedmenyn inte får tillbaka fokusmarkeringen efter att man laddar om sidan. Det får undermenyn.

**Comment by synne1** [comment]
Hittade dok att vissa unermenyer inte funkade alls i Ivard även om de inte ligger överst och det beror på att 'path' i routingen inte verkar kunna innehålla specialtecken (åäö). Om man byter ut dessa tecken funkar det (förutom den översta i alla undermenyer då).  Möjligtvis kan det finnas andra lösningar på just den biten. Men det får vi undersöka.
