### ISSUE TITLE
<vgr-action-panel [showCloseButton]="false"> Krysset fortfarande klickbart.

### ISSUE THREAD

**Issue by kebarvid** [Vastra-Gotalandsregionen/komponentkartan#396]
### Beskrivning
La upp en action panel med [showCloseButton]="false" på och tänkte att det då inte skulle finnas någon stängknapp på panelen. Och den syns visserligen inte, men för man musen över där den borde vara så får man "klick-pekaren" på musen och man kan fortfarande klicka på knappen som stänger panelen. Det som händer är att man sätter opacity: 0 på den (via en angular-animation)

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: v.5.0.3
* Angular version: 7
* Browsers: Alla

### Steg för att påvisa problemet
Lägg in en action-panel med <vgr-action-panel [showCloseButton]="false">innehåll</vgr-action-panel> och se att det finns en osynlig knapp i övre högra hörnet.

### Förväntat beteende
Det borde inte finnas någon stäng-knapp.

### Faktiskt beteende
Du kan stänga rutan med den "osynliga" knappen

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by AronssonFredrik** [comment]
Hej Arvid,
Detta är nu fixat och uppdaterat i 6.0.0-rc8 och framåt.

Exempel utan kryss.
1. Öppna https://vastra-gotalandsregionen.github.io/komponentkartan-demo/listexample-notifications
2. Klicka på "Öppna panel".
✔️ Öppnad panel ska inte innehålla ett kryss och ytan ska inte vara klickbar.

Exempel med kryss
1. Öppna https://vastra-gotalandsregionen.github.io/komponentkartan-demo/actionPanels
2. Klicka "Öppna panel 1".
✔️ Öppnad panel ska innehålla ett klickbart kryss.
