### ISSUE TITLE
Datepicker Calendar Överlappar varandra

### ISSUE THREAD

**Issue by anumatanna** [Vastra-Gotalandsregionen/komponentkartan#397]
### Beskrivning
Om man tar kalender i olika följder (exempelvis Månad före Dag) så överlappar dem varandra. Detta händer när man klickar i _calendar-alt_   ikonen. 
 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 5.0.3
* Angular version: 7.0.4
* Browsers: Chrome, IE, Edge

### Steg för att påvisa problemet
*Beskriv vad du förväntar dig skall hända*
1. Gå till komponentkartan
2. Gå till fliken "Komponenter" och klicka dig fram till "Datepicker"
3. Klicka på kalender-ikonen för "Månad"
4. Därefter klicka på ikonen för "Dag"

### Förväntat beteende
Kalender skall ej överlappa varandra.

### Faktiskt beteende
Kalenderna överlappar varandra.

### Övrig information, kodexempel och motivering till förändring
Som användare hade jag velat att "Månad"-kalendern stängde ner sig när jag klickar på "Dag"-kalendern.

### Skärmdumpar mm
![DatePickerOverlapseBug1](https://user-images.githubusercontent.com/54441775/65221461-61714c80-dabd-11e9-915f-989626d1eb66.PNG)
![DatePickerOverlapse2](https://user-images.githubusercontent.com/54441775/65221535-836acf00-dabd-11e9-9896-1d48f5be990c.PNG)

**Comment by AronssonFredrik** [comment]
@anumatanna ,
Detta ska vara fixat sedan version 5.1.3.

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/datepicker

**Comment by AronssonFredrik** [comment]
@anumatanna ,
Detta ska vara fixat sedan version 5.1.3.

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/datepicker
