### ISSUE TITLE
Komponent Dropdown select - Fokus är inte på vald alternativ när man öppnar dropdown

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#399]
### Beskrivning
*Fokus är inte på vald alternativ i dropdown "Stor, många alternativ".*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** 5.1.0-beta8, Angular: 7.1.0 och Angular-Cli: 7.3.9**
* Angular version: **version**
* Browsers: **Chrome**

### Steg för att påvisa problemet
*1. Tryck på "komponenter->Dropdown select"
2. Tryck på "Stor, många alternativ"
3. Välj en användare långt ner i listan tex "Gunilla"
4. Tryck på dropdown igen för att öppna*

### Förväntat beteende
*fokus är på "Gunilla"*

### Faktiskt beteende
*Fokus är på översta delen i listan
![komponentkartaDropdown](https://user-images.githubusercontent.com/33692196/67845120-38ea6280-faff-11e9-8f21-ff3436684a8b.PNG)
*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by AronssonFredrik** [comment]
Hej @maddefinlof ,
Skulle vi kunna kika på denna issue, vi har nämligen inte kvar den dropdown som syftas på.

Fredrik

**Comment by herrklaseen** [comment]
@athid Jah har testat hur den nya dropdown select komponenten funkar och det man kan härleda till den här issuen är att om ett alternativ långt ner i listan är valt skrollar dropdownen _inte_ till det alternativet när man valt och klickar igen. Det finns ingen indikering på vilket alternativ som är i "fokus". 

Är det fortfarande aktuellt att kolla på det här ärendet? I så fall behöver vi omformulera det så att det blir ett förbättringsförslag.
