### ISSUE TITLE
[Menu] Felmarkering av aktuell öppen

### ISSUE THREAD

**Issue by AronssonFredrik** [Vastra-Gotalandsregionen/komponentkartan#411]
### Beskrivning
Vid arbete av #408, ändra vi `[routerLinkActiveOptions]="{exact:false}"`, vilket har lett till att tabbar som inte är öppna är markerade öppna. (Se exempel nedan där både Start och Sidhantering är markerade som öppna).

Lösningsförslag:
1. Hantering om routerLink ska vara exact eller ej.
2. Ändra url av start till "/start" eller liknande

### Typ av ärende (kryssa i en med "x")
- [x] Bugg

### Din miljö
* vgr-komponentkartan version: 6.0.0-rc4, 
* Angular: 8.2.14 och Angular-Cli: 8.3.19
* Chrome 78.0.3

### Steg för att påvisa problemet
1. Öppna https://vastra-gotalandsregionen.github.io/komponentkartan-demo/theming

### Förväntat beteende
Bara Temahantering ska vara markerat som öppnat

### Faktiskt beteende
Både Start och Sidhantering är markerade som öppna

### Skärmdumpar mm
Både Start och Sidhantering är markerade som öppna
![image](https://user-images.githubusercontent.com/25684632/69786015-d8138000-11b9-11ea-8d27-9b48dce13c69.png)

**Comment by ralvesmartins** [comment]
Undersök om denna bugg bara finns i Komponentkartan demo
