### ISSUE TITLE
list-item_header_wrapper animeringen beter inte som förväntat.

### ISSUE THREAD

**Issue by annaanumat** [Vastra-Gotalandsregionen/komponentkartan#414]
### Beskrivning
list-item_header_wrapper animeringen beter inte som förväntat.

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 6.0
* Angular version: 8.2.14
* Browsers: Chrome, edge, IE

### Steg för att påvisa problemet
Demo sidan: https://vastra-gotalandsregionen.github.io/komponentkartan-demo/listexample-notifications

Future branch:
1. Gå till fliken **Komponentkartan/Exempelsidor/"Lista med kort" 
2. Öppna ett av objekten i listan

### Förväntat beteende
Animeringen vid stängning beter sig inte som förväntat

### Faktiskt beteende
list-item_header_wrapper stängs normalt/ den blåa inramningen skall försvinna samtidigt.

### Skärmdumpar mm
![headerwrap](https://user-images.githubusercontent.com/48483336/72248336-332cf500-35f7-11ea-8fcd-93e68bbd27f5.PNG)

**Comment by AronssonFredrik** [comment]
Hej Anna,
Med release av komponentkartan 6.0.0 så är detta löst.

Värt att notera att `vgr-list` är deprecated och man bör överväga att byta till `vgr-grid`.

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/listexample-notifications

Mvh,
Fredrik
