### ISSUE TITLE
Lägg exempelsida för Gridden

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#418]
### Beskrivning
*Finns ingen exempelsida för grid (Har funnits tidigare).*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x ] Förbättringsförslag

**Comment by AronssonFredrik** [comment]
@synne1, har du tid att sitta med detta? Eller åtminstone tid att anteckna vad vi vill visa på som exempel.

**Comment by synne1** [comment]
Exempelsidorna som jag refererar till finns i komponentkartan (app) men inte på demo (har för mig att de funnit där förut men jag kan ha fel). Kanske vi kan diskuterar detta på nästa möte?
