### ISSUE TITLE
ngx-perfect-scrollbar har nått end of life

### ISSUE THREAD

**Issue by herrklaseen** [Vastra-Gotalandsregionen/komponentkartan#435]
### Beskrivning
https://github.com/zefoy/ngx-perfect-scrollbar#eol-notice

### Typ av ärende (kryssa i en med "x")
- Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.3.6**
* Angular version: **9.1.2**
* Browsers: **Alla**

### Övrig information, kodexempel och motivering till förändring
När utvecklaren bakom ngx-perfect-scrollbar slutar uppdatera kommer vi inte kunna uppgradera dess dependencies vilket kan leda till säkerhetsproblem och försämrad funktionalitet. 

Förslagsvis migrerar vi till https://github.com/MurhafSousli/ngx-scrollbar eftersom utvecklaren av ngx-perfect-scrollbar rekommenderar det. 

På teknikmöte 2020-10-16 beslutades att vi migrerar till ngx-perfect-scrollbar eftersom det antagligen är minst påverkan. 
Det finns risk att denna nya scrollbar kräver nyare Angular, så denna story bundlas med #438

**Comment by AronssonFredrik** [comment]
Vi har en story i pivotal där vi diskuterat kring att gå ifrån perfect-scrollbar eftersom vi vill minska användandet av tredjepartsprodukter.

**Comment by athid** [comment]
Det finns ju som vi diskuterade på teknikmötet två vägar; 
1. Använda ngx-scrollbar.
2. Skippa 3:e part helt, det får då en visuell betydelse eftersom varje browser renderar olika scrollbars som dessutom är olika breda och således kan leda till layoutproblem då det är ont om plats i vissa vyer.

**Comment by athid** [comment]
Ämnet diskuterades på designmötet, och det finns ingen som kräver ett visst utseende eller att det är samma mellan olika browsers. Så valet om man skall köra native eller en 3:e part får helt enkelt fattas utifrån hur svårt/lätt det blir att supporta olika browsers och hur mycket kod-undrhåll det krävs.

**Comment by athid** [comment]
när vi drog in denna i implementation så upptäcktes att ngx-scrollbar inte stödjer IE, så vi får dra in den till ritbordet igen och se om vi kan hitta en annan lösning.

**Comment by ralvesmartins** [comment]
Vi kommer inte att stödja IE och kan därmed migrera till ngx-scrollbar
