### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#440]
### Beskrivning
*Beskriv ärendet här. Var så utförlig som möjligt.*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

I flera fall i våra system behöver användarna välja ett alternativ från en lång lista med möjliga val där de ofta vet vad de vill välja. I det här fallet skulle en combobox snabba upp interaktionen avsevärt eftersom man kan skriva in det önskade valet. I vissa fall behöver vi också tillåta att man får skriva in alternativ som inte finns i den fördefinierade listan. 

Vi utgår från den här beskrivningen för kraven relaterat till WCAG för **combobox**: https://www.w3.org/TR/wai-aria-practices/#combobox
Vi vill satsa på exempel 3 på den här sidan: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
Listbox: https://www.w3.org/TR/wai-aria-practices/#Listbox
´

-----------------
# KRAV

## Komponentens delar
* Comboboxen består av ett textfält och en listbox. **Förslagsvis används de komponenter som vi redan har för att skapa comboboxen. Är det möjligt?**
  * Styling samma som Input och Dropdown select (listbox):
  * Markering för hover ser ut som i dropdown select
  * **NY** Det alternativ som är valt markeras med en bakgrundsfärg, temats dimmade färg. Se bild i kommentar nedan.
* Default finns en knapp för att fälla ut listan med alternativ. Knappen ser ut som den som används i dropdown select.
* Det går att välja bort knappen.
* Comboboxen kan justeras i bredd på samma sätt som komponenten Input (två fördefinierade bredder och möjlighet att sätta valfri bredd)
* Alternativen kan ta upp mer än en rad likt i dropdown select
* Default finns ingen text i textfältet (till skillnad från dropdown där det står "Välj"). 
* Listboxen är automatiskt positionerad för att undvika att den visas utanför sidan. Default är att den linjerar till vänster om det finns plats. (ersätter/hänger ihop med #163554364) (Om det är för komplicerat borde man istället få välja vilken sida av textfältet som listboxen ska linjera med, default vänster.
* Skall fungera i IE och Edge, samt chrome. (IE gäller året ut (2021) för bland annat vårdval).

### Välja alternativ med autoselect
När textfältet får fokus kan förslag (autocomplete) börja visas på tre sätt:
1. Användaren börjar skriva och listboxen öppnas. De alternativ som stämmer med texten i textfältet visas och det översta resultatet blir valt. Om det inte finns något alternativ som matchar texten visas inte listboxen. 
  *  I textfältet syns hela det alternativet som kommer att bli valt med en highlight på den del av alternativet som användaren ännu inte skrivit in (se bild). Markeringens färg styrs av OS:et (?)
2. Användaren trycker pil ner (eller pil upp) vilket öppnar listboxen och första alternativet (eller sista) blir valt.
3. Användaren trycker på knappen med pil på vilket öppnar listbox och första alternativet blir valt.
****
* Touch-ytan är hela hover-markeringen, man måste inte trycka på själva texten
* Det går inte att stänga listbox med knappen (eftersom vi vill ha autocomplete = en lista med förslag). 
* När ett alternativ är valt kan man "avvälja" genom att ta bort texten i textfältet
* Om användaren skriver in mer i rutan efter att ett val gjorts kommer det att raderas när man går vidare. Det går bara att välja ett alternativ.

### Tangentbordsnavigation
**Navigera till komponenten**
*Tab*
Comboboxen fokuseras med tab. I detta fall är det själva textfältet som får fokus. Knappen (om den finns) är inte en del i tabordningen. Man kan inte nå den med tangentbordet utan den öppnas med muspekaren. 

**När textfältet har fokus**
*Pil ner*
Flyttar fokus till listan men jag kan fortsätta skriva i textfältet (se exempel 3, länk ovan) och fältet har fortfarande visuellt fokus också. När fokus flyttas till listboxen blir det första alternativet blir valt. Är det redan något valt flyttas markeringen och därmed även valet till nästa alternativ i listan. 

*Pil upp*
Beter sig som pil upp men man hamnar på det sista alternativet i listan om man startade i textfältet.

*Escape*
Rensar textfältet men fokus är kvar i textfältet så jag kan direkt skriva igen. Listboxen stängs. 

*Enter*
Väljer det val som är markerat (om användaren inte skrivit klart) och stänger listboxen. Fokus är kvar på textfältet. Inmatningsmarkören hamnar bakom det valda alternativet.

*Teckentangenter (printable characters)*
Alla tecken tillåts. Det går att begränsa i implementationen men komponenten ska default tillåta alla. 

*Alt + pil ner*
Om listbox är tillgänglig men inte visas så öppnas listboxen utan att flytta fokus.

*Alt + pil upp*
Om listbox visas och har fokus flyttas fokus till textfältet. Om listbox visas med inte har fokus stängs den. 

*Tab*
Stänger listan och flyttar fokus till nästa komponent i tabordningen

*Standardknappar för textredigering (standard single line text editing keys)*
* Inkludera tangenter för inmatning, markörens rörelse, markering och textmanipulation. Ska följa standard för web, jag tror att det är följande:
  * Inmatning: teckentangenter, space
  * markörens rörelse och markering: pil upp och pil ner för att navigera mellan alternativ,  markera texten med Shift + pil höger/vänster, hoppa till start/slut av ord med Alt + pil vänster/höger, pil höger och pil vänster för att flytta markören i ordet som skrivs
  * textmanipulation: ta bort inmatning med Backspace
* Standardnyckeltilldelningar för redigeringsfunktioner beror på enhetens operativsystem (är detta samma som innan?)

Klipper in texten här:
NOTE: Standard single line text editing keys appropriate for the device platform:
1. Include keys for input, cursor movement, selection, and text manipulation.
2. Standard key assignments for editing functions depend on the device operating system.
3. The most robust approach for providing text editing functions is to rely on browsers, which supply them for HTML inputs with type text and for elements with the contenteditable HTML attribute.
4. IMPORTANT: Be sure that JavaScript does not interfere with browser-provided text editing functions by capturing key events for the keys used to perform them.

**När listboxen har focus**
*Enter*
Väljer det val som är markerat (om användaren inte skrivit klart) och stänger listboxen. Fokus är kvar på textfältet. Inmatningsmarkören hamnar bakom det valda alternativet.

*Escape*
Rensar textfältet men fokus är kvar i textfältet så jag kan direkt skriva igen. Listboxen stängs. 

*Pil höger*
Flyttar fokus till textfältet utan att stänga listboxen och flyttar inmatningsmarkören ett tecken till höger. Om inmatningsmarkören är vid det tecken som är längst till höger flyttas inte markören.

*Pil vänster*
Flyttar fokus till textfältet utan att stänga listboxen och flyttar inmatningsmarkören ett tecken till vänster. Om inmatningsmarkören är vid det tecken som är längst till vänster flyttas inte markören.

*Teckentangenter*
Flyttar fokus till textfältet utan att stänga listboxen och skriver ut tecknet.

*Backspace*
Flyttar fokus till textfältet och tar bort tecknet som är innan inmatningsmarkören.

*Delete*
Flyttar fokus till textfältet, tar bort valt läge om ett alternativ var valt och tar bort den del av text in textfältet som är inline autocomplete (den highlightade delen).

*Pil ner* 
Flyttar fokus till nästa alternativ och väljer det. Om fokus är på sista alternativet händer ingenting.

*Pil upp* 
Flyttar fokus till föregående alternativ och väljer det. Om fokus är på det första alternativet händer ingenting.

*Home*
Antingen flyttas fokus till det första alternativet (som visas nu) i listboxen och det väljs eller så flyttas fokus till textfältet och inmatningsmarkören placeras vid det första tecknet som skrivits in. **Alternativ 1?**

*End*
Antingen flyttas fokus till det sista alternativet (som visas nu) i listboxen eller så flyttas fokus till textfältet och inmatningsmarkören placeras vid det sista tecknet som skrivits in. **Alternativ 1?**

#### WAI-ARIA roles, states and propteries
Kopierar in från https://www.w3.org/TR/wai-aria-practices/#combobox
Utgår från mönster för ARIA 1.1.

* Elementet som agerar combobox har rollen combobox (https://www.w3.org/TR/wai-aria-1.1/#combobox)
* Textfältet i comboboxen har rollen textbox (har vår input det eller searchbox?)
* Listboxen i comboboxen har rollen listbox
* Listbox och textfält följer ARIA-mönstren för respektive roll
* När listboxen visas ska textboxen ha aria-controls satta till ett värde som refererar till comboboxens listbox 
* Textfältet har värdet för aria-multiline satt till false, alltså endast single line inmatning accepteras (ok lösning?)
* När listboxen inte visas har comboboxen aria-expanded satt till false. När den visas ändras aria-expanded till true. Default är false.
* När comboboxen får fokus placeras DOM-fokus på textfältet
* När ett alternativ i listboxen har fokus är DOM-fokus kvar på textfältet som har aria-activedescendant satt till ett värde som refererar till det fokuserade alternativet i listboxen. 
* När ett föreslaget värde visas som det valda värdet (inline autocomplete?) har alternativet i listboxen aria-selected = true.
* Om comboboxen har en synlig rubrik (etikett) har comboboxen aria-labelledby satt till ett värde som refererar till rubriken. Annars har comboboxen en osynlig rubrik som sätts via aria-label.
* Textfältet har aria-autocomplete satt till both:
  * När listboxen öppnas visas föreslagna alternativ som kompletterar eller logiskt motsvarar tecknen som är skrivna i textfältet. Dessutom visas den del av det valda alternativet som inte ännu matats in av användaren, en så kallad completion string, bakom inmatningsmarkören i textfältet och den är visuellt urskiljbar och har ett selected state.

### Skärmläsare
* Skärmläsare läser upp en rubrik för comboboxen, antingen den rubrik som visas (aria-labelledby) eller den som definierats med aria-label
* Skärmläsaren läser alternativets text, dess status (valt, inte valt) och dess position i listan, respektive totalt antal "X av Y".
Tror att kraven för skärmläsare löses av att man följer ARIA-mönstren. **Behöver speca mer här?**
* Om ett felmeddelande visas ska skärmläsaren kunna läsa upp att det är ett felmeddelande och felmeddelandets text.
* det verkar som att chromevox läser våra dropdowns som lista med noll objekt, ska det vara så? borde kunna höra antal val när jag står på den

### Felmeddelande
* Det går att definiera eget felmeddelande för combobox
* Det går att ha flera felmeddelanden för combobox men att ett visas åt gången(ex, otillåten kombination och obligatorisk)
* Om man skriver in ett otillåtet alternativ ska ett felmeddelande visas. Texten bör definieras för varje fall så att den passar in i den givna kontexten. Default är texten, **XX?**
* Felmeddelandet ska ha samma styling som befintliga felmeddelanden

**Comment by louisebroo** [comment]
@athid Storyn är spelad i Ivards backlog och kommer att planeras in för implementation. Jag har flyttat den till version 8. Vi ser även att man på sikt skulle vilja komplettera med en annan konfiguration av comboboxen. Den här varianten är ju en autocomplete men vi ser även ett behov av att kunna använda combox för att lägga till alternativ, likt när man lägger till taggar på en story i Pivotal Tracker. Vi tror att det är en relativt enkel grej att lägga till en ny konfiguration som då inte skulle behöva leda till en breaking change. Jag kommer skriva en ny issue för den konfigurationen. För Ivards räkning är det viktigast att få autocomplete på plats för det kommer användas på flera ställen men vi har ett ställe där vi behöver tillåta custom values.

**Comment by louisebroo** [comment]
![Combobox med autocomplete](https://user-images.githubusercontent.com/35460884/112291553-7faaa080-8c90-11eb-9efe-9e70677fefba.png)

**Comment by ralvesmartins** [comment]
Tog bort kraven: 
* Det är valbart om man ska tillåta att användaren skriver in något annat än det som finns i listan med förslag. Default är att man bara får välja alternativ från listan. 
* Om man tillåter andra alternativ och användaren skriver in ett alternativ som inte finns i listan, läggs alternativet till i listboxen temporärt för att göra det valbart om användaren råkar radera. Det tas bort när listboxen stängts? **Detta känns svårt att göra tydligt, kanske bättre att det hålls utanför listboxen?**

Skapa som en ny story med dessa krav om behovet uppstår senare.

**Comment by johanmartin7811** [comment]
@synne1 @kinbode @alphaPlusPlus                                                                                                                                                    
 •	**Hoppa till start/slut av ord med Alt + pil vänster/höger**
•	Faktiskt resultat: byter till sidan du besökte innan, och tillbaka till sidan du var på.
•	Eller till tab-button sidan i komponentkartn

•	**Escape: Rensar textfältet men fokus är kvar i textfältet så jag kan direkt skriva igen. Listboxen stängs.**
•	Faktiskt resultat: rensar när man skriver första gången,  Har man redan skrivit och valt ett val innan, kommer det valet tillbaka när man trycker på ESC.

•	**Läser inte upp meddelandet under Reactive när man använder skärmläsaren, skall det göra eller gäller det ba**ra felmeddelanden man får när man skriver. Bygger på annan US som än inte är gjord: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/451
