### ISSUE TITLE
Enter gör sökning i dropdown select då den är stängd och har fokus

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#441]
### Beskrivning
Om man försöker öppna dropdown select då den har fokus med enter (då komponenten är i sitt grundstate (ej tidigare interagerad med) och den är av typen multiselect).

Så kommer komponenten aktivera "markera alla sökträffar", och således markera alla val direkt.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
Fokusera dig fram till en dropdown select (som är av typen multiselect, med fler än 30 val, som inte har något val gjort) med tab. 
Öppna upp den med enter. 
Dropdown öppnas och alla val markeras.

Exempel där man kan prova i en skarp klient, vårdval, utbetalningsunderlag.

Det sker alltid i IE/Edge, och i vissa fall kan det även ske i chrome.

### Förväntat beteende
Dropdown select skall bara öppnas, enter skall inte bubbla vidare och aktivera val eller sökfält inne i dropdown selecten.

### Faktiskt beteende
Enter bubblar igenom och aktiverar saker.

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by athid** [comment]
En tanke är väl om man ens skall kunna trycka enter på en tom sökbox, kanske skall man inte visa texten eller tillåta enter då inget är skrivet i fältet.

**Comment by kebarvid** [comment]
Skall inte längre markera några rutor när man öppnar den.

Går att testa antingen genom att checka ut branchen `feature/dropdown-fixes` i komponentkartan repot eller installera npm paketet `vgr-komponentkartan@7.8.1-beta1` i ens lokala projekt.

**Comment by erfham** [comment]
Test ok.
