### ISSUE TITLE
MenuItem redirectar till "/" även om ingen path angivits

### ISSUE THREAD

**Issue by jvholmberg** [Vastra-Gotalandsregionen/komponentkartan#445]
### Beskrivning

Om man skapar ett MenuItem utan länk pga man vill koppla säg en action istället (typ öppna modal) så skapas ändå en länk.
Och denna länken går till "/" vid klick, så både länken och klick actionen triggas. Försöker man aktivera den med mellanslag/enter så får man ett fel i konsolen. Säger man att det är en extern länk så kommer allt att fungera förutom aktiveringen med mellanslag/enter.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.4.0**
* Angular version: **9.1.9**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet

Skapa ett MenuItem likt nedanstående.
<vgr-menu-item text="Foobar" (click)="foobar()"></vgr-menu-item>

### Förväntat beteende

foobar() skall anropas men ingen redirect ske.
Jag vill kunna exekvera foobar både med klick men även med mellanslag, enter ...

### Faktiskt beteende
Klick resulterar till att man redirectas till "/" och foobar() exekveras.
Inget händer när man använder mellanslag eller enter förutom ett felmeddelande som visas i konsolen.

### Övrig information, kodexempel och motivering till förändring

Det går att få bort själva redirecten genom att sätta "isInternalLink" till "false" men problemet med tangentbordet kvarstår och det känns lite som ett hack.

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by louisebroo** [comment]
Att kunna navigera med tangentbordet är ett WCAG-krav, så vi behöver verkligen tillåta att man kan navigera eller aktivera en action med hjälp av enter eller mellanslag.

**Comment by erfham** [comment]
Test OK.
