### ISSUE TITLE
Modal - Stänga med klick utanför modalen (backdrop)

### ISSUE THREAD

**Issue by jvholmberg** [Vastra-Gotalandsregionen/komponentkartan#446]
### Beskrivning
Jag vill kunna stänga modalen genom att klicka på backdropen/utanför modalen.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **7.4.0**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
Öppna en modal klicka sedan utanför modalen

### Förväntat beteende
Modalen skall stängas

### Faktiskt beteende
Inget händer

### Övrig information, kodexempel och motivering till förändring
Gör att modalen känns mindre intrusive

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by erfham** [comment]
Test OK.
