### ISSUE TITLE
Gruppering och validering av checkboxar

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#448]
### Beskrivning
Skapa en gruppering av checkboxar samt möjliggör validering av denna.
Detta behövs i formulär när det finns en grupp (oftast) av checkboxar som man måste markera minst en av. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Det går att sätta valideringskriterier för en eller en grupp av checkboxar. Om kriterierna inte uppfylls visas ett valideringsmeddelande 
* Valideringen visas när man navigerat förbi komponenten utan att markera något alternativ eller när man försöker skicka in formuläret utan att markera något alternativ. Det går att välja vilket av alternativen som ska gälla.
* Valideringen släcks när valideringskriterierna är uppfyllda
* Valideringen visas som en ram runt checkboxen, eller gruppen av checkboxar, tillsammans med en ikon (exclamation circle solid) och en text.
* Ramens bredd är minst så stor så att det får plats att skriva obligatoriskt (min-width: 115px), men den ska växa med radiobuttons text
* Texten i valideringsmeddelanden har textstyle "body" (16px)
* Säkerställ att checkbox uppdaterar formControl om man klickar på själva checkboxen.*.  

Kommentar från tidigare bugg: Checkbox uppdaterar inte formControl om man klickar på själva checkboxen. Om man klickar på texten eller använder tangentbordet fungerar det normalt. Problemet verkar bara uppstå om formuläret har updateon 'blur' eller 'submit '*.  

### Skärmdumpar mm
![image](https://user-images.githubusercontent.com/35460884/92743398-cbdf6480-f380-11ea-9804-c163d430a132.png)

WCAG: https://www.w3.org/WAI/tutorials/forms/grouping/

**Comment by CrestTheFury** [comment]
@louisebroo 
Idag har vi ingen gruppering på checkboxar men däremot på radiobuttons.
Frågan är om man skall bryta isär denna i två delar 
1. Sätta validering på radiobuttongroup **(effort: small)**
2. Skapa en gruppering av checkboxar samt möjliggöra validering av denna **(effort: medium)**
Fråga på 2:an =>  Om man validerar på en checkbox och den ligger i en grupp, skall du gruppen valideras eller endast den enskilda checkboxen?

**Comment by louisebroo** [comment]
@CrestTheFury Jag skulle vilja bolla över detta till Rebecka som är ny PO. Spontant låter det väl klokt att dela upp i två. Angående din fråga så är jag lite osäker på om jag förstår. När skulle man vilja validera bara på en checkbox i en grupp? Har du något exempel?

**Comment by ralvesmartins** [comment]
Rebecka ska diskutera detta med Synnöve

**Comment by CrestTheFury** [comment]
Release in 9.1.0
