### ISSUE TITLE
Validering av radiogroup

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#449]
### Beskrivning
Det saknas validering på radiogroups. Detta behövs i formulär när det finns en radio group som är obligatorisk. Best practise för radio groups är att inte ha något alternativ förvalt för att användaren inte ska råka missa den frågan, men det bygger ju på att vi kan märka ut att det inte blivit något valt.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Det går att sätta valideringskriterier för en radriogroup (att ett val krävs).
* Valideringen visas när man navigerat förbi komponenten utan att markera något alternativ eller när man försöker skicka in formuläret utan att markera något alternativ. Det går att välja vilket av alternativen som ska gälla.
* Valideringen släcks när valideringskriterierna är uppfyllda
* Valideringen visas som en ram runt radiogroupen tillsammans med en ikon (exclamation circle solid) och en text.
* Ramens bredd är minst så stor så att det får plats att skriva obligatoriskt (min-width: 115px), men den ska växa med radiobuttons text
* Texten i valideringsmeddelanden har textstyle "body" (16px)

### Skärmdumpar mm
![image](https://user-images.githubusercontent.com/35460884/92743398-cbdf6480-f380-11ea-9804-c163d430a132.png)

WCAG: https://www.w3.org/WAI/tutorials/forms/grouping/

**Comment by ralvesmartins** [comment]
Rebecka ska diskutera detta med Synnöve

**Comment by maddefinlof** [comment]
Test ok

**Comment by CrestTheFury** [comment]
Release in 9.1.0
