### ISSUE TITLE
Ny gråskala => uppdaterad styling på komponenter

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#454]
### Beskrivning
Det finns en uppsjö av gråa nyanser i vårt designsystem och vi vill städa upp så att det blir rent och städat. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Det finns fyra grå toner i Komponentkartan: dark, primary, secondary och dimmed
  * Dark # 717474
  * Primary # 9EA2A2
  * Secondary # BBBEBE
  * Dimmed # EAEBEB
* Det finns en text style som heter placeholder (i body och small) som har den grå färgen Dark
* Komponenter som innehåller placeholder text har uppdaterats med den nya färgen. 
  * Dessa är: datepicker, input och text area.
* Separator i dropdown-lista, är nu # 979797, byt till grey-primary 
* Scroll har kulör primary i det neutrala temat med 30 % opacity (i designfilen), vad har den i koden? Förslag att byta till grey-secondary
* Linjen längst ner i vgr-header är i neutrala temats sekundära nyans nu. Förslag att den antingen ska ändras med tema (sekundär i temat)
* Separator i action-panel är neutrala temats sekundära nyans, byt till grey-primary 
* Ramen till panel-dashboard är neutrala temats sekundära nyans, byt till grey-primary 
* Separator i menyn är nu i # DBDBDB, byt till antingen grey-secondary eller grey-dimmed. Den kulör som är nu är mitt emellan dem... Föreslår grey-secondary för tydlig kontrast när den är så tunn. Samma borde gälla för separator i header-menu (om den har en sån?)
  * Menyn har också en linje i höger kant, den är neutrala sekundära. Byt till grey-primary
* Uppdaterad dokumentation på demo-sidan: https://vastra-gotalandsregionen.github.io/komponentkartan-demo/colours 

![image](https://user-images.githubusercontent.com/35460884/92749419-5ffffa80-f386-11ea-8472-d454794aa13b.png)

**Comment by CrestTheFury** [comment]
@louisebroo 
Vi saknar gray-ultradimmed i denna story, men antar att den är en del av den gråa collectionen?

Finns även fler färger (bla. fokusfärgen) som inte stämmer överens mellan wikin och komponentkartan, skall det till fler stories för att rätta upp även dessa?

**Comment by CrestTheFury** [comment]
Innan man implementerar: 
Sofia har redan implementerat 3 av 5 gråa toner som finns definierade i Wiki'n. Dessa finns i _settings.colors.scss. De behöver även läggas till i komponentkartan-demo

**Comment by louisebroo** [comment]
@CrestTheFury Jag antar att den också borde läggas till här. Det är Anders som har tagit fram den så jag är osäker på tanken med den. Finns den redan med bland färgerna i koden? Finns den med i någon komponent eller behöver vi lägga till det i den här storyn?

Angående andra färger så vet jag inte riktigt hur jag ska svara, det beror på vilka färger det är du menar. När jag kollar färgkoden som står på demo-kartan och i wikin så står samma HEX-kod så jag är osäker på var det skiljer sig. Vilka färger är det som skiljer sig?
