### ISSUE TITLE
Dropdown select med bara ett val => readonly

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#455]
Fråga från refinement 25/11: Borde dessa fall lösas genom att alltid ha valet "Ingen" eller dylikt för att även vara mer förståelig för användaren?
Kommentar från refinement 09/12: Är inte så önskevärt att låsa in det i komponenten, utan implementatören bör bygga det från fall till fall.
### Beskrivning
Ibland används dropdowns för att välja mellan alternativ som dynamiskt ändras. Ofta är det baserat på användarens behörighet. Om användaren bara får se ett alternativ finns ingen anledning att visa dropdown i sitt aktiva state eftersom det kan få användaren att tro att hen kan ändra något. Därför bör dropdown select alltid övergå till readonly om det bara finns ett alternativ.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Om det bara finns ett valbart alternativ i en dropdown select visas den med det valda alternativet i readonly-läge.
* Undantag: om dropdownen inte är obligatorisk att fylla i ska den istället visas i active-läget och med knappen Ta bort val tillgänglig.

**Comment by ralvesmartins** [comment]
Behöver testa i alla system så att det ser bra ut efter uppdateringen innan det släpps

**Comment by TorinWilliams** [comment]
Se kommentarer längst upp i storyn:

Fråga från refinement 25/11: Borde dessa fall lösas genom att alltid ha valet "Ingen" eller dylikt för att även vara mer förståelig för användaren?
Kommentar från refinement 09/12: Är inte så önskevärt att låsa in det i komponenten, utan implementatören bör bygga det från fall till fall.
