### ISSUE TITLE
Radiobutton ska skala rätt när man zoomar

### ISSUE THREAD

**Issue by ghost** [Vastra-Gotalandsregionen/komponentkartan#457]
### Beskrivning
När man zoomar ut skalar radiobutton konstigt, den runda formen blir oval och pricken hamnar inte centrerat. Det funkar att zooma in upp till 200 % innan den börjar se konstig ut vilket uppfyller WCAG-kravet men jag tycker att det borde gå att zooma ut också för de som vill kunna få bättre överblick.

Denna bör byggas tillsammans med #443

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.3.8**
* Angular version: **9.1.7**
* Browsers: **Chrome**

### Steg för att påvisa problemet
* Zooma sidan mer än 200 %

### Förväntat beteende
* Radiobutton behåller sin form (cirkel och inte oval) när man zoomar. Pricken i radiobutton är alltid centrerad

### Faktiskt beteende
När man zoomar ut skalar radiobutton konstigt, den runda formen blir oval och pricken hamnar inte centrerat.

**Comment by aljlo2** [comment]
Efter analys har vi bestämt att denna inte kommer att göras då sättet vi bygger upp vår radiobutton på hade krävt för mycket arbete att göras om för en såpass liten "bugg". Dessutom är det bara i vissa "ut-zoomade"-lägen då detta sker.

**Comment by CrestTheFury** [comment]
Åtgärdad i samband med omskrivingen av radiobuttongroup (9.1.0)
