### ISSUE TITLE
Möjlighet att fokusera allt innehåll för uppläsning

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#458]
### Beskrivning
För att något ska läsas av skärmläsaren så behöver det kunna fokuseras. Vi behöver en strategi för att innehåll ska bli nåbart på sidorna.
Fokusmarkeringen ska kunna användas på allt som man kan tabba till.
Hur ska focus bete sig på texter etc? Allt som läsaren kan läsa upp är det som man kan fokusera.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Det finns en metod för att fokusera på varje komponent.
* Alla komponenter är uppdaterade med API beskrivning för hur man sätter fokus

**Comment by ralvesmartins** [comment]
En fokusmetod är implementerad, så vi kan manuellt (programmatiskt) sätta fokus på alla komponenter.
