### ISSUE TITLE
Fokus hamnar på osynligt ställe när man navigerar från en tom datepicker till ett stängt kort

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#465]
### Beskrivning
När datepickern blir tom (man rensar datumet) och man tabbar till eller klickar på annan komponent släpper fokus visuellt från datepickern men man måste tabba/trycka en gång till för att det man försöker navigera till ska få fokus. Det verkar som att det som fokuseras vid första klick/tabb är osynligt.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.3.8**
* Angular version: **9.1.7**
* Browsers: **Chrome**

### Steg för att påvisa problemet

- Gå till https://vastra-gotalandsregionen.github.io/komponentkartan-demo/datepicker
- Ställ dig i datepickern
- Tabba

### Förväntat beteende
- Fokus flyttas till nästa element i tabordningen och är synligt

### Faktiskt beteende
- Fokus flyttas till nästa element men listitem (grid? card? va ni nu kallar det) öppnas inte så jag ser inte var jag är

**Comment by ralvesmartins** [comment]
Kan inte reproducera i Chrome 31/8 2021
