### ISSUE TITLE
Ändra om CSS-hanteringen till att använda Angular Component Styles

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#468]
### Beskrivning
Det rekomenderade* sättet att jobba med css för komponenter i angular är att css-filerna ligger med "bundlade" med komponenten. När komponentkartan skapades hanterades CSS på ett annat sätt.

Den stora skilnaden mellan vårt sätt och det rekomenderade* är att komponenternas stilregler i vår uppsättning kan krocka med varandra. Lägger man inte en regel i en komponent så kan den påverka flera andra komponenter. Det blir också mycket mer överskådligt när man har alla filer som hör till en komponent på ett och samma ställe.

Det borde vara relativt enkelt att flytta in styles för respektive komponent in komponenterna, men det kräver en hel del kontrollerande efter för att se att inget försvunnit i flytten.

lite info på i angulars dokumentation: https://angular.io/guide/component-styles

*Så görs det i CLI:et när man skapar en komponent

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

**Comment by kebarvid** [comment]
Ändringarna finns incheckade i branchen feature/component-styles och det finns även publicerat i vgr-komponentkartan-npm paketet som 7.6.0-beta4. vill man snabbt kolla över det mot befintliga verisionen så kan man checka ut komponetkartan-demo och köra branchen feature/component-styles där och jämföra med det som ligger på github-pages
