### ISSUE TITLE
Dropdown: Klickat alternativ väljs ej ifall fokus ligger på sökfält 

### ISSUE THREAD

**Issue by jvholmberg** [Vastra-Gotalandsregionen/komponentkartan#471]
### Beskrivning
Om fokus ligger på sökfältet i dropdown och du klickar på ett alternativ i dropdownen så väljs inte det alternativet utan fokus flyttas ist. Det krävs därmed ett andra klick. 

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.4.0**
* Angular version: **9.1.9**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
Öppna en dropdown där sökfältet finns. Sätt fokus på säkfältet och klicka sedan på ett alternativ i dropdownen.

### Förväntat beteende
Klickat alternativ skall väljas

### Faktiskt beteende
Fokus sätts på klickat alternativ

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by kebarvid** [comment]
Felet berodde på markera-alla texten som försvann när man lämnade fältet och flyttade positionen på valet man klickar på, nu ligger texten alltid där vid multiselect, men döljs när filter-rutan inte har fokus. Således flyttar sig inte valen längre.

Går att testa antingen genom att checka ut branchen `feature/dropdown-fixes` i komponentkartan repot eller installera npm paketet `vgr-komponentkartan@7.8.1-beta1` i ens lokala projekt.

**Comment by erfham** [comment]
Test ok
