### ISSUE TITLE
Dropdown select: Kan inte välja ett val som har valts tidigare

### ISSUE THREAD

**Issue by erfham** [Vastra-Gotalandsregionen/komponentkartan#472]
### Beskrivning
*Om man tidigare har valt alternativ x och ändrar till alternativ y så kan man inte längra välja alternativ x.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **7.3.8**
* Angular version: **9.1.7**
* Browsers: **IE 11**

### Steg för att påvisa problemet
*1. Gå till https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select i IE 11 och klicka på Exempel.
2. I dropdown "Stor, 50 alternativ", välj Val 2.
3. Välj nu Val 1 och sedan Val 2 igen.*

### Förväntat beteende
*Man kan klicka på Val 2 och det visas som valt alternativ*

### Faktiskt beteende
*Fokus går över till Val 2 men inget händer vid klick*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by kebarvid** [comment]
Har egentligen inte gjort någon ändring i koden här. Problemet dök upp i komponentkartan demo för att det i det projektet saknades pollyfills som aktiverade möjligheten till .includes() på arrayer och strängar som vi använder oss av i komponetkartan. Det  finns i komponetkartan-repot och det är nog därför det inte upptäckts tidigare. FRågan är vilket som är den korrekta lösningen här, bygga ut paketet mot en äldre ES-version, skriva om koden att använda sig av äldre (och krångligare) sätt att göra samma kollar eller att som jag nu gjort lägga till pollyfills i projektet.

Går att testa genom att köra senaste versionen av master-branchen i komponetkartan-demo repot.
