### ISSUE TITLE
Dropdown Select Chrome: flervals-dropdown visar inte valda alternativ

### ISSUE THREAD

**Issue by herrklaseen** [Vastra-Gotalandsregionen/komponentkartan#477]
### Beskrivning
I Internet Explorer 11, om man använder en dropdown select med "flerval", dvs en med checkboxar, och väljer (bockar i) ett eller flera val reflekteras inte de valen i den översta delen av dropdownen. 

Inga val gjorda:
![image](https://user-images.githubusercontent.com/650661/95550542-5d3a0900-0a09-11eb-9e33-09e3064f58f4.png)

Ett val gjort:
![image](https://user-images.githubusercontent.com/650661/95550599-75118d00-0a09-11eb-9e7e-5facb15a89ad.png)

Två val gjorda:
![image](https://user-images.githubusercontent.com/650661/95550649-822e7c00-0a09-11eb-80ee-c5b21f7e7110.png)

Som synes uppdateras "textfältet" när man gjort val, vilket sker i Chrome. Det funkar OK i Edge också.
![image](https://user-images.githubusercontent.com/650661/95552108-6678a500-0a0c-11eb-9ef1-a715c796ff88.png)

### Din miljö
* Version av vgr-komponentkartan: **7.5.1**
* Angular version: **9.1.7**
* Browsers: **Internet Explorer 11**

### Steg för att påvisa problemet

1. Öppna https://vastra-gotalandsregionen.github.io/komponentkartan-demo/dropdown-select i Internet Explorer 11
Klicka på Exempel, klicka på Alternativ med extra information
Välj ett eller flera alternativ

### Förväntat beteende
Textfältet högst upp uppdateras med de alternativ som är valda.

### Faktiskt beteende
Textfältet högst upp innehåller ordet "Välj".

**Comment by kebarvid** [comment]
Har egentligen inte gjort någon ändring i koden här. Problemet dök upp i komponentkartan demo för att det i det projektet saknades pollyfills som aktiverade möjligheten till .includes() på arrayer och strängar som vi använder oss av i komponetkartan. Det  finns i komponetkartan-repot och det är nog därför det inte upptäckts tidigare. FRågan är vilket som är den korrekta lösningen här, bygga ut paketet mot en äldre ES-version, skriva om koden att använda sig av äldre (och krångligare) sätt att göra samma kollar eller att som jag nu gjort lägga till pollyfills i projektet.

Går att testa genom att köra senaste versionen av master-branchen i komponetkartan-demo repot.

**Comment by louisebroo** [comment]
Vi ser det felet i Chrome också. Dessutom verkar det som att det ser ut som att man har filtrerat listan med alternativ när man öppnar dropdown efter att ha gjort en filtrering.. men när man väljer “markera alla” så markeras istället alla alternativ och inte bara de som man ser. Sen har jag en person i teamet som får upp texten “Tryck retur för att markera alla..” (eller vad det brukar stå) även för single select, men det har jag inte kunnat återskapa...

**Comment by CrestTheFury** [comment]
Kan inte återskapa problemet

**Comment by TorinWilliams** [comment]
Stäng pga att det inte kunde återskapas samt att beslutet är att vi inte ska stödja IE längre.
