### ISSUE TITLE
Markera alla funktion aktiv för dropdown single select.

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#479]
### Beskrivning
* Vid användning av  dropdown singel select med mer än 20 items där inga val redan gjorts beter den sig som om det vore en multi-select och uppmuntrar till att markera alla samt att navigering med piltangenter ej längre fungerar. *

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** 7.5.0 **
* Angular version: ** 9  **
* Browsers: ** Chrome **

### Steg för att påvisa problemet
* 1. Klicka på (eller öppna med Enter) en dropdown singel select  som har har fler än 20 items som inte redan har en ett aktivt val och navigera med pil ned till sök-inputen. 
* 2. Tryck på pil ned igen*

### Förväntat beteende
* 1. Att det inte skall stå texten '(tryck retur för att välja alla träffar)'  
* 2. Att det skall gå att fortsätta navigera med piltangenterna.*

### Faktiskt beteende
* 1. Texten '(tryck retur för att välja alla träffar)' finns fast det inte är en mult-select.
* 2. Det går inte längre att navigera med piltangenterna.
<img width="283" alt="singel-dropdown" src="https://user-images.githubusercontent.com/35916501/96719364-967b5d00-13a9-11eb-8f04-3937bce0f1b6.PNG">
 *

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Se bifogad skärmdunp.*

**Comment by kebarvid** [comment]
Ingen text skall nu visas för en singel-select.

Går att testa antingen genom att checka ut branchen `feature/dropdown-fixes` i komponentkartan repot eller installera npm paketet `vgr-komponentkartan@7.8.1-beta1` i ens lokala projekt.

**Comment by erfham** [comment]
Test ok
