### ISSUE TITLE
Det går att tabba utanför komponent modal dialog

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#48]
### Beskrivning
*Öppna "Modal dialog" och tabba. *

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc8 **
* Angular version: **version**
* Browsers: **Chrome, IE**

### Steg för att påvisa problemet
*Öppna "Modal dialog" och tabba.*

### Förväntat beteende
*Man kan enbart tabba inne i komponenten och inte utanför*

### Faktiskt beteende
*Det går även att tabba utanför komponenten.*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
Är möjligt att t.ex tabba till menyn och välja nytt alternativ med enter. Då navigerar man bort från sidan trots att den är modal... Hur förhindrar man klick på allt som ligger "under" modal?

**Comment by perakerberg** [comment]
Closed in 0.3.3-rc53
