### ISSUE TITLE
Omstylning av page-header

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#482]
### Beskrivning
Då flera system har minimalt med information i headern, så vill man att den i minsta läget tar mindre plats. Man vill dessutom att den skiljer sig mer mot innehållet i sidan, då alla objekt på sidan lätt flyter ihop. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Beskrivning av ändringar
* page-headern dockas nu mot headern, den strechas med sidan så den blir lika bred som hela sidan.
* ny färg ljusare gråskalefärg läggs till, ultradimmed, `#F8F8F8 `som blir bakgrundsfärgen på headern.
* En mörkgrå linje på 2px höjd läggs i botten på headern (secondary grå, `#BBBEBE`) 
* En skugga läggs under headern, `box-shadow: 0px 2px 8px #0000001A.` 
  * ev kan man behöva skjuta skuggan i x led lite då den kolliderar med menyn. 
* Vi behåller textens positionering i page headern som idag. Det innebär att den kommer placeras till höger, med 20px kvar till högerkanten och följa webbläsaren och således även login-infon (i header) då man drar i webbläsarfönstret
* minimi höjden på den ändras med, till 50px.

### Skärmdumpar mm
Nuvarande header
![image](https://user-images.githubusercontent.com/999511/97578912-bc2fe400-19f1-11eb-8d4a-7b6a0a83f88a.png)

Ny header
![image](https://user-images.githubusercontent.com/999511/97580150-3dd44180-19f3-11eb-88d9-b10af26b9198.png)

**Comment by louisebroo** [comment]
Kan den här stängas? @CrestTheFury
