### ISSUE TITLE
page toolbar

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#483]
### Beskrivning
Eftersom man på sikt vill lägga in tabbar (#478) i den nya page-headern (#482) behöver filter kunna flytta ut ur den för flera av våra system.

Dom kan givetvis läggas direkt i en page-block direkt under headern, men för att kunna göra filtren mer kompakta och även ha en bättre visuell indikation på var ett page block slutar då det är sticky och scrollas så får vill man bygga en speciell container som kallas för page-toolbar. Man har även försökt göra samma sak med ett transparent page-block i projekt, men det är lite oegenheter med clipping som resultat, samt att man inte får en tydlig visuell indikation på vad som klipps och var så föreslås alltså en specifik styling.

Om man dessutom renodlar så att vi försöker placera filter i en sådan container så kan man även låsa page-headern till att bli 50px hög, och få ytterligare lite luft i höjdled och underöka om vi kan dra ut page headern helt över hela sidan, eller minska texten i menyn, se (#484)

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Beskrivning
Bild på en page-toolbar
![image](https://user-images.githubusercontent.com/999511/98362872-46013200-202e-11eb-94f8-9027b05897b3.png)

Tanken är att den lägger sig precis som nya headern, och alltså tar sin bredd på sidan. Den följer med webbläsarens bredd.
![image](https://user-images.githubusercontent.com/999511/98363006-8eb8eb00-202e-11eb-99c8-a5d521e2e4ea.png)

Den skall även kunna ha ett extraläge (valbart) där man kan fälla ut fler filter om så behövs i en applikation:
![image](https://user-images.githubusercontent.com/999511/98363077-aa23f600-202e-11eb-992c-642f70971ce7.png)
![image](https://user-images.githubusercontent.com/999511/98363084-ae501380-202e-11eb-8735-e035f7205a0c.png)

Då innehåll scrollas (och den är sticky, även det bör vara valbart, men default är sticky=true) klipps det av den gråa linjen.
![image](https://user-images.githubusercontent.com/999511/98363134-c4f66a80-202e-11eb-9841-c5fc425eaa4e.png)

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by athid** [comment]
Frågan är om denna kan hanteras i grid-toolbar, eftersom vi i alla användningsfall har den kopplad till filtrering av en grid.

**Comment by ralvesmartins** [comment]
Stängs då det inte finns behov i dagsläget.
