### ISSUE TITLE
Ny stil på grid

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#489]
### Beskrivning
Då vi stylar om både header och page-block så hugger vi tag i grid:en med.

Två viktiga delar vi vill lösa är:
- Få header raden att skilja sig ifrån content visuellt
- Få ett öppet kort i grid att bli tydligare, användare har svårt att se vad de öppnat och hur det skiljer sig ifrån annat content (tex page-block)

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Övrig information, kodexempel och motivering till förändring
Nuvarande grid
![image](https://user-images.githubusercontent.com/999511/100200555-12b01580-2eff-11eb-88e8-612a705c32dc.png)

Och den tänkta nya grid:en
![image](https://user-images.githubusercontent.com/999511/100435912-e7642c80-309e-11eb-9d31-ad12ddc766f6.png)

### Förändringar
* gridens content (header,rows och pagnation) ligger på ett vitt kort, som har samma skugga och rundning som nya page-block (#488)
* varje grid item har inte längre en skugga
  * istället har de en tunn linje i topp (0,5px) och i botten (0,5px) färg #F0F0F0
  * och på hover får de temafärg, dimmad
  * har samma höjd som innan (35px)
* grid-header raden får en ny grå färg, ultradimmed grå #F8F8F8, samma som vi har i nya page headern (#482)
  * den får även en tjock linje i botten precis som nya page header, på 2px (secondary grå, #BBBEBE)
  * har lite högre höjd än innan (40px nu).
  * texten centreras i höjdled på dessa 40 px.
* pagnation raden får även den samma färg som hedern #F8F8F8.  har samma höjd som innan.

* ett öppet kort får en temafärgad bakgrund i toppen, samt en border + en skugga. Dessutom dras kortet ut (inte innehållet) med +5px på vänster och +5px högerkanten. (dvs om grid är 1100 bred, så är ett öppet kort 1110 bred)
* stylingen på ett öppet kort är:
```
background: #FFFFFF;
border: 1px solid #9EA2A2;
box-shadow: 0 0 15px 0 rgba(0,0,0,0.60);
border-radius: 2px;
```
* Styling på header raden på öppet kort är:
```
background: #EAECED;
border-bottom: 1px solid #9EA2A2;
border-radius: 2px 2px 0 0;
```

**Tillägg under utvecklingen**
Vi hade inte tänkt på att notiser i gamla grid lägger mellanrum mellan items. 
För att lösa det i nya gridden föreslås att notiser inte läggs hela vägen ut på kortet (den valbara kantlinjen är kvar som tidigare) men själva vgr-notificationen är indragen 10px i vänster och högerkant, samt 5px i top och botten så den tydligare ligger på kortet / list-itemet.

Och linjen runt list items görs lite tydligare, tidigare var kravet "en tunn linje i topp (0,5px) och i botten (0,5px) färg #F0F0F0", vilket byts mot en 1px tjock linje i topp och botten, fortfarande med #F0F0F0

![image](https://user-images.githubusercontent.com/999511/114146046-6869e500-9917-11eb-8315-68d7997b498a.png)

**Denna skall släppas på npm, med taggen dev. För att testas i respektive projekt innan vi släpper skarpt**

**Comment by johanmartin7811** [comment]
Buggen för storyn: [Liten del av griden visas ovanför menyn i chrome när man scrollar där griden har sticky header](https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/535)
