### ISSUE TITLE
Expandable div (eller ev alla komponenter) har en fokusmetod

### ISSUE THREAD

**Issue by brustablett** [Vastra-Gotalandsregionen/komponentkartan#494]
### Beskrivning
Ivard använder expandable div för en liten lista där grid-komponenten inte passade. Vi behöver kunna programmatiskt styra fokus till expandable div, men fokusmetod saknas i komponenten.

Vi tror även att fokusmetod saknas i andra komponenter, vilket kan göras i annan story eller bakas in i den här.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ?
* Angular version: ?
* Browsers: Chrome

### Förväntat beteende
Det går att styra fokus till en expandable div programmatiskt.

### Övrig information, kodexempel och motivering till förändring
En tanke har tidigare varit att alla saker som är fokuserbara också har en fokusmetod som gör att de kan få fokus programmatiskt. Vi löste detta på vissa komponenter då, men bara de med det mest uppenbara behovet. Alla komponenter borde gås igenom.

**Comment by synne1** [comment]
* Följande komponenter får en fokusmetod (om de redan har tabindex).

   * Expandable div
   * Button
   * Grid header column
   * Grid row
   * Checkbox
   * Radio group
   * Close Button *- inget tabindex*
   * Filter group/Filter tag
   * Card
   * Menu item
   * Title value heading *- inget tabindex*
   * Toggle  group/Toggle button
   * Table header
   * Table row *- inget tabindex*
   * Lock button  *- inget tabindex*
