### ISSUE TITLE
Datepickern tömmer felaktigt värde, men visar ändå upp det datum som inte fick väljas

### ISSUE THREAD

**Issue by brustablett** [Vastra-Gotalandsregionen/komponentkartan#498]
### Beskrivning
Datepickern har ett fel.
Om valideringar avvisar datumet, rensas värdet, men datumet visas fortfarande upp i date-pickern.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
I en implementation där vi har regler för vilka datum som får anges, mata in ett datum som bryter mot sådan regel (m.h.a. tangentbordet).

### Förväntat beteende
Borde rensa det datum som visas om det avvisas och värdet egentligen har tömts.
Det är dock viktigt att användaren kan se ett felmeddelande, så att det blir tydligt att datumet inte fick väljas.

### Faktiskt beteende
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by idajaehie** [comment]
Efter diskussioner i UX-Komponentkartemötet bestämde vi oss för att låta det felaktigt inmatade värdet stå kvar tillsammans med sitt felmeddelande för att användaren ska förstå vad som var fel och kunna rätta sitt värde därefter. Stänger dennna.

**Comment by idajaehie** [comment]
Efter diskussioner i UX-Komponentkartemötet bestämde vi oss för att låta det felaktigt inmatade värdet stå kvar tillsammans med sitt felmeddelande för att användaren ska förstå vad som var fel och kunna rätta sitt värde därefter. Stänger dennna.
