### ISSUE TITLE
Det går att editera i en stängd dropdown (Komponent dropdown multiselect)

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#50]
### Beskrivning
*Det går att editera i en stängd dropdown multiselect *

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: ** 0.3.1-rc8 **
* Angular version: **version**
* Browsers: **IE**

### Steg för att påvisa problemet
*Gå till komponent Dropdown multiselect. Lås upp och välj dropdown där det står "disabled" och välj alla. Fäll inte tillbaka dropdown. Spara med hänglås. Editera i den låsta dropdownen*

### Förväntat beteende
*Efter stängning med hänglås ska det inte gå att editera i dropdown*

### Faktiskt beteende
*Det går att editera*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
[Se exempel] (https://media.giphy.com/media/xUOxfmTtNBQkh2IngA/giphy.gif)

**Comment by CrestTheFury** [comment]
Löst i 0.3.3-rc43

**Comment by CrestTheFury** [comment]
Löst i 0.3.3-rc43
