### ISSUE TITLE
WCAG – Erbjud möjligheten att hoppa förbi återkommande innehåll (del 1)

### ISSUE THREAD

**Issue by idajaehie** [Vastra-Gotalandsregionen/komponentkartan#506]
### Beskrivning
Då man väljer ett menyval bör man komma direkt till toppen av sidans innehåll.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: Chrome

### Steg för att påvisa problemet
Efter val i menyn (med enter/space) behöver vi idag tabba oss genom resterande menyval innan vi går vidare till sidans innehåll. Det blir svårt för en användare som använder skärmläsaren att förstå hur sidan är uppbyggd samt att det med tangentbordet innebär en hel del tabbande för att ta sig in på en sida efter att man gjort sitt val i menyn.

### Förväntat beteende
När ett av menyalternativen är markerade och väljs med enter/space så skall fokus hoppa in på den valda sidan (om den har fokuserbart innehåll) istället för att fortsätta förflytta sig i menyn då man tabbar direkt efteråt.

### Faktiskt beteende
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring
Behöver stödjas för att uppfylla WCAG kriteriet 2.4.1
(https://webbriktlinjer.se/riktlinjer/75-gruppera-och-skapa-mojlighet-att-hoppa-forbi-delar-pa-sidorna/#)

### Skärmdumpar mm
Denna sida fungerar på sådant sätt (dock bara med enter) https://www.w3.org/TR/WCAG21/

**Comment by athid** [comment]
tog bort (alt visa upp en genväg), den kör vi som en separat story som skrivs nu på fredag.
