### ISSUE TITLE
WCAG – Justera strukturen/navigeringen i en grids sorterbara kolumner

### ISSUE THREAD

**Issue by idajaehie** [Vastra-Gotalandsregionen/komponentkartan#508]
### Beskrivning
I grid, där man har sorterbara kolumner, så går tab till varje sorterbar kolumn vilket i de fall du har många måste tabba igenom alla kolumner för att sen komma till listan.  

Genom att justera strukturen kan vi förenkla navigeringen i komponenten så att jag på ett enkelt sätt (tabb) kan gå vidare till nästa komponent. Och väl i gridens kolumnrad pila mig mellan de sorterbara kolumnerna. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: Chrome

### Steg för att påvisa problemet
Gå till en grids kolumnrad som har sorterbara kolumner (ex Ivard--> fakturor-->grid med fakturor) och börja tabba dig genom kolumnraden för att komma till första content (fakturan)

### Förväntat beteende
När jag tabbar mig till kolumnraden får komponenten fokus, därefter kan jag pila mig mellan valen. Om jag vill hoppa vidare till nästa komponent kan jag göra det med hjälp av tabb.

Viktigt att testa så skärmläsaren läser upp innehållet i hela kolumnraden. Dvs något i stil med "Lista med fakturor, står på 1a av 7 sorterbara kolumner, Fakturanummer, sorterad fallande"

### Faktiskt beteende
Behöver idag tabba mig till komponenten och därefter i varje sorterbar kolumn.

### Övrig information, kodexempel och motivering till förändring
Effektivisera användning av tangentbordsnavigering, skapa en meningsfull tabbordning och gruppera element som hör ihop så att användaren kan hoppa över innehåll vid behov. Stödjs av WVAG kriterer: 2.4.3, 2.4.1 och 2.5.3

**Denna skall släppas som demo först så att man kan testa av den**

**Comment by ralvesmartins** [comment]
Se exempel 2: https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html

**Comment by CrestTheFury** [comment]
Storyn har ändrats så man istället skall kunna ta sig ner till raderna genom att tryck pil ner från headern. Man kan även trycka pil ner från header-kolumnerna.

Detta då man hade problem att komma åt komponenter som lades i header-kolumnerna om man skulle stödja pil-höger och pil-vänster samt tab till första raden från headern
