### ISSUE TITLE
Monthpicker visar bara månad

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#51]
### Beskrivning
*Monthpicker visar bara månad och inte månad och år*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc8 **
* Angular version: **version**
* Browsers: **IE**

### Steg för att påvisa problemet
*Gå till komponent "Monthpicker. Visar fel datum enligt bifogad bild. Gäller även komponenten som är i disable läge.
![monthpickervisarintear](https://user-images.githubusercontent.com/33692196/32941687-e5aa0782-cb86-11e7-8187-14111df1ab1f.JPG)
".*

### Förväntat beteende
*Borde visa månad och år*

### Faktiskt beteende
*Visar endast månad*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
I exemplet i demokartan har man satt formatet "MMMM" vilket innebär månad, långt namn. Vill man ha ut år måste man sätta YYYY MM, för att få ut år samt månad.
