### ISSUE TITLE
När man har en filtertag i fokus ska tab lämna gruppen med filtertaggar

### ISSUE THREAD

**Issue by ghost** [Vastra-Gotalandsregionen/komponentkartan#511]
### Beskrivning
*Beskriv ärendet här. Var så utförlig som möjligt.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **Tror 8.1**
* Angular version: **vet inte**
* Browsers: **Chrome**

### Steg för att påvisa problemet
Filter tags verkar ha ändrat tab-beteende. Enligt spec (https://www.pivotaltracker.com/n/projects/1877465/stories/157359505) ska gruppen med taggar ha tabstop likt radio group, vilket innebär att man tabbar till den första taggen och nästa tab tar en vidare från taggarna till nästa sak i tabordningen. Nu gör tab att man kommer till nästa tag, men det är piltangenterna till för. Det funkar även med piltangenterna men det blir onödigt många tab om man inte vill interagera med alla filter taggar.

### Förväntat beteende
När en filter tag fokuserats ska man kunna navigera med piltangenterna till nästa tag och tab går till nästa objekt (förbi taggar).

### Faktiskt beteende
Tab flyttar fokus till nästa filter tag

**Comment by aljlo2** [comment]
Fixat i nytt släpp av version 12.0.4
