### ISSUE TITLE
Pipes i komponentkartan

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#512]
### Beskrivning
Vi har flera system som konverterar värden, tex;
HSA-ID
Valuta
Postnummer
Personnummer 
etc

Detta sker i angular pipes i respektive applikation. Vi vill flytta detta till komponentkartan för att skapa mer återanvändbara och synkade översättningar mellan data och presentation. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Lista pipes vi vill ta med här
HSA-ID
Valuta
Belopp
Postnummer
Personnummer 
Datum

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by aljlo2** [comment]
Släppt ny version av komponentkartan med 4 nya pipes: hsaidPipe, postnummer, personnummer samt komponentkartanCurrency. Ingen datum pipe implementerades då det finns att tillgå från Angular redan
