### ISSUE TITLE
Laddnings-state på grid

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#514]
### Beskrivning
Vi vill lägga till ett loading state på grid komponenten. Den skall ha en spinner centrerad i sig istället för sina grid items. Den kommer få ha en fördefinierad min-yta i detta state. 

Detta state skall underlätta användandet i applikationer då man istället för att dölja grid å lägga dit en spinner i applikationens kod bara kan byta state via en property på komponenten. Den är "disabled" och aria-disabled under tiden den är i loading state.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Önskat beteende
* Man kan sätta komponenten eller ta den ur "loading state" utifrån en property
* Den byter då till en spinner istället för att lista items
* Den är disabled / aria-disabled under statet (inga klick / fokus är tillåtna).
* då den är i loading state har den en fix höjd på 300px. Sen när man går ut ur loading och visar data så byter den till den höjden man vill ha på den. 

![image](https://user-images.githubusercontent.com/999511/114152334-71aa8000-991e-11eb-9fb2-5c9b80ae6f09.png)

**Comment by athid** [comment]
Vill vi dölja grid istället här, dvs dölja header och hela plattan och bara lägga spinner på transparent bakgrund?

**Comment by CrestTheFury** [comment]
Denna finns idag redan byggd.
Propertien heter "showLoader"
Vi kommer uppdatera KomponentkartanDemo med de saknade properties(arna).
