### ISSUE TITLE
Laddnings-state på button

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#515]
### Beskrivning
Vi vill lägga till ett loading state på button komponenten. Den skall ha en spinner centrerad i sig istället för sin label.

Detta state skall underlätta användandet i applikationer då man istället för att dölja knapp å lägga dit en spinner i applikationens kod bara kan byta state via en property på komponenten. Den är "disabled" och aria-disabled under tiden den är i loading state.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Önskat beteende
* Man kan sätta komponenten eller ta den ur "loading state" utifrån en property
* Den byter då till att lägga till en spinner centrerat i knappen och text och ev ikon döljs utan att påverka storleken av knappen.
* Den är disabled / aria-disabled under loading-statet (inga klick / fokus är tillåtna).

Design: https://www.figma.com/file/GEPTQQq2NyedLvoN5CM3uO/Komponenter?node-id=1030%3A268023
Stäm av med UX under utvecklingen angående padding och storlek på loader.

**Comment by athid** [comment]
Förslag, lägg spinner jämtill label.

**Comment by CrestTheFury** [comment]
@louisebroo @TorinWilliams @brustablett 
Frågor från refinement:
Bilderna stämmer inte överens riktigt med texten.
* Hur vill ni att den skall se ut när den är disablad (dvs loadern visas)?
* Det beskrivs i text att sec och discr skall loadern visas utan text, men det är text i bilden. Hur vill ni att det skall se ut?
* Primärknappen skulle bytas till sekundär-design vid laddning, men är det med eller utan disabled utseende?
* Sekundärknappen, hur skall den förändras vid laddning?

Om man har en loader på knappen och den är synlig, skall då Disabled propertien ersättas? Kan vara ett beteende som man kanske inte vill ha?

**Comment by louisebroo** [comment]
@CrestTheFury Jag har inte varit med Anders i designarbetet så jag har inte något svar på dina frågor men vi kan ju försöka klura på det tillsammans. Vet @TorinWilliams något om den här designen? Jag har inte sett den tidigare.

**Comment by TorinWilliams** [comment]
Tja! Jag kan misstänka att denna förbättringsförslag kommer från det som implementerades i vårdval för filuppladdningssidan. När man laddar upp flera filer samtidigt, så ville vi visa att arbetet pågår.
Caroline och Junior löste med att skapa en loader i en disablad knapp samt text under i stil med "1 av 4 filer uppladdad"

Mer än så vet jag inte. 

Utifrån texten (och min känsla för Anders stil) tolkar jag så här:

- det ska finnas en loading state för alla knappar
- den är disablad egentligen (går inte att klicka) men ser ut att vara aktiv (den är nog diskuterbar kan jag tro)
- han vill byta primär knapp till att se ut som sekundär (så att loadern syns tydligare än om det hade varit på den helgrå disablad bakgrund

Som sagt - jag tror vi skulle kunna ta en vända och hitta gemensam lösning som passar alla

**Comment by TorinWilliams** [comment]
... typ en laddning state to rule them all

**Comment by CrestTheFury** [comment]
Released in 9.0.6
