### ISSUE TITLE
Skip to content länk i menyn.

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#516]
### Beskrivning
I vårdval har man provat att lägga en "Hoppa till innehåll" länk på första tangeentbords-tabben på en sida.
Denna syns inte, utan visas bara då man trycker tab, aktiverar man den. Vi vill kopiera in denna lösningen till komponentkartan. I vårdval funkar den bara mot startsidan, men det är viktigt att den funkerar på samtliga sidor. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Förväntat beteende
* Då sidan är laddad syns inte "hoppa till innehåll"
* Om man trycker tab så fokuseras "hoppa till innehåll" och visas.
  * Trycker man tab igen, döljs den och menyn börjar fokuseras på första item
  * Trycker man retur eller mellanslag på den, så hoppar fokus till första interaktiva elementet på den sidan som visas för tilfället.
* Den tillhör vgr-header och ligger där i. (förslag till lösning)
*  "hoppa till innehåll" skall få fokus först, (sen menyn, sen inloggnings-bluppen och sen sidan (som det är idag)).
* om sidan inte har något interaktivt (fokuserbart) så hoppar den vidare till menyn istället.
* vi vill ha en property för att kunna slå av denna funktionaliteten

Tex W3 har ett exempel på denna https://www.w3.org/
Och här är ett bra exempel med. https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/#content

### Skärmdumpar mm
*Sidan är laddad*
![image](https://user-images.githubusercontent.com/999511/112315249-3e26ef00-8caa-11eb-9c33-7a85ec0c0851.png)
*Trycker på tab*
![image](https://user-images.githubusercontent.com/999511/112315334-54cd4600-8caa-11eb-8b2f-49b624a939f4.png)

Skall släppas som NPM demo paket för att kunna testas i de olika produkterna.

**Comment by aljlo2** [comment]
Är inte denna redundant med tanke på den här storyn: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/506 ?

**Comment by aljlo2** [comment]
Stänger ner den här med tanke på kommentar från [aljlo2](https://github.com/aljlo2) commented [on Feb 22, 2022](https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/516#issuecomment-1047581191) som redan är gjord och borde täcka behovet
