### ISSUE TITLE
vgr-modal i vgr-page-body

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#519]
### Beskrivning
vgr-modal fungerar inte om den ligger i vgr-page-body. Om den ligger i en vgr-page-body så täcker modalen inte hela fönstret utan bara body.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 8.1.3
* Angular version: 10
* Browsers: IE, Edge, Chrome & Firefox

### Steg för att påvisa problemet
```
<vgr-page>
    <vgr-page-header title="FELAKTIGA BESÖK">
      <h2>
        X besök att rätta
      </h2>
    </vgr-page-header>

  <vgr-page-body>
    <button (click)="DoFoo()">Öppna modal</button>
    <vgr-modal id="osparade-andringar-modal">
      <vgr-modal-header>
        Test
      </vgr-modal-header>
      <vgr-modal-content>
        <p>Test</p>
      </vgr-modal-content>
      <vgr-modal-footer>
      </vgr-modal-footer>
      <vgr-modal-footer>
        <div>
          <vgr-button default=true [buttonStyle]="'secondary'">Avbryt</vgr-button>
        </div>
      </vgr-modal-footer>
    </vgr-modal>
  </vgr-page-body>
</vgr-page>
```

### Förväntat beteende
Hela fönstret täcks av modalen
Krav: modal skall täcka hela sidan oavsett var i DOM den befinner sig.

### Faktiskt beteende
Bara page body täcks av modalen

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
![image](https://user-images.githubusercontent.com/44672809/113845256-9b846b00-9795-11eb-9731-d2d3bdaa8a38.png)

**Comment by athid** [comment]
Den är inte byggd för att läggas på den nivån, se API:t på komponentkartan demo; https://vastra-gotalandsregionen.github.io/komponentkartan-demo/modaldialog

Modal består av två delar. En komponent som läggs på samma nivå som <vgr-page>, med <vgr-modal>. Detta är en placeholder för det innehåll som sedan visas över applikationen. Den består i sin tur av tre delar, <vgr-modal-header>, <vgr-modal-content> och <vgr-modal-footer>.  Dvs inte i <vgr-page> noden.  

Finns det någon anledning varför ni vill lägga den inne i page?

**Comment by perut1** [comment]
Vi vill lägga modaler inne i de komponenter som vill initiera en modal. Och de komponenterna ligger i vgr-page. Om modalen måste ligga i "rooten" så betyder det att vi måste bubbla upp event ner till sid-komponenten och sedan skicka tillbaka resultetet igen till den ursprungliga komponenten igen. Det gör det nästan omöjligt för oss att hålla komponenterna separerade.

**Comment by athid** [comment]
Då kör vi denna på fredagens teknikmöte så kan vi kika lite mer på den.
