### ISSUE TITLE
Stänga ner modal / logga in med att trycka på ESC

### ISSUE THREAD

**Issue by johanmartin7811** [Vastra-Gotalandsregionen/komponentkartan#522]
**Beskrivning**
Med ESC kan man stänga ner en modal.
Det som händer i Privera är att man har focus på dropdown trycker ESC logga en som användare

Typ av ärende (kryssa i en med "x")

- [x]  Bugg
- [ ]  Förbättringsförslag

**Din miljö**
Privera
Browsers: Chrome, Edge, IE11

**Steg för att påvisa problemet**
Rensa webbinformation för närmaste timmen
Starta sida (Hittades i privera)
Focus sätts på dropdown för att Välja ett avtal
Tryck på ESC loggar in som ( Användare ) i Sidan utan att välja avtal 

**Förväntat beteende:**
Går inte att Stänga modal med ESC och logga i som användare
**Faktiskt beteende:**
Kan stänga ner modal och logga in som användare

**Comment by CrestTheFury** [comment]
Kunde inte återskapas i komponentkartan. Stänger denna så får man öppna den igen när Privera hunnit testa hos sig
