### ISSUE TITLE
Lägg till en egenskap på grid, zebra!

### ISSUE THREAD

**Issue by athid** [Vastra-Gotalandsregionen/komponentkartan#523]
### Beskrivning
För att göra långa grids lättare att läsa vill man kunna slå på zebra läget via en property.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Krav
* Man skall kunna slå av/på zebra läge. Default är av.
* Jämna list item rader får en bakgrundsfärg som är är F8F8F8 (ultradimmed) oberoende av tema. (om man börjar räkna på 1 och inte 0 😊 )
* Ojämna list item rader behåller samma bakgrundsfärg som idag
* Hover behåller samma färg i #489, oberoende av bakgrundsfärgerna ovan.
* När ett kort öppnas är det alltid vitt som innan. (zebrafärgen är alltså bara på stängda list items)

### Skärmdumpar mm
Exempel på zebra på:
![image](https://user-images.githubusercontent.com/999511/114148183-cb5c7b80-9919-11eb-8790-546d547a1cc0.png)

Och med notiser:
![image](https://user-images.githubusercontent.com/999511/114148240-d3b4b680-9919-11eb-8a74-8609af118e5a.png)

Och öppet kort:
![image](https://user-images.githubusercontent.com/999511/114148264-d9aa9780-9919-11eb-8f01-c92a74135271.png)

**Comment by CrestTheFury** [comment]
Released in 9.0.3
