### ISSUE TITLE
Sidhuvudets rubrik döljs av scrollbar i vissa fall

### ISSUE THREAD

**Issue by louisebroo** [Vastra-Gotalandsregionen/komponentkartan#526]
### Beskrivning
Jag har sett att sedan vi uppdaterade sidhuvudet så att det fyller ut hela sidan så hamnar rubriken till höger ibland (alltid?) under webbläsarens scrollbar. Detta gör att man som användare inte kan se rubriken. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **osäker men efter version 8 tror jag**
* Angular version: **vet inte**
* Browsers: **Chrome (på PC)**

### Steg för att påvisa problemet
* Gå in på en sida som är byggd med komponentkartan med ett sidhuvud som har rubrik i sig
* Observera huruvida scrollbar täcker rubriken

### Förväntat beteende
* Det går alltid att se sidans rubrik

### Skärmdumpar mm
<img width="120" alt="Skärmavbild 2021-04-13 kl  15 02 23" src="https://user-images.githubusercontent.com/35460884/114557491-04725400-9c6a-11eb-9246-773893fe34fd.png">

**Comment by CrestTheFury** [comment]
@louisebroo 
Vi kunde inte med version 8.2.1 eller 8.2.3 kunna återskapa problemet. Däremot så märker vi att Titeln på page-header ligger X:px från sidfönstret medan menydelarna i header ligger alltid med en marginal från kanten även när scrollen kommer.

Vi skulle vilja stänga denna storyn och isåfall öppna en ny där vi "alignar" informationen på högersidan för de båda headr:arna om ni vill ha det så.

**Comment by louisebroo** [comment]
@CrestTheFury jag tycker också att vi kan stänga den då, har inte heller sett beteendet det senaste. @ralvesmartins tycker du att vi ska öppna en ny story för att få till samma padding eller ska vi nöja oss så länge? Så länge man kan se allt innehåll så tror jag att det är good enough.

**Comment by ralvesmartins** [comment]
Skapar ny story för att aligna informationen på högersidan
