### ISSUE TITLE
Förhindra pageChanged

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan#544]
### Beskrivning
När man får en request från pageChanged så har själva sidan redan bytts och det finns inget sätt att förhindra det. Det hade varit bra om man antingen som i andra javascript-event returnera false för att förhindra själva sidbytet eller om det fanns en annan metod som kördes innan där man kunde avgöra om det är OK att byta sida i detta läge eller inte.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [X] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: **Browser1, Browser2**

### Steg för att påvisa problemet
*Beskriv hur man kan återskapa problemet.*

### Förväntat beteende
*Beskriv vad du förväntar dig skall hända*

### Faktiskt beteende
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perut1** [comment]
Samma sak gäller även sortering av en grid. Pilen ändrar sig även om man beslutar att inte genomföra själva sorteringen.

**Comment by ralvesmartins** [comment]
Samma problem beskrivs här: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/394
