### ISSUE TITLE
Skuggan på en Expanded grid-row täcker innehåll i intilliggande grid-rows

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#549]
### Beskrivning
*När en grid-row är expanded, borde avstånd till en intilliggande grid-row vara 10px. Just nu täcker box-shadow innehåll i intilliggande  *

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.2.3**
* Angular version: **10**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*Öppna en grid-row. Eller två intilliggande*

### Förväntat beteende
*10 pixlar padding på top och bottom, så att skuggan inte täcker innehåll i intilliggande grid-rows*

### Faktiskt beteende
*0 pixlar padding på top och bottom, så att skuggan täcker innehåll i intilliggande grid-rows*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
![1 expanded](https://user-images.githubusercontent.com/45225935/120783126-000c3e00-c52b-11eb-91c5-2415a3caf7f7.PNG)
![2 expanded](https://user-images.githubusercontent.com/45225935/120783249-1fa36680-c52b-11eb-92ef-528e6193f105.PNG)

**Comment by ralvesmartins** [comment]
Vad händer om du har två rader öppna bredvid varandra? Blir det då 20px?
Ska det vara samma avstånd i stora och lilla läget?

Stäm av implementation med @TorinWilliams under storiens gång.

**Comment by CrestTheFury** [comment]
Released in 9.0.6
