### ISSUE TITLE
Går inte att tabba eller navigera med pilartangenter (Komponent dropdown)

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#55]
### Beskrivning
*Går inte att tabba i dropdown eller navigera med piltangenter*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc8 **
* Angular version: **version**
* Browsers: **IE**

### Steg för att påvisa problemet
*Gå till komponent "Dropdown". Tabba inne i dropdown menyer eller navigera med pilar fungerar inte bra*

### Förväntat beteende
*Borde gå att tabba och navigera med pilarna*

### Faktiskt beteende
*Går inte att tabba eller navigera med pilar*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
Beror på att komponenten inte är WCAG anpassad än. Story för detta finns.
