### ISSUE TITLE
Texten på button växlar inte mellan Aktivera och Inaktivera 

### ISSUE THREAD

**Issue by johanmartin7811** [Vastra-Gotalandsregionen/komponentkartan#551]
### Beskrivning
*Tryck man på AV och PÅ knappen i toggle button hoppar Disabled texten i knappen till höger och vänster*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0-beta1** 
* Angular version: **Angular: 10.2.1 och Angular-Cli: 10.2.0**
* Browsers: **Chrome, IE11, Edge, Firefox**

### Steg för att påvisa problemet
*Öpnna upp Komponentkartan Demo / Button
*Gå till Button  > tryck på exempel*
*Tryck på AV och PÅ knappen*

### Förväntat beteende
*Texten på Button växlar mellan texterna Aktivera och Inaktivera när man aktiverar och inaktiverar fokusera och skicka knapparna*

### Faktiskt beteende
*Texten på Button visar bara Aktivera när man aktiverar och inaktiverar fokusera och skicka knapparna*

### Skärmdumpar mm
*
![image (1)](https://user-images.githubusercontent.com/56890634/122515575-ee886300-d00d-11eb-99cb-84cb6c782cdb.png)
![image (2)](https://user-images.githubusercontent.com/56890634/122515567-eaf4dc00-d00d-11eb-9d11-c46f51ba13e7.png)
*

**Comment by ZoeWall11** [comment]
Buggen finns endast när man kör komponentkartan lokalt (alltså localhost:3000)
