### ISSUE TITLE
Gemensamt mönster för att Spara

### ISSUE THREAD

**Issue by ralvesmartins** [Vastra-Gotalandsregionen/komponentkartan#553]
### Beskrivning
Som en användare vill jag ha ett enhetlig mönster och design för hur jag sparar data på en sida. 

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

**Comment by aljlo2** [comment]
Inte aktuellt i dagsläget då inget behov av detta finns
