### ISSUE TITLE
Designa om "selectable list" till den nya tabell-komponenten

### ISSUE THREAD

**Issue by ralvesmartins** [Vastra-Gotalandsregionen/komponentkartan#554]
### Beskrivning
Designa om "selectable list" till den nya tabell-komponenten.

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

**Comment by TorinWilliams** [comment]
Stängdes på grund av att en ny komponent kommer att erbjuda det som önskas - och då bir det istället en story i det systemets backlogg istället.
