### ISSUE TITLE
Notifications ska läsas upp av en skärmläsare

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#557]
### Beskrivning
*Notifications borde läsas upp av en skärmläsare - både vilken typ av notis, samt vad innehållet/medellandet är. Även så kallad assertive notiser borde läses upp när de uppstår utan att fokus flyttas. 

1. Notification som uppstår pga användarens handling eller en ändring av status tex.:
- en success notification när användaren sparar (eller error när sparandet misslyckas)
- "långsam nätverk" varningen 

Förslag - sätta dessa till role=alert eller testa med attributen "Aria-live"
https://www.w3.org/WAI/tutorials/forms/notifications/#listing-errors
samma princip som med problematiken med valideringar som beskrivs i denna: https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/451#issue-698060086*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0-beta2-b**
* Angular version: **, Angular: 10.2.1 och Angular-Cli: 10.2.0**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*Beskriv hur man kan återskapa problemet.*

### Förväntat beteende
*om ett fel uppstår tex "on submit", då ska den tillhörande notification läsas upp så att användaren förstår vilken typ det är (felmeddelande, varning, information, succé) samt vad medellandet är*

### Faktiskt beteende
*notification läses inte upp när den uppstår och går inte heller att sätta fokus på*

### Övrig information, kodexempel och motivering till förändring
*vi behöver uppfylla WCAG 3.3.1 - Error Identification
inspiration och förslag: https://www.w3.org/WAI/tutorials/forms/notifications/*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by CrestTheFury** [comment]
Released in 9.0.6
