### ISSUE TITLE
Ändring i en dropdown påverkar en annan dropdown (Komponent dropdown)

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#56]
### Beskrivning
*Ändrar värdet i tex dropdown 8 items till "jättelångt namn 1"  (jättelångt namn 3 är förvalt) och öppnar disabled dropdown och den visar samma värde "jättelångt namn 1" som den första menyn fast den visade ett annat värde innan "jättelångt namn 3".*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc8 **
* Angular version: **version**
* Browsers: **IE**

### Steg för att påvisa problemet
*Ändrar värdet i tex dropdown "8 items(förvalt)" till jättelångt namn 1  (jättelångt namn 3 är förvalt). Öppnar "disabled" dropdown och jättelångt namn 1 är markerad medans tootip visar "jättelångt namn 3" *

### Förväntat beteende
*Borde inte påverkan en annan meny*

### Faktiskt beteende
*En ändring i en meny påverkar en annan meny*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
Bör bero på uppsättning av variabler i .ts filen bakom dropdowns. Uppstädning behövs där.

**Comment by Jbraaf** [comment]
Löst i senare version
