### ISSUE TITLE
Gridheaderns innehåll linjerar inte som förväntat

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#580]
### Beskrivning
*Om man ex har en check-box i grid-header, linjerar den inte med de andra kolumner som ex är text*

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0**
* Angular version: **10**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*Lägg in en checkbox i en grid-header-column (rubrikraden) och text i dom andra  kolumnerna. *

### Förväntat beteende
*Alla kolumner alignar med varandra. *

### Faktiskt beteende
*Checkboxens placering för högt*

### Övrig information, kodexempel och motivering till förändring
*
<img width="429" alt="grid-align-items2" src="https://user-images.githubusercontent.com/35916501/133248433-45cc2668-560a-412f-8ee5-b54ad4a48a2d.PNG">

Align-items i vgr-grid-header borde vara baseline och inte center. (align-items: baseline)

<img width="464" alt="grid-align-items3" src="https://user-images.githubusercontent.com/35916501/133248459-8964d005-611d-4f3b-9d84-46b5077bf422.PNG">

 *

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by ralvesmartins** [comment]
Stäm av med UX om det ev behövs padding bottom
