### ISSUE TITLE
Bordern hoppar ut när byter mellan lilla och stora läget

### ISSUE THREAD

**Issue by johanmartin7811** [Vastra-Gotalandsregionen/komponentkartan#582]
### Beskrivning
*När man växlar mellan stora och lilla läget hoppar borden ut före griden / sidan.*

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0**
* Angular version: **10.2.1**
* Browsers: **chrome , edge, firefox, ie**

### Steg för att påvisa problemet
*Gå in på grid*
*Dra browsern så den växlar mellan stora och lilla läget*

### Förväntat beteende
*Borden följer med när man växlar mellan stora och lilla läget*

### Faktiskt beteende
*Borden hoppar ut innan griden / sidan *

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by CrestTheFury** [comment]
Kan inte återskapa problemet, troligen åtgärdad i ngn av bug-fixarna efter 8.3.0
