### ISSUE TITLE
Nya marginaler på notiser som inte passar så bra

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#583]
### Beskrivning
*Nya marginaler (egentligen padding men vit bakgrund) på notiser som inte passar så bra.*

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0**
* Angular version: **10**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*Jämför Notisers utseende med version 8.2.0. så har det tillkommit marginaler som inte passar in (iaf i Ivard)*

### Förväntat beteende
*Version 8.2.0*
![image-1](https://user-images.githubusercontent.com/35916501/134345464-76d1a1d1-e785-40db-a67b-baf93b5dbc7d.png)

### Faktiskt beteende
*Version 8.3.0*
<img width="535" alt="image-2" src="https://user-images.githubusercontent.com/35916501/134345484-71610b08-5a56-4127-a19e-1d74d010707b.PNG">

### Övrig information, kodexempel och motivering till förändring
*Det borde inte ligga några inbyggda marginaler (paddings med vit bakgrund) i notis-komponenten.*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
Före
![image](https://user-images.githubusercontent.com/35916501/134347223-d3af669b-db7e-4db0-aeb2-36a33c53f710.png)

Efter
![image](https://user-images.githubusercontent.com/35916501/134347396-5282baff-0264-4bb0-923d-d353726190bf.png)

**Comment by ralvesmartins** [comment]
Det verkar vara griden som lägger på padding
