### ISSUE TITLE
Exempel sidan stängs när man skall öppna / stänga andra besöket i griden 

### ISSUE THREAD

**Issue by johanmartin7811** [Vastra-Gotalandsregionen/komponentkartan#584]
### Beskrivning
*När man skall öppna/ stänga andra besöket i griden stängs exempel sidan med tangetbordet *

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.3.0**
* Angular version: **10.2.1**
* Browsers: **Chrome, Edge, Firefox**

### Steg för att påvisa problemet
[*Öppna grid demosidan*](https://vastra-gotalandsregionen.github.io/komponentkartan-demo/grid-documentation)
Klicka på exempel
Tabba ner till andra besöket i griden
Tryck på enter

### Förväntat beteende
*Besöket öppnar sig*
![Skärmklipp](https://user-images.githubusercontent.com/56890634/135257603-c455e5d9-0587-41b8-8381-fc0a15b518fc.PNG)

### Faktiskt beteende
*Exempel sidan stänger sig*
![Skärmklipp](https://user-images.githubusercontent.com/56890634/135257731-5d0e1df4-7558-4657-bd28-26a949e87daa.PNG)

### Skärmdumpar m

https://user-images.githubusercontent.com/56890634/135257259-678c9d1f-a13e-4046-9904-a90e9d367369.mp4

**Comment by aljlo2** [comment]
Problemet med denna "bugg" är att vi har en grid i en grid vilket den tyvärr inte är gjord för. Vi måste bygga om hela exempelsidan för griden för att rätta denna bugg eventuellt.
