### ISSUE TITLE
En vgr-dropdown i en vgr-cardsection visas "halv" vid expandering i IE och Edge 

### ISSUE THREAD

**Issue by perakerberg** [Vastra-Gotalandsregionen/komponentkartan#59]
### Beskrivning
Om man lägger en dropdown inuti en kortsektion döljs "pilen" när man expanderar kortsektionen. Gäller endast i IE 11 och Edge, i stora storleken.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc14**
* Angular version: **4.3.1**
* Browsers: **IE11, Edge**

### Steg för att påvisa problemet
*Lägg en vgr-dropdown i en card-section. Visa UI i Stora storleken. Stäng sektionen, expandera den. *

### Förväntat beteende
*Dropdown visas korrekt*

### Faktiskt beteende
*Högersidan på dropdown försvinner*

### Övrig information, kodexempel och motivering till förändring
*Det här verkar vara relaterat till rendering av animerat innehåll i IE och Edge. Om man minskar/ökar storlek på fönstret och får en uppdatering så rättas felet till. Om man öppnar developer tools, och försöker markera elementet så rättas det till*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
[Exempel](https://media.giphy.com/media/3o6fJarHPwQ0jlYsqQ/giphy.gif)

**Comment by FeliciaRingblom** [comment]
Kolla om detta löser sig med production mode

**Comment by perakerberg** [comment]
Det löste sig med production mode
