### ISSUE TITLE
Några pixlar av pageheadern går utanför sidan vid scroll

### ISSUE THREAD

**Issue by johanmartin7811** [Vastra-Gotalandsregionen/komponentkartan#596]
### Beskrivning
*När man scrollar på en sidan visas pageheadern utanför sidan, *

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [ ] Förbättringsförslag

### Din miljö,
* Version av vgr-komponentkartan: **8.4.1**
* Angular version: **10.2.1**
* Browsers: **Chrome, Edge, Firefox**

### Steg för att påvisa problemet
*Öppna localhost eller demosidan*
*Öppna valfri sida där man kan scrolla, Te x DatePicker*
*Öppna exempel*
*Scrolla*

### Förväntat beteende
*Pageheadern är lika stor som sidan vi scroll*

### Faktiskt beteende
*Pageheadern går utanför sidan vi scroll, gäller alla sidor*

### Skärmdumpar mm
![pageheader](https://user-images.githubusercontent.com/56890634/137465736-a11a3e59-3ebb-4bb8-9f93-a94005867462.PNG)

**Comment by CrestTheFury** [comment]
Released in 9.0.3
