### ISSUE TITLE
Valideringsrutan runt en dropdown växer för stor

### ISSUE THREAD

**Issue by perakerberg** [Vastra-Gotalandsregionen/komponentkartan#60]
### Beskrivning
Om man har en dropdown med valideringsfel så växer valideringsrutan sig för stor om layouten tillåter det. Exempel finns på demo-appens valideringssida. 

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.1-rc14**
* Angular version: **4.3.1**
* Browsers: **Chrome, IE11, Edge**

### Steg för att påvisa problemet
*Öppna demo-appen, navigera till validering, klicka i och ur dropdown.*

### Förväntat beteende
*Valideringsfel visas som en ruta med 10px padding runt dropdown*

### Faktiskt beteende
*Valideringsruta tar upp allt tillgängligt utrymme*

### Övrig information, kodexempel och motivering till förändring
Fix: Ta bort ```display:block``` på ```.validation```

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by FeliciaRingblom** [comment]
Avvakta tills stöd för Reactive Forms är implementerat
