### ISSUE TITLE
Checkbox uppdaterar inte value på formControl om man klickar på checkboxen.

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#604]
### Beskrivning
*  Checkbox uppdaterar inte formControl om man klickar på själva checkboxen. Om man klickar på texten eller använder tangentbordet fungerar det normalt. Problemet verkar bara uppstå om formuläret har udateon 'blur' eller 'submit '*.  

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.4.2**
* Angular version: **10**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*
1. Använd ett formulär (Reactive form) med en checkbox.
2. Sätt formuläret till updateon 'blur' eller 'submit'
3. Klicka på checkboxen (ex texten) och submitta formuläret
4. Läs av värdet på FormControl. 
*

### Förväntat beteende
*Värdet ändras*

### Faktiskt beteende
*Värdet har inte ändrats.*

### Övrig information, kodexempel och motivering till förändring
*Om man klickar på texten eller använder tangentbordet fungerar det normalt.*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by TorinWilliams** [comment]
Löses i samband med https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/448
