### ISSUE TITLE
Tabbutton uppdaterar active även om navigering stoppas.

### ISSUE THREAD

**Issue by synne1** [Vastra-Gotalandsregionen/komponentkartan#605]
### Beskrivning
*Om man vill förhindra navigering mellan tabbar (ex vid dirty formulär) indikerar den tabben man klickat active fast inputen active är false.*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [ x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.4.2**
* Angular version: **10**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
*Använd tabbuttons i en tabgroup och koppla (onSelectedChange) eller (click) event till en metod som hanterar navigering mellan tabbarna. Skapa ett uttryck som blir falskt så att active state inte uppdateras till det nya statet (alltså stannar på det gamla statet).*

### Förväntat beteende
*Active state stannar på det gamla värdet*

### Faktiskt beteende
*Active state får det nya värdet*

### Övrig information, kodexempel och motivering till förändring
**

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by CrestTheFury** [comment]
Released in 9.0.6
