### ISSUE TITLE
Ny komponent - Redigerbar tabell

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#608]
### Beskrivning
Både VEP och Vårdval har behov av en tabell som användarna kan redigera. Det nya komponenten är även tänkt som en förbättring för en komponent (selectable list) som finns endast i Vårdval.

### Acceptanskriterier
- tabellen är en <table> som kan redigeras
 - en extern event (knapptryck tex.) kan öppna redigeringsläge (se Övrig information nedan för framtida tankar)
- tabellen är deklarativt (men guidelines för vilka komponenter är tänkt att ha i tabellen kommer senare)

- Det ska vara möjligt att sätta max-höjd på komponenten
 - Vid maxhöjd visas skroll och en ram i $gray-secondary (#bbbebe)

### WCAG
En del tillgänglighet följer med om man använder korrekt semantisk markup.
**Se sektionen** "A semantically correct table" på https://a11y-101.com/development/tables

*uppläsning vid tabb in till tabellen (olika screenreaders hanterar på olika sätt, därför ställer jag inte dessa krav på ett specifikt sätt - utan kolla länken ovan för att förstå hur olika läsare kan reagera beroende på markup)
- tabellen ska deklarera sig som en tabell i en screenreader
- Användaren ska förstå vilken cell den befinner sig i (dvs "row 1, kolumn 1")
- Kolumnens rubrik ska läsas upp när man byter kolumn
- innehåll i cellen ska läsas upp 
 - inklusive status på ett interaktiv element som "text input, disabled"

*navigering 
- tabb in till tabellens första cell
- piltangenterna används för navigering i tabellen

### Övrig information, kodexempel 
I ett senare skede skulle man öppna för redigering per rad - dvs ett ikon-knapp i varje rad för redigering. 
### Skärmdumpar mm
[Figma exempel](https://www.figma.com/file/GEPTQQq2NyedLvoN5CM3uO/Komponenter?node-id=1064%3A245602)

<img width="640" alt="Screenshot 2021-11-25 at 13 07 43" src="https://user-images.githubusercontent.com/45225935/143439020-c7d1ae04-8435-4dd3-aa1a-350b2ed55175.png">

**Comment by CrestTheFury** [comment]
Released in 9.0.7

**Comment by CrestTheFury** [comment]
released in 9.0.7
