### ISSUE TITLE
Disabled checkboxar fungerar inte

### ISSUE THREAD

**Issue by alphaPlusPlus** [Vastra-Gotalandsregionen/komponentkartan#612]
### Beskrivning
*När jag sätter disabled till true för checkboxar fungerar det inte när checkbox är kopplat till reactiveforms (har formControlName attribute). Det ser samma ut som disabled är false* 

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **8.4.2**
* Angular version: **10.2.4**
* Browsers: **Chrome, Edge, Firefox**

### Steg för att påvisa problemet
Här till exampel disabled fungerar inte
<vgr-checkbox formControlName="invoiceIsAutomaticallyReviewed" [checked]="true" [disabled]="true" [label]=" 'Inaktiverad vald' "></vgr-checkbox>

Men här fungerar 
<vgr-checkbox  [checked]="true" [disabled]="true" [label]=" 'Inaktiverad vald' "></vgr-checkbox>

### Förväntat beteende
*När man sätter in disabled till true ska chekboxer vara inaktiveras även om den har formControlName-attributet*

### Övrig information, kodexempel och motivering till förändring
Här till exampel disabled  fungerar det inte
<vgr-checkbox formControlName="invoiceIsAutomaticallyReviewed" [checked]="true" [disabled]="true" [label]=" 'Inaktiverad vald' "></vgr-checkbox>

Men här fungerar 
<vgr-checkbox  [checked]="true" [disabled]="true" [label]=" 'Inaktiverad vald' "></vgr-checkbox>

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by TorinWilliams** [comment]
## Kommer lösas i denna https://github.com/Vastra-Gotalandsregionen/komponentkartan/issues/448
