### ISSUE TITLE
Demosidan - tydliggör exempeln av Expandable div

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#614]
# Beskrivning
*Exempeln av Expandable div på demosidan är enkel att missa samt att det går inte att tangentbordsnavigera till underliggande innehåll. Dessutom bör texten till tillgänglighet fyllas i enligt nedan:

### Tillgänglighets texten
- <vgr-expandable-div-header> rubrik läsas upp av skärmläsaren, sedan om den är expanded eller inte.
- Både `enter` och `mellanslag` triggar om den expanderas eller stängas
- Om [expanded]="false" ska tabb flytta fokus till nästa synlig <vgr-expandable-div-header>
- Om [expanded]="true" ska tabb flytta fokus till nästa underliggande rad 
 
### Acceptanskriterier
- Den visuella exempeln ska visas ovanför HTML exempeln på demosidan
- Den visuella exempeln består av 3 stycken expandable divs med varierande rubriktext
 - en av dessa bör även innehålla en underliggande <vgr-expandable-div-header> för att visa djupare hierarkin
 - för varje underliggande nivå ska innehåll justeras 10px till höger se exempeln under skärmdumpar nedan
*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [ x] Förbättringsförslag

### Övrig information, kodexempel och motivering till förändring
*Demosidan är komponentkartans ansikte utåt, både för designers och interna på VGR som behöver förstå sig på designsystemet och hur den fungerar. Det är därför viktigt att exempel och beskrivningar ska vara korrekt och tydlig*

### Skärmdumpar mm
![expandable](https://user-images.githubusercontent.com/45225935/145579272-ba4bca7c-047a-4fce-9dc5-458f2c215ce3.png)

**Comment by aljlo2** [comment]
Klart!
