### ISSUE TITLE
Boxen "Detaljer" för patientavgifter stängs när man klickar runt i rutan

### ISSUE THREAD

**Issue by GabrielleEltonius** [Vastra-Gotalandsregionen/komponentkartan#615]
### Beskrivning
*När man öppnat "detaljer" för patientavgifter på filuppladdningssidan så stänger sig boxen när man klickar i den. Dvs utan att trycka på knappen "stäng".*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **9.0.3**
* Angular version: **12.2.11**
* Browsers: **Chrome**

### Steg för att påvisa problemet
*1. Gå till filuppladdning
2. Ladda upp en egen fil eller välj en existerande med saknade patientavgifter
3. Klicka på "detaljer"
4. Klicka runt i rutan*

### Förväntat beteende
*Boxen för detaljer bör inte stängas*

### Faktiskt beteende
*Boxen stängs*

### Skärmdumpar mm
![DetaljerPatientAvgifter](https://user-images.githubusercontent.com/96078067/145866809-9c974f81-d78b-497d-a3a1-aa074779b93c.PNG)

**Comment by aljlo2** [comment]
Knappen tar upp hela området (längd och bredd för knapp) till vänster om sig när man högerställer den. Detta behöver åtgärdas.

**Comment by aljlo2** [comment]
Detta visade sig kunna lösas i klienten enbart så stänger denna.
