### ISSUE TITLE
Demosidan - Tydliggör filter tag exempel 

### ISSUE THREAD

**Issue by TorinWilliams** [Vastra-Gotalandsregionen/komponentkartan#616]
### Beskrivning
*Filtertag exempel på komponentkartan är inte tydlig och saknar padding på flera ställen. 
- Under "översikt" ska både aktiv och inaktiv filtertag visas, samt att deras text ska vara "aktiv" och "inaktiv". 
- Under exempel: 
 - ta bort "inaktivera filtertaggen" knapp
 - se skärmdump nedan för avstånd mellan alla element
### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **9.0.3**
* Angular version: **12.2.11**
* Browsers: **Edge, Chrome**

### Skärmdumpar mm

I Figma:
[Översikt](https://www.figma.com/file/JFqNsyNhOkF69fJZKqSmRv/Till-demosidan?node-id=19%3A3259)
[Exempel](https://www.figma.com/file/JFqNsyNhOkF69fJZKqSmRv/Till-demosidan?node-id=19%3A3183)

![Filtertag översikt](https://user-images.githubusercontent.com/45225935/145955580-b7ee9f7f-728a-4403-b523-b0db280abbb3.png)
![Filtertag exempel](https://user-images.githubusercontent.com/45225935/145958137-15f4dae6-cfa4-41bd-9188-433187a52d9c.png)

*

**Comment by aljlo2** [comment]
Klart!
