### ISSUE TITLE
Formatkontroller i "Datumfältet"

### ISSUE THREAD

**Issue by UlrikaJ** [Vastra-Gotalandsregionen/komponentkartan#617]
### Beskrivning
Datumfältet saknar idag formatkontroller vilket gör att användaren kan skriva in både bokstäver och siffror och även ogiltiga datum som te x 2020-15-14 eller 2021-13-40. 

Vi önskar att datumfältet har formatkontroller så att det endast är möjligt att mata in giltiga datum på formatet ÅÅÅÅMMDD dvs med månader och dagar som finns i kalendern.

Det fungerar om man sätter att fältet är obligatoriskt - men ska fungera även om den inte är obligatoriskt

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö  --- Får återkomma med det
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: **Edge **

### Steg för att påvisa problemet
*Beskriv hur man kan återskapa problemet.*
Fyll i bokstäver och det tar den in utan att protestera
Fyll i tokiga datum som inte finns tex månad >12 och dagar > det finns dagar i den månaden tex 2020-15-14 eller 2021-13-40. 

### Förväntat beteende
*Beskriv vad du förväntar dig skall hända*
Det ska inte vara möjligt att fylla i bokstäver.
Det ska endast vara möjligt att fylla i korrekta datum på formatet ÅÅÅÅMMDD.
Det ska endast vara möjligt att fylla i korrekta datum dvs endast 12 månader och endast rätt antal dagar per månad enligt vår vanliga kalender. 
Det är inte möjligt att fylla i datum som ser ut 2022-15-14 eller 2021-13-40 som i bilden ovan. 

### Faktiskt beteende
*Beskriv vad som händer*
Vi kan fylla i vad som helst och när man lämnar fältet ges ingen återkoppling utan den tar in vad som helst

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*
![Konstigt datum](https://user-images.githubusercontent.com/97515786/148926199-d99a7937-e35b-411f-971b-6fbccfeac906.png)

**Comment by UlrikaJ** [comment]
komponentkartan: 8.4.2
angular: 10.2
browser: chrome, firefox och edge

**Comment by aljlo2** [comment]
@UlrikaJ vi lyckas inte återskapa buggen i komponentkartan. Har du möjlighet att hjälpa oss?

**Comment by UlrikaJ** [comment]
Hej ! 
Javisst det kan jag göra. Låt oss undersöka detta. Bokar du upp ett teams möte? Min kalender är uppdaterad.

**Comment by aljlo2** [comment]
Kunde inte återskapa problemet, privera ska titta i sin kod att de implementerat komponenten korrekt. Efter avstämning med Ulrika så stänger vi denna.
