### ISSUE TITLE
Problem med Shift+Tab i grid

### ISSUE THREAD

**Issue by alphaPlusPlus** [Vastra-Gotalandsregionen/komponentkartan#624]
### Beskrivning
När man tryckt Shift+Tab när man är inne i första grid-row fokus flytta tillbaka  till grid-header

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **9.0.4**
* Angular version: **12.2.16**
* Browsers: **Chrome, Edge**

### Steg för att påvisa problemet
Som här:
![fel](https://user-images.githubusercontent.com/239385/153459916-a3c86d2a-3c97-4916-bf16-f82299d12fbc.gif)

### Förväntat beteende
![rätt](https://user-images.githubusercontent.com/239385/153459938-aa0b01f2-2467-46e3-8953-7ba98cb19b21.gif)

### Faktiskt beteende
Som här:
*Beskriv vad som händer*

### Övrig information, kodexempel och motivering till förändring

**Comment by CrestTheFury** [comment]
Hej, löste sig detta för er när du lade in fixen? Vill du stänga denna då?
/Caroline

**Comment by alphaPlusPlus** [comment]
Jepp det funkar efter fixan. Jag kan stänga denna
