### ISSUE TITLE
Förbättring av dropdown med sökfält i 

### ISSUE THREAD

**Issue by Jonkar89** [Vastra-Gotalandsregionen/komponentkartan#649]
### Beskrivning
*Vid användning av dropdown med sökfält i, önskas det att användaren direkt ska kunna skriva i sökfältet utan att behöva klicka i sökrutan. Flera utav våra användare föredrar att använda tangentbord framför mus, något som hade underlättat för dom.*

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: *9.1*
* Angular version: *12.2*
* Browsers: *Google Chrome*

### Förväntat beteende
*Förväntas att man direkt kommer in i sökfältet efter att man öppnat dropdownen*

### Faktiskt beteende
*Klickar man på dropdownen så behöver man idag klicka en extra gång i sökrutan för att kunna skriva i*

**Comment by aljlo2** [comment]
Fungerar på ovan angivet sätt i version 10.1.2 av vgr-komponentkartan samt version 15 av angular
