### ISSUE TITLE
[vgr-toggle-button] style slår inte igenom när [pressed] ändras till false

### ISSUE THREAD

**Issue by JohanW30** [Vastra-Gotalandsregionen/komponentkartan#653]
### Beskrivning
vgr-toggle-button ser fortfarande ut som den är  vald efter att man klickat för att "släcka" den.

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 11.0.2
* Angular version: 17.0.7
* Browsers: *

### Steg för att påvisa problemet
öppna https://vastra-gotalandsregionen.github.io/komponentkartan-demo/togglebutton
klicka två gånger på Av/På knappen

### Förväntat beteende
Efter att man ändrat från På till Av skall "secondary"-style visas

### Faktiskt beteende
Efter att man ändrat från På till Av ser knappen fortfarande ut att vara vald
klickar man  på någon annan yta i formuläret efteråt så uppdateras knappen som förväntat

### Skärmdumpar mm
![image](https://github.com/Vastra-Gotalandsregionen/komponentkartan/assets/158455500/97f05a40-7baf-4892-8ec8-44b8f7dd32a0)

**Comment by aljlo2** [comment]
Stänger issuen med svaret: anledning till att den inte ändras till secondary är för att den fortfarande är "i fokus" vilket är anledningen till att den ändras till secondary när man klickar någon annanstans på sidan då "fokus" försvinner då och den får sin riktiga styling.
