### ISSUE TITLE
Partiell route-matching i Menu

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#68]
### Beskrivning
Menyalternativ blir markerade även om de endast partiellt matchar route. 

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 0.3.1-rc14
* Angular version: 4.4.6
* Browsers: Chrome

### Steg för att påvisa problemet
Sätt URL på ett menyalternativ till en partiell route av ett annat menyalternativs URL.

### Förväntat beteende
Endast det menyval som helt matchar routen markeras och endast gruppen det tillhör expanderas.

### Faktiskt beteende
Samtliga partiellt matchande menyval markeras och expanderas.

### Övrig information, kodexempel och motivering till förändring
Exempel på meny där problemet uppstår.
```
this.menus = [{
      title: 'Min meny',
      groups: [{
        menuItems: [
          { title: 'Hem', url: '/' },
          { title: 'Val 1', url: '/a' },
          { title: 'Val 2', url: '/a/b' },
          { title: 'Grupp', menuItems: [
            { title: 'Val 3', url: '/a/b/c' }
          ] }
        ]
      }]
    } as IMenu];
```

### Skärmdumpar mm
<img width="200" alt="menu" src="https://user-images.githubusercontent.com/2772564/33136625-f747f0e4-cfa5-11e7-8962-29acdaa14bb4.png">

**Comment by perakerberg** [comment]
Verkar som om man kan konfigurera exact match på RouterLinkActive genom att sätta exactMatch: true, default är tydligen false. Good find! https://angular.io/api/router/RouterLinkActive

**Comment by perakerberg** [comment]
Fixed in 0.3.3-rc20
