### ISSUE TITLE
vgr-list renderas felaktigt när man håller musknappen nere utan att släppa.

### ISSUE THREAD

**Issue by mijokoletic** [Vastra-Gotalandsregionen/komponentkartan#70]
### Beskrivning
vgr-list renderas felaktigt när man håller musknappen nere utan att släppa.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 0.3.3-rc4
* Angular version: 4.4.4
* Browsers: chrome

### Steg för att påvisa problemet
* Visa först en tom vgr-lista 
* Klicka på en vgr-button (där clickeventet populerar lista) och håller musknappen i några sekunder och sen släpper du den.

### Förväntat beteende
headerkolumnerna och listkolumnerna ska ha samma storlek

### Faktiskt beteende
headerkolumnerna och listkolumnerna har inte samma storlek

### Övrig information, kodexempel och motivering till förändring
finns återskapad exempel på buggen i komponentkartan "demo/app/lists/lists"

### Skärmdumpar mm

![lista_halla_nere_musklicket](https://user-images.githubusercontent.com/31612448/33179026-55741bda-d068-11e7-89d6-cfa0f7854a29.gif)

**Comment by mijokoletic** [comment]
Bergis så är vgr-button en medbrottsling i buggen.

**Comment by perakerberg** [comment]
Beror på att vi gör cancelBubble på button.click. VI behöver förhålla oss till att alla element har en click-event som default, samt att keypress ska göra samma sak som click.

**Comment by CrestTheFury** [comment]
Löst i senare version
