### ISSUE TITLE
Byt ut div-taggar med klasser i komponenter mot riktiga komponenter

### ISSUE THREAD

**Issue by perakerberg** [Vastra-Gotalandsregionen/komponentkartan#71]
### Beskrivning
I flera komponenter används ng-content för att lägga ut dynamiskt innehåll. I de fall man har flera ng-content så behöver man selektera ut innehållet i varje ng-content med en css-klass annan selektor. 
När vi använder css-klasser blir det förvirrande för användaren som då måste veta onödigt mycket om vår underliggande struktur. Därför bör vi byta ut selektorer på css-klass mot riktiga taggar / komponenter. 
Exempel: ```.list-item__header -> <vgr-list-item-header>, .list-item__content -> <vgr-list-item-content>```

### Typ av ärende (kryssa i en med "x")
- [ ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: *3.3*
* Angular version: **4.3.1**
* Browsers: **Alla**

### Övrig information, kodexempel och motivering till förändring
Gör det enklare att förstå komponentkartan och gör den mer konsekvent

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by Jbraaf** [comment]
Löst i senare version
