### ISSUE TITLE
Kalenderikon syns ett kort ögonblick första gången du öppnar ett kort i Edge och IE

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#72]
### Beskrivning
Kalenderikon syns ett kort ögonblick första gången du öppnar ett kort i Edge och IE

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc4**
* Angular version: **version**
* Browsers: **Edge, IE11 (ser bra ut i Chrome)**

### Steg för att påvisa problemet
Gå in på BMM-sidan under menyalternativet enhet och öppna sedan en enhet. Då blinkar kalender ikonerna en gång innan de försvinner.

### Förväntat beteende
Kalenderikonerna skall inte synas när man öppnar ett kort

### Faktiskt beteende
Se steg för att påvisa problemet

**Comment by Jbraaf** [comment]
Löst i senare version
