### ISSUE TITLE
Kalender klipps av i komponent Monthpicker

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#73]
### Beskrivning
*Monthpicker klipps av när man har fällt ihop alla övriga kolumner.*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **version**
* Angular version: **version**
* Browsers: **Chrome**

### Steg för att påvisa problemet
*Gå till BMM sidan. Lägg till en ny enhet. Stäng alla fält förutom Enhetsinformationsfältet.
Öppna kalender. *

### Förväntat beteende
*Hela kalendern visas*

### Faktiskt beteende
*Kalendern visar bara översta raden*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller ö
![enhetssidankalenderklippsav](https://user-images.githubusercontent.com/33692196/33203263-bff2488c-d0ff-11e7-89aa-b6594c6980d0.JPG)
vrig information*

**Comment by perakerberg** [comment]
Closed with 0.3.3-rc53
