### ISSUE TITLE
Komponent back to top knapp försvinner vid zoom

### ISSUE THREAD

**Issue by maddefinlof** [Vastra-Gotalandsregionen/komponentkartan#77]
### Beskrivning
*Back to top knapp försvinner när man zoomar upp*

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc9 **
* Angular version: **version**
* Browsers: **Chrome, IE**

### Steg för att påvisa problemet
*1.Gå till "Back to top" och scrolla ner så att knappen visas.
2. Zomma in 150%*

### Förväntat beteende
*Knappen borde visas*

### Faktiskt beteende
*Knappen försvinner*

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by CrestTheFury** [comment]
Är löst i nästa stable version
