### ISSUE TITLE
Fel storlek valideringsrutan för dropdown/dropdownmulti, och calendar

### ISSUE THREAD

**Issue by mijokoletic** [Vastra-Gotalandsregionen/komponentkartan#85]
### Beskrivning
Röda valideringsrutan har fel storlek

### Typ av ärende (kryssa i en med "x")
- [x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc21**
* Angular version: **4.4.4**
* Browsers: **Chrome, IE, EDGE**

### Steg för att påvisa problemet
Triggra så att valideringen blir ej valid på nämna komponenter.

### Förväntat beteende
Felmeddelande är inte enligt detaljdesign/skiss.

### Faktiskt beteende
Felmeddelande enligt detaljdesign/skiss.

### Övrig information, kodexempel och motivering till förändring
*Text här*

### Skärmdumpar mm
![_error_fel_1](https://user-images.githubusercontent.com/31612448/33484902-ac1a72bc-d6a4-11e7-8445-aab9dc000059.PNG)

**Comment by CrestTheFury** [comment]
Löst i version 0.3.3-rc44
