### ISSUE TITLE
Collapible i Collapsible (card-section)

### ISSUE THREAD

**Issue by Faldo** [Vastra-Gotalandsregionen/komponentkartan#89]
### Vi vill gruppera items i lister, konstigt beteende när vi lägger card-section i card-section
*I Ksv får vi in Claims som har Visits. Dessa Visits kan vara med eller utan Warnings. Detta är högsta nivån i Claims. *

### Typ av ärende (kryssa i en med "x")
- [x ] Bugg
- [x] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: *0.3.3-rc22**
* Angular version: **^4.4.1**
* Browsers: **Chrome, Firefox**

### Steg för att påvisa problemet
*Lägger vgr-card-section i vgr-card-section. Då får vi problem med överlappande linjer (bottom/top) och expandera/kollaps pilen går åt fel håll*

### Förväntat beteende
*Enkla linjer mellan varje card-section och att expand/kollaps fungerar oberoende av varandra*

### Faktiskt beteende
*Lägger vgr-card-section i vgr-card-section. Då får vi problem med överlappande linjer (bottom/top) och expandera/kollaps pilen går åt fel håll*

### Övrig information, kodexempel och motivering till förändring
![expanded](https://user-images.githubusercontent.com/232093/33554201-0737dd5c-d8fc-11e7-8c38-1e2427081727.PNG)
![expanded](https://user-images.githubusercontent.com/232093/33554221-1f82abe4-d8fc-11e7-84fe-22585d374558.PNG)
![collpased](https://user-images.githubusercontent.com/232093/33554266-4edbdc58-d8fc-11e7-8157-e5f234501aed.PNG)

```
<vgr-card> 
<vgr-card-column>
    <!-- Visits -->
    <vgr-card-section [title]="'Besök med varningar'">
          <vgr-card-section *ngFor="let visit of visitsWithWarnings" [expanded]="false" 
                                     [title]="visit.patientIdentity" [subtitle]="visit.healthcareVisitDate">
         ........................................................................... 
         </vgr-card-section>
    <vgr-card-section [title]="'Övriga besök'">
      <vgr-card-section>
      </vgr-card-section>
    </vgr-card-section>
  </vgr-card-column>
</vgr-card>
```

### Skärmdumpar mm
*Infoga skärmdumpar eller övrig information*

**Comment by perakerberg** [comment]
Sektioner är endast ämnade för tvådelade kort. När det gäller full-size layout på kort så får respektive system implementera sitt eget innehåll.
