### ISSUE TITLE
Komponentkartan-demo, hovring över knapp påverkar annat innehåll

### ISSUE THREAD

**Issue by CrestTheFury** [Vastra-Gotalandsregionen/komponentkartan#93]
### Beskrivning
I IE på Button sidan under Exempel så hoppar Sekundärknapparna ner lite när man hovrar över en primärknapp. Sker endast första gången. Stänger du Exempel och öppnar igen så hoppar den på nytt vid hovring.

### Typ av ärende (kryssa i en med "x")
- [X] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: **0.3.3-rc32**
* Angular version: **XX**
* Browsers: **IE (edgemode samt 11mode**

### Steg för att påvisa problemet
1. Gå in på Button
2. Öppna exempel
3. Hovra över OK knappen, då hoppar allt ner lite samt så blir exempelrutan lite större

### Förväntat beteende
Rutan skall inte ändra storlek för att man hovrar över en knapp.

### Faktiskt beteende
Rutan ändrar storlek för att man hovrar över en knapp, samt så hoppar knapparna under ner lite grann

### Skärmdumpar mm
![iebuttonbug](https://user-images.githubusercontent.com/28337838/33610279-50494452-d9cb-11e7-920f-035633ec9dba.gif)

**Comment by perakerberg** [comment]
I exemplet i demo-kartan ligger komponenterna en div utan klasser. Lägger man dem i en row-layout så försvinner problemet. Troligen behöver man speca något ytterligare i sin div för att få komponenterna att stanna kvar i IE.

**Comment by Jbraaf** [comment]
Stänger detta tills det uppkommer i ett verkligt exempel / Johanna
