### ISSUE TITLE
VgrList kraschar i test med NgFor

### ISSUE THREAD

**Issue by kinbode** [Vastra-Gotalandsregionen/komponentkartan#97]
### Beskrivning
Test i Karma/Jasmine av komponenter med VgrList kraschar om NgFor används för att loopa ListItem. Detta fungerade i 0.3.3-rc22 men fungerar inte längre i 0.3.3-rc36. Det är oklart när det slutade fungera.

### Typ av ärende (kryssa i en med "x")
- [ x] Bugg
- [ ] Förbättringsförslag

### Din miljö
* Version av vgr-komponentkartan: 0.3.3-rc36
* Angular version: 4.4.6
* Browsers: Karma/Jasmine

### Steg för att påvisa problemet
Se kodexempel.

### Förväntat beteende
Det kraschar inte i test.

### Faktiskt beteende
Det kraschar i test.

### Övrig information, kodexempel och motivering till förändring
Explicit deklaration av ListItem fungerar:
```html
<vgr-list>
  <vgr-list-header></vgr-list-header>
  <vgr-list-item></vgr-list-item>
</vgr-list>
```
Tom loop över ListItem fungerar:
```html
<vgr-list>
  <vgr-list-header></vgr-list-header>
  <vgr-list-item *ngFor="let x of []"></vgr-list-item>
</vgr-list>
```
Icke tom loop över ListItem fungerar inte:
```html
<vgr-list>
  <vgr-list-header></vgr-list-header>
  <vgr-list-item *ngFor="let x of [{}]"></vgr-list-item>
</vgr-list>
```

**Comment by Jbraaf** [comment]
Löst i senare version
